-- 设计师分类（26-50）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Udio', 'Udio', '设计师', 'AI音乐生成工具，通过文字描述生成高质量原创音乐，适合视频配乐和创意项目背景音。', 'AI music generation tool creating original music from text for video and creative projects.', '免费+付费', 4.5, 'https://www.udio.com', ARRAY['文字生成原创音乐','多种音乐风格','高质量音频输出','商用授权可选'], true, true, true, 'udio', 'AI音乐', '文字描述生成高质量原创音乐', ARRAY['音乐质量出色','风格多样丰富','免费版可用'], ARRAY['商用需付费授权','生成时间较长'], '视频配乐和创意项目背景音首选', ARRAY['热门','今日推荐'], 2600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Suno AI', 'Suno AI', '设计师', 'AI歌曲创作工具，输入歌词和风格描述即可生成完整歌曲，包含人声和伴奏，效果惊艳。', 'AI song creation tool generating complete songs with vocals from lyrics and style descriptions.', '免费+付费', 4.6, 'https://suno.com', ARRAY['完整歌曲AI生成','人声伴奏一体','多种音乐风格','歌词自定义输入'], true, true, false, 'suno-ai', 'AI歌曲', '输入歌词即生成完整AI歌曲', ARRAY['歌曲完整度极高','人声效果惊艳','免费版可用'], ARRAY['商用授权需付费','风格控制有限'], '创意视频和品牌歌曲制作推荐', ARRAY['热门','TG精选'], 2500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Ideogram', 'Ideogram', '设计师', 'AI图像生成工具，擅长在图像中准确渲染文字，解决了其他AI工具文字生成错误的痛点。', 'AI image generator excelling at accurate text rendering within images.', '免费+付费', 4.5, 'https://ideogram.ai', ARRAY['图像内文字准确渲染','多种艺术风格','海报和封面设计','商用版权支持'], true, false, false, 'ideogram', 'AI图文', '擅长图像内准确渲染文字的AI', ARRAY['文字渲染准确度最高','海报设计效果好','免费版可用'], ARRAY['整体图像质量不如MJ','风格多样性有限'], '需要图像内含文字时的首选工具', ARRAY['热门'], 2400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Leonardo AI', 'Leonardo AI', '设计师', 'AI图像生成平台，提供多种专业模型，支持游戏资产、概念艺术和产品设计图生成。', 'AI image generation platform with multiple models for game assets and concept art.', '免费+付费', 4.6, 'https://leonardo.ai', ARRAY['多种专业AI模型','游戏资产生成','概念艺术创作','图像精细控制'], true, true, false, 'leonardo-ai', 'AI概念图', '多模型专业AI图像生成平台', ARRAY['专业模型选择多','游戏资产质量高','免费额度充足'], ARRAY['高级功能需付费','学习成本较高'], '游戏设计师和概念艺术家首选', ARRAY['热门','今日推荐'], 2300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Krea AI', 'Krea AI', '设计师', 'AI实时图像生成工具，支持边画边生成，实时预览AI效果，适合创意探索和快速迭代。', 'AI real-time image generation tool with live preview as you draw for creative exploration.', '免费+付费', 4.4, 'https://www.krea.ai', ARRAY['实时AI图像生成','边画边预览效果','图像风格迁移','创意快速迭代'], false, true, false, 'krea-ai', '实时AI绘图', '边画边实时预览的AI图像工具', ARRAY['实时预览体验独特','创意探索效率高','操作直觉化'], ARRAY['高级功能需付费','生成质量不稳定'], '创意探索和快速出图的有趣工具', ARRAY['热门'], 2200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Photoroom', 'Photoroom', '设计师', 'AI电商图片编辑工具，一键背景移除、替换和产品图美化，专为电商卖家和设计师优化。', 'AI e-commerce photo editor with one-click background removal and product image enhancement.', '免费+付费', 4.6, 'https://www.photoroom.com', ARRAY['一键背景移除替换','产品图AI美化','批量图片处理','电商模板库'], true, true, false, 'photoroom', 'AI电商图', '电商产品图AI一键美化工具', ARRAY['电商场景针对性强','批量处理高效','模板丰富专业'], ARRAY['免费版有水印','复杂场景偶有误差'], '电商卖家产品图处理必备工具', ARRAY['热门','TG精选'], 2100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Autodraw', 'Autodraw', '设计师', 'Google推出的AI绘图工具，识别手绘草图并推荐专业图标替换，帮助非设计师快速创作。', 'Google AI drawing tool that recognizes sketches and suggests professional icon replacements.', '免费', 4.2, 'https://www.autodraw.com', ARRAY['手绘草图AI识别','专业图标智能推荐','快速图形创作','完全免费使用'], false, false, false, 'autodraw', 'AI草图', 'Google手绘草图转专业图标工具', ARRAY['完全免费使用','操作极简单','Google品质保障'], ARRAY['功能相对简单','图标风格有限'], '非设计师快速制作简单图形推荐', ARRAY['免费'], 2000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Visily', 'Visily', '设计师', 'AI UI设计工具，支持截图转可编辑设计稿、手绘转原型，内置丰富UI组件库。', 'AI UI design tool converting screenshots and sketches to editable prototypes.', '免费+付费', 4.3, 'https://www.visily.ai', ARRAY['截图转可编辑设计稿','手绘转数字原型','丰富UI组件库','团队协作功能'], false, false, false, 'visily', 'AI UI', '截图转可编辑UI设计稿工具', ARRAY['截图转换效果好','组件库丰富','免费版可用'], ARRAY['高保真设计能力有限','导出格式有限'], '产品经理和初级设计师原型工具', ARRAY['免费'], 1900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mokker AI', 'Mokker AI', '设计师', 'AI产品图背景生成工具，上传产品图后自动生成专业场景背景，适合电商和品牌营销。', 'AI product photo background generator creating professional scenes for e-commerce.', '免费+付费', 4.4, 'https://mokker.ai', ARRAY['产品图场景背景生成','多种场景风格','批量图片处理','高分辨率输出'], false, false, false, 'mokker-ai', '产品背景', 'AI自动生成产品图专业背景', ARRAY['背景生成效果自然','场景风格多样','操作简单'], ARRAY['免费版次数有限','复杂产品效果一般'], '电商产品图快速生成专业背景', ARRAY['热门'], 1800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Designify', 'Designify', '设计师', 'AI自动化设计工具，一键将产品图转化为专业电商展示图，自动处理背景、阴影和构图。', 'AI design automation tool converting product photos into professional e-commerce visuals.', '免费+付费', 4.3, 'https://www.designify.com', ARRAY['产品图自动美化','背景阴影自动处理','电商展示图生成','批量自动化处理'], false, false, false, 'designify', 'AI美化', '产品图一键转专业展示图工具', ARRAY['自动化程度高','电商效果专业','批量处理高效'], ARRAY['自定义空间有限','免费版有限制'], '电商产品图批量自动化处理推荐', ARRAY['热门'], 1700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Stylar AI', 'Stylar AI', '设计师', 'AI图像风格化工具，将照片转化为各种艺术风格，支持精细控制风格强度和细节保留。', 'AI image stylization tool converting photos to various art styles with fine control.', '免费+付费', 4.3, 'https://www.stylar.ai', ARRAY['照片转艺术风格','风格强度精细控制','细节保留优化','多种艺术风格库'], false, false, false, 'stylar-ai', 'AI风格化', '照片转艺术风格精细控制工具', ARRAY['风格控制精细','细节保留好','风格库丰富'], ARRAY['免费版次数有限','复杂风格效果不稳定'], '创意图像风格化处理推荐', ARRAY['热门'], 1600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Recraft AI', 'Recraft AI', '设计师', 'AI矢量图和图标生成工具，专为设计师优化，支持品牌风格一致性控制和SVG直接输出。', 'AI vector and icon generation tool for designers with brand style consistency and SVG output.', '免费+付费', 4.5, 'https://www.recraft.ai', ARRAY['AI矢量图标生成','品牌风格一致性','SVG直接输出','设计系统集成'], true, false, true, 'recraft-ai', 'AI矢量图', '设计师专用AI矢量图标生成', ARRAY['矢量输出质量高','品牌一致性好','设计师友好'], ARRAY['免费版功能有限','学习成本较高'], '品牌图标和插画设计的高效工具', ARRAY['今日推荐'], 1500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Playground AI', 'Playground AI', '设计师', 'AI图像生成和编辑平台，免费额度慷慨，支持图像混合、局部编辑和多种生成模型切换。', 'AI image generation and editing platform with generous free quota and image mixing.', '免费+付费', 4.4, 'https://playground.com', ARRAY['免费额度慷慨','图像混合编辑','局部区域修改','多模型切换'], false, true, false, 'playground-ai', 'AI图像', '免费额度慷慨的AI图像生成平台', ARRAY['免费额度最慷慨','功能全面丰富','多模型可选'], ARRAY['界面较为复杂','高级功能需付费'], '想免费大量生成图像的设计师首选', ARRAY['免费','热门'], 1400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Canva文字转图', 'Canva Text to Image', '设计师', 'Canva内置的文字转图像功能，无需离开设计界面即可生成AI图像并直接用于设计项目。', 'Canva built-in text to image feature for generating AI images within the design workflow.', '免费+付费', 4.3, 'https://www.canva.com/ai-image-generator', ARRAY['设计内直接生成图像','多种艺术风格','一键插入设计稿','与Canva模板结合'], false, false, false, 'canva-text-to-image', 'Canva AI图', 'Canva内置文字转图像功能', ARRAY['工作流无缝集成','操作极简单','免费版可用'], ARRAY['生成质量不如专业工具','风格控制有限'], 'Canva用户无需切换工具的便捷选择', ARRAY['免费'], 1300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Artbreeder', 'Artbreeder', '设计师', 'AI图像混合创作工具，通过混合多张图像的基因参数创造独特艺术作品，适合角色和风景创作。', 'AI image breeding tool creating unique art by mixing image gene parameters.', '免费+付费', 4.2, 'https://www.artbreeder.com', ARRAY['图像基因混合创作','角色和风景生成','参数精细调节','社区作品分享'], false, false, false, 'artbreeder', 'AI混合', '图像基因混合创造独特艺术工具', ARRAY['创作方式独特有趣','角色设计效果好','社区资源丰富'], ARRAY['操作逻辑较特殊','高级功能需付费'], '角色设计和概念艺术探索推荐', ARRAY['免费'], 1200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Visme AI', 'Visme AI', '设计师', 'AI信息图表和演示文稿设计工具，通过文字描述自动生成专业图表、报告和演示稿。', 'AI infographic and presentation design tool generating professional charts from text.', '免费+付费', 4.3, 'https://www.visme.co', ARRAY['AI生成信息图表','演示文稿自动设计','数据可视化','品牌模板库'], false, false, false, 'visme-ai', 'AI图表', 'AI自动生成专业信息图表工具', ARRAY['图表设计专业美观','数据可视化强','模板库丰富'], ARRAY['免费版功能有限','复杂图表需手动调整'], '数据报告和演示文稿设计推荐', ARRAY['热门'], 1100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Patterned AI', 'Patterned AI', '设计师', 'AI无缝图案生成工具，通过文字描述生成可平铺的无缝图案，适合纺织品、包装和背景设计。', 'AI seamless pattern generator creating tileable patterns from text for textiles and packaging.', '免费+付费', 4.3, 'https://www.patterned.ai', ARRAY['无缝图案AI生成','多种图案风格','高分辨率输出','商用授权支持'], false, false, false, 'patterned-ai', 'AI图案', 'AI生成可平铺无缝图案工具', ARRAY['无缝效果处理好','图案风格多样','商用授权清晰'], ARRAY['免费版次数有限','复杂图案质量参差'], '纺织品和包装设计图案生成推荐', ARRAY['热门'], 1000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Booth AI', 'Booth AI', '设计师', 'AI产品摄影工具，上传产品图后自动生成专业级产品摄影效果，无需真实拍摄场地。', 'AI product photography tool generating professional product shots without real studio.', '免费+付费', 4.4, 'https://www.booth.ai', ARRAY['产品图专业摄影效果','多种场景风格','光影自动优化','高分辨率输出'], false, false, false, 'booth-ai', 'AI产品摄影', 'AI生成专业级产品摄影效果', ARRAY['摄影效果专业逼真','场景选择丰富','节省拍摄成本'], ARRAY['免费版次数有限','复杂产品效果一般'], '电商产品图低成本专业化首选', ARRAY['热门'], 900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Clipdrop', 'Clipdrop', '设计师', 'Stability AI旗下图像编辑工具集，包含背景移除、图像超分、光线调整等多种AI图像处理功能。', 'Stability AI image editing toolkit with background removal, upscaling and lighting tools.', '免费+付费', 4.5, 'https://clipdrop.co', ARRAY['背景一键移除','图像AI超分辨率','光线重新打光','图像去噪清晰化'], true, true, false, 'clipdrop', 'AI图像处理', 'Stability AI多功能图像处理套件', ARRAY['功能组合全面','处理质量高','免费版可用'], ARRAY['高级功能需付费','部分功能有使用限制'], '图像后期处理的全能工具套件', ARRAY['热门','今日推荐'], 800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Hotpot AI', 'Hotpot AI', '设计师', 'AI图像处理工具集，提供背景移除、图像修复、艺术风格化、图标生成等多种实用功能。', 'AI image processing toolkit with background removal, restoration and icon generation.', '免费+付费', 4.2, 'https://hotpot.ai', ARRAY['背景移除处理','图像AI修复','艺术风格化','图标批量生成'], false, false, false, 'hotpot-ai', 'AI工具集', '多功能AI图像处理工具集合', ARRAY['功能种类丰富','免费版可用','操作简单'], ARRAY['单项功能不如专业工具','免费版有水印'], '需要多种图像处理功能的设计师', ARRAY['免费'], 700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Namelix', 'Namelix', '设计师', 'AI品牌命名工具，通过关键词生成创意品牌名称，并自动生成对应的Logo设计方案。', 'AI brand naming tool generating creative brand names and logo designs from keywords.', '免费', 4.3, 'https://namelix.com', ARRAY['AI创意品牌命名','域名可用性检查','配套Logo生成','多种命名风格'], false, false, false, 'namelix', 'AI命名', 'AI生成创意品牌名称和Logo', ARRAY['命名创意丰富','域名检查方便','完全免费'], ARRAY['命名质量参差不齐','Logo设计较简单'], '初创公司品牌命名头脑风暴工具', ARRAY['免费'], 600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Brandmark', 'Brandmark', '设计师', 'AI Logo设计工具，输入品牌名称和关键词自动生成专业Logo，提供完整品牌资产包下载。', 'AI logo design tool generating professional logos from brand name and keywords.', '$25起', 4.3, 'https://brandmark.io', ARRAY['AI自动生成Logo','完整品牌资产包','多种设计风格','矢量文件输出'], false, false, false, 'brandmark', 'AI Logo', 'AI自动生成专业Logo品牌资产', ARRAY['Logo质量较专业','品牌资产完整','一次性付费'], ARRAY['原创性有限','复杂品牌需专业设计'], '初创公司快速获得专业Logo推荐', ARRAY['热门'], 500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Wepik AI', 'Wepik AI', '设计师', 'Freepik旗下AI设计平台，提供AI图像生成、模板设计和图像编辑，素材资源与Freepik打通。', 'Freepik AI design platform with image generation, templates and Freepik asset integration.', '免费+付费', 4.2, 'https://wepik.com', ARRAY['AI图像生成','海量设计模板','Freepik素材集成','图像AI编辑'], false, false, false, 'wepik-ai', 'AI设计', 'Freepik旗下AI设计创作平台', ARRAY['Freepik素材资源丰富','模板数量海量','免费版可用'], ARRAY['AI生成质量一般','界面较为复杂'], 'Freepik用户的AI设计延伸工具', ARRAY['免费'], 400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Pixlr AI', 'Pixlr AI', '设计师', '在线AI图像编辑器，集成AI背景移除、图像生成和智能修图功能，是Photoshop的轻量替代。', 'Online AI image editor with background removal, generation and smart retouching tools.', '免费+付费', 4.2, 'https://pixlr.com', ARRAY['AI背景移除','在线图像编辑','AI图像生成','智能修图工具'], false, false, false, 'pixlr-ai', 'AI修图', 'Photoshop轻量替代在线AI编辑器', ARRAY['无需安装在线使用','功能覆盖全面','免费版可用'], ARRAY['专业功能不如PS','免费版有广告'], '轻量图像编辑需求的免费替代工具', ARRAY['免费'], 300, 'active');
