-- 程序员分类（1-25）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('GitHub Copilot', 'GitHub Copilot', '程序员', 'GitHub和OpenAI联合推出的AI代码补全工具，实时根据上下文生成代码建议，支持主流IDE和编程语言。', 'GitHub and OpenAI AI code completion tool with real-time context-aware suggestions.', '$10/月', 4.8, 'https://github.com/features/copilot', ARRAY['实时代码补全','多语言支持','IDE插件集成','代码注释生成'], true, true, false, 'github-copilot', 'AI代码补全', 'GitHub官方AI代码补全神器', ARRAY['补全质量业界最高','上下文理解深','IDE集成无缝'], ARRAY['需要付费订阅','偶尔生成错误代码'], '每个程序员必装的AI编程助手', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Cursor', 'Cursor', '程序员', 'AI原生代码编辑器，基于VSCode构建，深度集成GPT-4，支持自然语言编写代码、重构和调试。', 'AI-native code editor built on VSCode with deep GPT-4 integration for natural language coding.', '$20/月', 4.8, 'https://cursor.sh', ARRAY['自然语言写代码','代码库全局理解','AI对话调试','一键代码重构'], true, true, true, 'cursor', 'AI编辑器', '最强AI原生代码编辑器', ARRAY['代码库理解最深','自然语言交互强','VSCode生态兼容'], ARRAY['价格偏高','大项目响应较慢'], '想用AI大幅提升编程效率的首选', ARRAY['热门','TG精选'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Tabnine', 'Tabnine', '程序员', 'AI代码补全工具，支持本地模型部署保护代码隐私，适合企业级代码安全要求的团队使用。', 'AI code completion with local model deployment for enterprise code privacy requirements.', '免费+付费', 4.5, 'https://www.tabnine.com', ARRAY['本地模型部署','代码隐私保护','多IDE支持','团队代码学习'], true, false, false, 'tabnine', 'AI补全', '支持本地部署的AI代码补全工具', ARRAY['隐私保护最强','企业级安全','本地部署可选'], ARRAY['免费版功能有限','补全质量不如Copilot'], '注重代码隐私的企业团队推荐', ARRAY['热门'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Codeium', 'Codeium', '程序员', '完全免费的AI代码补全工具，支持70+编程语言和40+IDE，个人使用永久免费，质量媲美付费工具。', 'Completely free AI code completion supporting 70+ languages and 40+ IDEs.', '免费', 4.6, 'https://codeium.com', ARRAY['永久免费使用','70+语言支持','40+IDE集成','代码搜索功能'], true, true, false, 'codeium', 'AI补全', '永久免费的高质量AI代码补全', ARRAY['完全免费无限制','语言覆盖最广','IDE支持最多'], ARRAY['企业功能需付费','偶尔补全不准确'], '预算有限的开发者最佳免费选择', ARRAY['免费','热门','TG精选'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Windsurf', 'Windsurf', '程序员', 'Codeium推出的AI代码编辑器，主打Cascade AI代理功能，能自主完成多步骤编程任务。', 'Codeium AI code editor featuring Cascade AI agent for autonomous multi-step coding tasks.', '免费+付费', 4.7, 'https://codeium.com/windsurf', ARRAY['Cascade AI代理','多步骤任务自动化','代码库全局感知','实时协作编辑'], true, true, true, 'windsurf', 'AI编辑器', 'Cascade AI代理自主完成编程任务', ARRAY['AI代理能力强','任务自动化程度高','免费版可用'], ARRAY['新产品稳定性待验证','复杂任务偶有错误'], 'Cursor的强力竞争者，免费版更慷慨', ARRAY['热门','今日推荐'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Amazon CodeWhisperer', 'Amazon CodeWhisperer', '程序员', 'AWS推出的AI代码生成工具，深度集成AWS服务，个人使用免费，自动扫描安全漏洞。', 'AWS AI code generation tool with deep AWS integration, free for individuals with security scanning.', '免费+付费', 4.4, 'https://aws.amazon.com/codewhisperer', ARRAY['AWS服务深度集成','安全漏洞自动扫描','个人免费使用','多语言代码生成'], false, true, false, 'amazon-codewhisperer', 'AWS AI', 'AWS官方AI代码生成安全扫描工具', ARRAY['AWS集成最深','安全扫描实用','个人免费'], ARRAY['非AWS场景优势不明显','补全质量一般'], 'AWS开发者的官方AI编程助手', ARRAY['免费','热门'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Replit AI', 'Replit AI', '程序员', '在线编程平台Replit内置AI助手，支持代码生成、调试和部署，无需本地环境配置。', 'Replit online coding platform with built-in AI for code generation, debugging and deployment.', '免费+付费', 4.4, 'https://replit.com', ARRAY['在线编程环境','AI代码生成','一键部署运行','多人协作编程'], false, true, false, 'replit-ai', '在线编程', 'Replit在线编程AI助手一键部署', ARRAY['无需本地环境','部署极简单','协作功能好'], ARRAY['网络依赖性强','高级功能需付费'], '快速原型和学习编程的在线工具', ARRAY['热门'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Sourcegraph Cody', 'Sourcegraph Cody', '程序员', 'AI代码助手，能理解整个代码库上下文，回答代码问题、生成代码和解释复杂逻辑。', 'AI coding assistant understanding entire codebase context for Q&A and code generation.', '免费+付费', 4.5, 'https://sourcegraph.com/cody', ARRAY['全代码库上下文理解','代码问答解释','多模型支持','企业私有部署'], true, false, false, 'sourcegraph-cody', 'AI代码库', '理解整个代码库的AI编程助手', ARRAY['代码库理解最深','多模型可选','企业部署安全'], ARRAY['配置较复杂','免费版有限制'], '大型代码库理解和导航的利器', ARRAY['热门'], 4300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('JetBrains AI', 'JetBrains AI', '程序员', 'JetBrains IDE系列内置AI助手，深度集成IntelliJ、PyCharm等IDE，提供代码补全和重构建议。', 'JetBrains IDE built-in AI assistant deeply integrated with IntelliJ and PyCharm.', '$10/月', 4.5, 'https://www.jetbrains.com/ai', ARRAY['IDE深度集成','代码补全重构','测试代码生成','代码审查建议'], false, false, false, 'jetbrains-ai', 'IDE AI', 'JetBrains IDE深度集成AI助手', ARRAY['IDE集成最深','重构建议准确','测试生成实用'], ARRAY['需要JetBrains订阅','价格叠加较贵'], 'JetBrains IDE用户的官方AI升级', ARRAY['热门'], 4200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Phind', 'Phind', '程序员', '专为开发者设计的AI搜索引擎，回答技术问题时自动搜索最新文档和代码示例，比Google更懂程序员。', 'AI search engine for developers answering technical questions with latest docs and code examples.', '免费+付费', 4.6, 'https://www.phind.com', ARRAY['技术问题AI搜索','最新文档自动检索','代码示例生成','多模型切换'], true, true, false, 'phind', 'AI搜索', '程序员专用AI技术搜索引擎', ARRAY['技术搜索最精准','文档检索及时','代码示例实用'], ARRAY['非技术问题效果差','高级功能需付费'], '替代Stack Overflow的程序员搜索工具', ARRAY['热门','今日推荐'], 4100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Warp', 'Warp', '程序员', 'AI增强的现代终端工具，内置AI命令建议、错误解释和自然语言转命令功能，重新定义终端体验。', 'AI-enhanced modern terminal with command suggestions, error explanation and natural language commands.', '免费+付费', 4.6, 'https://www.warp.dev', ARRAY['AI命令建议','自然语言转命令','错误自动解释','团队命令共享'], true, true, false, 'warp', 'AI终端', 'AI增强的现代终端重新定义体验', ARRAY['终端体验革命性','AI命令建议准确','错误解释实用'], ARRAY['仅支持Mac/Linux','高级功能需付费'], '提升终端效率的现代化AI工具', ARRAY['热门','TG精选'], 4000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Continue.dev', 'Continue.dev', '程序员', '开源AI代码助手，可连接任意LLM模型，支持VSCode和JetBrains，完全可定制化。', 'Open-source AI coding assistant connecting any LLM model for VSCode and JetBrains.', '免费', 4.5, 'https://continue.dev', ARRAY['开源完全免费','连接任意LLM','VSCode/JetBrains支持','完全可定制'], true, false, false, 'continue-dev', '开源AI', '开源可连接任意LLM的AI编程助手', ARRAY['完全开源免费','模型选择自由','隐私保护强'], ARRAY['配置需要技术能力','无官方支持'], '想自定义AI编程工具的开发者首选', ARRAY['免费','热门'], 3900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mintlify', 'Mintlify', '程序员', 'AI代码文档生成工具，自动为代码生成高质量文档，支持多种编程语言，一键生成API文档。', 'AI code documentation generator creating high-quality docs automatically for multiple languages.', '免费+付费', 4.4, 'https://mintlify.com', ARRAY['代码文档自动生成','API文档一键生成','多语言支持','文档网站托管'], false, false, false, 'mintlify', 'AI文档', 'AI自动生成高质量代码文档工具', ARRAY['文档生成质量高','API文档专业','托管服务方便'], ARRAY['高级功能需付费','自定义有限'], '懒得写文档的开发者必备工具', ARRAY['热门'], 3800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Pieces for Developers', 'Pieces for Developers', '程序员', 'AI开发者工作流工具，智能保存代码片段、截图和上下文，跨工具搜索和复用开发资产。', 'AI developer workflow tool for saving code snippets and context with cross-tool search.', '免费+付费', 4.4, 'https://pieces.app', ARRAY['代码片段智能保存','跨工具上下文搜索','开发资产管理','AI代码解释'], false, false, false, 'pieces-for-developers', '代码片段', 'AI智能管理开发者代码片段工具', ARRAY['代码片段管理好','跨工具搜索实用','上下文保留完整'], ARRAY['学习成本较高','高级功能需付费'], '提升开发工作流效率的知识管理工具', ARRAY['热门'], 3700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Snyk', 'Snyk', '程序员', 'AI安全漏洞检测平台，自动扫描代码、依赖包和容器中的安全漏洞，提供修复建议。', 'AI security vulnerability detection scanning code, dependencies and containers with fix suggestions.', '免费+付费', 4.6, 'https://snyk.io', ARRAY['代码安全漏洞扫描','依赖包漏洞检测','容器安全扫描','AI修复建议'], true, true, false, 'snyk', 'AI安全', 'AI自动扫描代码安全漏洞工具', ARRAY['漏洞检测最全面','修复建议实用','CI/CD集成好'], ARRAY['高级功能需付费','误报率偶有偏高'], '开发团队代码安全必备工具', ARRAY['热门','TG精选'], 3600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Postman AI', 'Postman AI', '程序员', 'API开发平台Postman内置AI功能，自动生成API测试、文档和代码，提升API开发效率。', 'Postman API platform with AI for auto-generating tests, documentation and code.', '免费+付费', 4.5, 'https://www.postman.com', ARRAY['API测试自动生成','API文档自动化','代码片段生成','AI接口调试'], true, true, false, 'postman-ai', 'API测试', 'Postman内置AI自动生成API测试', ARRAY['API测试生成准确','文档自动化好','团队协作强'], ARRAY['高级功能需付费','界面较为复杂'], 'API开发者提升测试效率必备', ARRAY['热门'], 3500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Sentry AI', 'Sentry AI', '程序员', '应用监控平台Sentry内置AI功能，自动分析错误根因、生成修复建议，加速Bug修复流程。', 'Sentry monitoring platform with AI for root cause analysis and fix suggestions.', '免费+付费', 4.5, 'https://sentry.io', ARRAY['错误根因AI分析','修复建议自动生成','性能问题检测','告警智能聚合'], true, false, false, 'sentry-ai', 'AI监控', 'Sentry AI自动分析错误根因工具', ARRAY['根因分析准确','修复建议实用','集成生态丰富'], ARRAY['高级功能需付费','数据量大时较慢'], '生产环境Bug快速定位修复必备', ARRAY['热门'], 3400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Datadog AI', 'Datadog AI', '程序员', '云监控平台Datadog内置AI功能，自动检测异常、预测故障和生成运维建议，保障系统稳定性。', 'Datadog cloud monitoring with AI anomaly detection, failure prediction and ops recommendations.', '$15/主机/月', 4.6, 'https://www.datadoghq.com', ARRAY['AI异常自动检测','故障预测分析','日志智能分析','告警降噪处理'], false, false, false, 'datadog-ai', 'AI运维', 'Datadog AI云监控异常检测平台', ARRAY['监控覆盖最全面','异常检测准确','告警降噪好'], ARRAY['价格较高','配置复杂度高'], '云原生应用监控运维的行业标准', ARRAY['热门'], 3300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('GitLab Duo', 'GitLab Duo', '程序员', 'GitLab内置AI功能套件，覆盖代码补全、代码审查、安全扫描和DevOps全流程AI辅助。', 'GitLab built-in AI suite covering code completion, review, security and full DevOps workflow.', '$19/用户/月', 4.4, 'https://about.gitlab.com/gitlab-duo', ARRAY['代码补全生成','AI代码审查','安全漏洞扫描','DevOps流程AI'], false, false, false, 'gitlab-duo', 'DevOps AI', 'GitLab全流程DevOps AI助手套件', ARRAY['DevOps集成最深','代码审查实用','安全扫描可靠'], ARRAY['需要GitLab订阅','功能深度不如专业工具'], 'GitLab用户DevOps全流程AI升级', ARRAY['热门'], 3200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('LangChain', 'LangChain', '程序员', 'LLM应用开发框架，提供链式调用、记忆管理、工具集成等模块，是构建AI应用的主流框架。', 'LLM application development framework with chaining, memory and tool integration modules.', '免费', 4.5, 'https://www.langchain.com', ARRAY['LLM链式调用','记忆管理模块','工具集成框架','Agent构建支持'], true, true, false, 'langchain', 'AI框架', 'LLM应用开发主流框架', ARRAY['生态最成熟丰富','文档完善','社区活跃'], ARRAY['抽象层有时过重','版本更新频繁'], '构建LLM应用的首选开发框架', ARRAY['热门','TG精选'], 3100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Hugging Face', 'Hugging Face', '程序员', 'AI模型托管和共享平台，提供数万个开源模型、数据集和Spaces应用，是AI开发者的GitHub。', 'AI model hosting and sharing platform with thousands of open-source models and datasets.', '免费+付费', 4.8, 'https://huggingface.co', ARRAY['开源模型库最大','数据集共享平台','Spaces应用托管','Transformers框架'], true, true, false, 'hugging-face', 'AI模型库', 'AI开发者的GitHub模型共享平台', ARRAY['模型资源最丰富','社区最活跃','开源生态最强'], ARRAY['高级计算需付费','部分模型质量参差'], 'AI开发者必须掌握的核心平台', ARRAY['热门','TG精选'], 3000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Vercel AI SDK', 'Vercel AI SDK', '程序员', 'Vercel推出的AI应用开发SDK，简化在Next.js等框架中集成LLM的流程，支持流式输出。', 'Vercel AI application SDK simplifying LLM integration in Next.js with streaming support.', '免费', 4.6, 'https://sdk.vercel.ai', ARRAY['LLM集成简化','流式输出支持','多模型统一接口','React Hooks集成'], true, false, true, 'vercel-ai-sdk', 'AI SDK', 'Vercel简化LLM集成的AI开发SDK', ARRAY['集成极简单','流式体验好','Next.js最佳搭配'], ARRAY['主要面向Vercel生态','文档仍在完善'], 'Next.js开发者构建AI应用的最快方式', ARRAY['热门','今日推荐'], 2900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Replicate', 'Replicate', '程序员', 'AI模型云端运行平台，通过API调用数千个开源AI模型，无需自己部署GPU基础设施。', 'Cloud platform for running AI models via API without managing GPU infrastructure.', '按用量付费', 4.5, 'https://replicate.com', ARRAY['数千模型API调用','无需GPU基础设施','按用量付费','自定义模型部署'], true, false, false, 'replicate', 'AI模型API', '无需GPU即可调用数千AI模型', ARRAY['模型选择最丰富','按量付费灵活','部署极简单'], ARRAY['延迟较高','成本随规模增加'], '快速集成各类AI模型的最简方式', ARRAY['热门'], 2800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Linear AI', 'Linear AI', '程序员', '现代项目管理工具Linear内置AI功能，自动生成Issue描述、总结进度和预测完成时间。', 'Modern project management tool Linear with AI for issue generation and progress summaries.', '$8/用户/月', 4.6, 'https://linear.app', ARRAY['Issue AI自动生成','进度智能总结','完成时间预测','代码关联追踪'], false, true, false, 'linear-ai', 'AI项目', 'Linear内置AI项目管理工具', ARRAY['界面设计最优雅','AI功能实用','开发者体验好'], ARRAY['功能相对简单','高级功能需付费'], '开发团队项目管理的现代化工具', ARRAY['热门'], 2700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('SonarQube AI', 'SonarQube AI', '程序员', '代码质量和安全分析平台，AI辅助检测代码异味、漏洞和技术债务，支持30+编程语言。', 'Code quality and security platform with AI detecting code smells, vulnerabilities and tech debt.', '免费+付费', 4.5, 'https://www.sonarsource.com', ARRAY['代码质量AI分析','安全漏洞检测','技术债务追踪','CI/CD流水线集成'], false, false, false, 'sonarqube-ai', '代码质量', 'AI代码质量安全分析30+语言', ARRAY['代码质量分析深','安全检测全面','CI集成方便'], ARRAY['配置较复杂','企业版价格高'], '团队代码质量管控的行业标准工具', ARRAY['热门'], 2600, 'active');
