-- 2026年Q1行业报告新增工具（律师+设计师部分）
-- 共约30个新工具，分两个文件

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Harvey AI', 'Harvey AI', '律师', '专为律师事务所设计的生成式AI平台，支持合同分析、尽职调查、法律研究和文书起草，已获全球顶级律所验证。', 'Generative AI platform for law firms supporting contract analysis, due diligence and legal research.', '企业定价', 4.8, 'https://www.harvey.ai', ARRAY['合同智能分析审查','尽职调查自动化','法律研究加速','多语言文书起草'], true, true, true, 'harvey-ai', '律所AI平台', '顶级律所专用生成式AI，合同审查效率提升8倍', ARRAY['大所验证效果卓越','安全合规有保障','多语言支持'], ARRAY['仅面向企业客户','价格不透明'], '大型律所数字化转型首选', ARRAY['热门','TG精选','2026新品'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Thomson Reuters CoCounsel', 'CoCounsel', '律师', '汤森路透推出的AI法律助手，深度整合Westlaw数据库，支持法律研究、合同分析和案例摘要生成。', 'Thomson Reuters AI legal assistant integrated with Westlaw for research and contract analysis.', '$99/月起', 4.7, 'https://legal.thomsonreuters.com/cocounsel', ARRAY['Westlaw数据库深度整合','法律研究自动化','合同条款分析','案例摘要生成'], true, true, true, 'cocounsel', 'AI法律助手', '汤森路透官方AI法律助手，权威数据加持', ARRAY['Westlaw数据权威','研究效率极高','安全合规'], ARRAY['价格较高','主要面向英文法律'], '英文法律研究首选工具', ARRAY['热门','TG精选','2026新品'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('通义法睿', '通义法睿', '律师', '阿里巴巴推出的中文法律AI大模型，专为中国法律场景优化，支持合同审查、法律研究和文书生成。', 'Alibaba Chinese legal AI model optimized for China legal scenarios including contract review.', '免费+付费', 4.5, 'https://tongyi.aliyun.com', ARRAY['中文合同智能审查','法律条文检索','文书自动生成','法律风险识别'], true, true, true, 'tongyi-fasui', '中文法律AI', '阿里通义法睿，中文法律场景最强AI', ARRAY['中文理解能力强','免费版可用','持续更新迭代'], ARRAY['英文能力有限','部分功能需付费'], '中国律师和法务首选AI工具', ARRAY['热门','TG精选','国产精品'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Luminance', 'Luminance', '律师', '英国AI法律科技公司，提供合同审查、尽职调查和法律文件分析的企业级AI平台，支持70+语言。', 'UK AI legal tech providing enterprise contract review, due diligence and document analysis in 70+ languages.', '企业定价', 4.6, 'https://www.luminance.com', ARRAY['AI合同审查','尽职调查自动化','异常条款检测','70+语言文件分析'], true, false, false, 'luminance', '合同尽调AI', '企业级AI法律文件分析，70+语言支持', ARRAY['多语言能力强','异常检测精准','大所广泛采用'], ARRAY['价格较高','需专业培训'], '跨境并购尽调的高效工具', ARRAY['热门'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('无讼AI Pro', '无讼AI Pro', '律师', '无讼平台推出的AI增强版，接入DeepSeek大模型，中文案例检索准确率提升40%，支持智能文书生成。', 'Wusong AI Pro with DeepSeek integration, 40% improved Chinese case search accuracy.', '¥299/月', 4.4, 'https://www.wusong.com', ARRAY['DeepSeek加持检索','中文案例智能分析','法律文书生成','律师社区资源'], true, true, true, 'wusong-ai-pro', '中文案例检索', '无讼AI Pro，DeepSeek加持中文法律检索', ARRAY['中文案例库庞大','DeepSeek理解准确','社区资源丰富'], ARRAY['英文支持有限','高级功能需付费'], '中国律师日常案例检索首选', ARRAY['热门','国产精品','2026新品'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Westlaw AI', 'Westlaw AI', '律师', '汤森路透Westlaw平台的AI增强版，全球最权威法律数据库，支持智能案例检索和法规查询。', 'AI-enhanced Westlaw from Thomson Reuters, world most authoritative legal database.', '$69/月起', 4.6, 'https://legal.thomsonreuters.com/westlaw', ARRAY['全球权威案例检索','法规智能查询','引用有效性验证','AI摘要生成'], true, true, false, 'westlaw-ai', '权威法律库', '全球最权威法律数据库AI版', ARRAY['数据权威性最高','案例覆盖最全','更新及时'], ARRAY['价格较高','主要面向英文'], '英文法律研究的权威工具', ARRAY['热门'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Midjourney V7', 'Midjourney V7', '设计师', '2026年Q1发布的Midjourney最新版本，图像质量再次跃升，提示词理解能力接近人类设计师水平，新增视频生成功能。', 'Latest Midjourney V7 with leap in image quality, near-human prompt understanding and new video generation.', '$10/月', 4.9, 'https://www.midjourney.com', ARRAY['顶级图像生成质量','提示词深度理解','新增视频生成','商业授权支持'], true, true, true, 'midjourney-v7', 'AI图像旗舰', 'Midjourney V7，2026年最强AI图像生成工具', ARRAY['图像质量业界最高','提示词理解极强','新增视频能力'], ARRAY['需Discord使用','免费版受限'], '设计师AI图像生成首选，必须掌握', ARRAY['热门','TG精选','2026新品'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('可灵AI 2.0', '可灵AI 2.0', '设计师', '快手推出的AI视频生成工具2.0版，2026年Q1视频质量达到商业级别，支持最长3分钟视频生成，中文原生支持。', 'Kuaishou Kling AI 2.0 with commercial-grade video quality, up to 3 minutes, native Chinese support.', '免费+付费', 4.8, 'https://klingai.kuaishou.com', ARRAY['商业级视频生成','最长3分钟视频','中文原生支持','图生视频功能'], true, true, true, 'kling-ai-2', 'AI视频生成', '可灵AI 2.0，国产视频生成达到商业级别', ARRAY['视频质量达商业级','中文支持最好','免费版可用'], ARRAY['高质量需付费','生成速度较慢'], '国内设计师视频生成首选，性价比极高', ARRAY['热门','TG精选','国产精品','2026新品'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Sora商业版', 'Sora', '设计师', 'OpenAI推出的Sora视频生成商业版，2026年Q1正式上线，支持最长1分钟高质量视频生成，视频生成进入新纪元。', 'OpenAI Sora commercial version launched Q1 2026, up to 1 minute high-quality video generation.', '$20/月', 4.7, 'https://sora.com', ARRAY['OpenAI顶级视频生成','最长1分钟视频','物理世界模拟','多风格视频生成'], true, true, true, 'sora', 'OpenAI视频', 'OpenAI Sora商业版，视频生成新纪元', ARRAY['物理模拟最真实','OpenAI品质保障','风格多样'], ARRAY['价格较高','时长限制1分钟'], '追求最高视频质量的设计师首选', ARRAY['热门','TG精选','2026新品'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('即梦AI', '即梦AI', '设计师', '字节跳动推出的AI创作平台，支持图像和视频生成，中文原生支持，免费版功能丰富，适合国内设计师。', 'ByteDance AI creation platform supporting image and video generation with native Chinese support.', '免费+付费', 4.6, 'https://jimeng.jianying.com', ARRAY['AI图像生成','AI视频生成','中文原生支持','最长2分钟视频'], true, true, true, 'jimeng-ai-2', 'AI图文视频', '字节即梦AI，图像视频一站式创作', ARRAY['图文视频一站式','中文支持最好','免费版功能丰富'], ARRAY['高级功能需付费','服务器偶尔拥挤'], '国内设计师图文视频创作首选', ARRAY['热门','国产精品','2026新品'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Ideogram 2.0', 'Ideogram 2.0', '设计师', 'Ideogram最新版本，文字渲染能力大幅提升，矢量图生成能力出色，适合需要精准文字排版的设计场景。', 'Ideogram 2.0 with greatly improved text rendering and vector graphics generation capabilities.', '免费+付费', 4.6, 'https://ideogram.ai', ARRAY['精准文字渲染','矢量图生成','多风格图像','商业授权支持'], true, true, true, 'ideogram-2', 'AI文字排版', 'Ideogram 2.0，文字渲染最强AI图像工具', ARRAY['文字渲染业界最强','矢量图能力出色','免费版可用'], ARRAY['风格不如Midjourney多样','视频功能暂无'], '需要精准文字的设计场景必选', ARRAY['热门','TG精选','2026新品'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Recraft V3', 'Recraft V3', '设计师', 'Recraft最新版本，矢量图和品牌视觉生成能力大幅提升，支持SVG导出，适合品牌设计师和UI设计师。', 'Recraft V3 with improved vector and brand visual generation, SVG export support.', '免费+付费', 4.6, 'https://www.recraft.ai', ARRAY['矢量图SVG生成','品牌视觉一致性','多风格图像生成','批量生成功能'], true, true, true, 'recraft-v3', 'AI矢量设计', 'Recraft V3，矢量图和品牌设计AI利器', ARRAY['SVG矢量导出','品牌一致性强','免费版功能丰富'], ARRAY['知名度不如Midjourney','视频功能暂无'], '品牌设计师和UI设计师强烈推荐', ARRAY['热门','TG精选','2026新品'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Runway Gen-3', 'Runway Gen-3', '设计师', 'Runway第三代AI视频生成模型，支持文生视频和图生视频，最长30秒，专业级视频效果，广受影视设计师青睐。', 'Runway Gen-3 AI video generation supporting text-to-video and image-to-video up to 30 seconds.', '$15/月', 4.5, 'https://runwayml.com', ARRAY['文生视频','图生视频','专业级视频效果','视频编辑功能'], true, true, false, 'runway-gen3', 'AI视频专业版', 'Runway Gen-3，影视级AI视频生成工具', ARRAY['视频质量专业级','编辑功能丰富','影视行业认可'], ARRAY['时长限制30秒','价格偏高'], '影视和广告设计师的专业视频工具', ARRAY['热门','TG精选'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Pika 2.0', 'Pika 2.0', '设计师', 'Pika Labs推出的2.0版AI视频生成工具，操作简单，支持视频风格转换和动效生成，适合社媒内容创作者。', 'Pika 2.0 AI video generation with simple operation, style transfer and motion effects for social media.', '$8/月', 4.4, 'https://pika.art', ARRAY['简单易用视频生成','视频风格转换','动效生成','社媒格式优化'], true, true, true, 'pika-2', 'AI视频创作', 'Pika 2.0，最易上手的AI视频生成工具', ARRAY['操作最简单易上手','价格实惠','社媒格式支持好'], ARRAY['视频质量不如可灵','时长限制30秒'], '社媒运营和内容创作者的入门视频工具', ARRAY['热门','2026新品'], 4300, 'active');
