-- 会计分类（1-25）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('用友畅捷通', 'YonYou CJT', '会计', '国内领先的中小企业财务云软件，AI辅助记账、报税和财务分析，覆盖全业务财务场景。', 'Leading Chinese SMB financial cloud software with AI bookkeeping and tax filing.', '¥199/年', 4.5, 'https://www.chanjet.com', ARRAY['AI智能记账','一键报税申报','财务报表自动生成','多账套管理'], true, true, false, 'chanjet', 'AI记账', '中小企业AI财务云管理软件', ARRAY['本土化程度最高','税务对接准确','价格亲民'], ARRAY['界面设计较老旧','移动端体验一般'], '国内中小企业财务管理首选', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('金蝶云星辰', 'Kingdee Star', '会计', '金蝶推出的中小企业财务云，AI自动识别票据、智能记账，支持与银行和税务系统直连。', 'Kingdee SMB financial cloud with AI invoice recognition and bank/tax system integration.', '¥299/年', 4.5, 'https://www.kingdee.com', ARRAY['AI票据自动识别','智能记账分录','银行流水自动对账','税务直连申报'], true, true, false, 'kingdee-star', 'AI财务', '金蝶AI智能财务云管理平台', ARRAY['票据识别准确率高','银税直连方便','金蝶品牌可靠'], ARRAY['高级功能需升级版本','客服响应较慢'], '中小企业财务数字化转型推荐', ARRAY['热门','今日推荐'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('QuickBooks AI', 'QuickBooks AI', '会计', 'Intuit旗下全球最受欢迎的小企业财务软件，内置AI功能自动分类交易、预测现金流和生成报告。', 'Intuit most popular small business accounting software with AI transaction categorization.', '$30/月', 4.6, 'https://quickbooks.intuit.com', ARRAY['AI交易自动分类','现金流预测','财务报告自动生成','税务准备辅助'], true, true, false, 'quickbooks-ai', 'AI财务', '全球最受欢迎的小企业财务软件', ARRAY['功能最成熟完善','集成生态丰富','AI分类准确'], ARRAY['主要面向美国市场','中文支持有限'], '海外业务财务管理的行业标准', ARRAY['热门','TG精选'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Xero AI', 'Xero AI', '会计', '新西兰云财务软件，AI自动对账、发票处理和财务预测，深受全球中小企业和会计师喜爱。', 'New Zealand cloud accounting with AI reconciliation, invoice processing and forecasting.', '$15/月', 4.6, 'https://www.xero.com', ARRAY['AI银行自动对账','发票智能处理','财务预测分析','多货币支持'], true, true, false, 'xero-ai', 'AI对账', '全球中小企业云财务AI平台', ARRAY['对账自动化程度高','界面简洁易用','多货币支持好'], ARRAY['主要面向英语市场','中文支持有限'], '跨境业务财务管理的优质选择', ARRAY['热门'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('税务师AI助手', 'TaxAI Assistant', '会计', '国内AI税务辅助工具，覆盖增值税、企业所得税、个税申报，智能识别税务风险和优惠政策。', 'Chinese AI tax assistant covering VAT, corporate and personal income tax filing.', '免费+付费', 4.4, 'https://www.taxai.cn', ARRAY['多税种智能申报','税务风险识别','税收优惠政策匹配','申报数据自动填充'], true, false, false, 'tax-ai-assistant', 'AI报税', '国内多税种AI智能申报助手', ARRAY['税种覆盖全面','风险识别准确','政策匹配实用'], ARRAY['部分功能需付费','地方税务差异处理有限'], '会计师日常报税效率提升工具', ARRAY['热门'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Sage AI', 'Sage AI', '会计', '英国老牌财务软件Sage推出的AI功能，自动处理发票、预测现金流，适合中型企业财务管理。', 'UK accounting software Sage with AI invoice processing and cash flow prediction.', '$25/月', 4.4, 'https://www.sage.com', ARRAY['AI发票自动处理','现金流智能预测','财务报告生成','多公司账套管理'], false, false, false, 'sage-ai', 'AI财务', 'Sage老牌财务软件AI升级版', ARRAY['品牌历史悠久可靠','功能覆盖全面','中型企业适配好'], ARRAY['界面较为复杂','价格偏高'], '中型企业财务管理的稳健选择', ARRAY['热门'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('发票宝', 'FaPiaoBao', '会计', '国内AI发票管理工具，支持发票OCR识别、真伪验证、自动归档和报销流程管理。', 'Chinese AI invoice management with OCR recognition, verification and expense management.', '免费+付费', 4.5, 'https://www.fapiaobao.com', ARRAY['发票OCR智能识别','发票真伪验证','自动归档分类','报销流程管理'], true, true, false, 'fapiao-bao', 'AI发票', '国内AI发票识别与管理工具', ARRAY['识别准确率高','真伪验证可靠','报销流程顺畅'], ARRAY['高级功能需付费','大批量处理较慢'], '企业财务发票管理必备工具', ARRAY['热门','今日推荐'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Botkeeper', 'Botkeeper', '会计', 'AI驱动的自动化记账平台，结合机器学习和人工审核，为会计师事务所提供高效记账服务。', 'AI-powered automated bookkeeping platform combining ML and human review for accounting firms.', '企业定价', 4.4, 'https://www.botkeeper.com', ARRAY['AI自动化记账','机器学习分类','人工审核结合','会计师事务所专用'], false, false, false, 'botkeeper', 'AI记账', 'AI+人工结合的自动化记账平台', ARRAY['自动化程度高','准确率有保障','适合会计师事务所'], ARRAY['价格较高','主要面向美国市场'], '会计师事务所提升服务效率推荐', ARRAY['热门'], 4300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Vic.ai', 'Vic.ai', '会计', 'AI应付账款自动化平台，自动处理供应商发票、匹配采购订单和审批工作流，减少人工操作。', 'AI accounts payable automation platform for invoice processing and PO matching.', '企业定价', 4.5, 'https://www.vic.ai', ARRAY['供应商发票自动处理','采购订单智能匹配','审批工作流自动化','异常发票检测'], true, false, false, 'vic-ai', 'AI应付', 'AI应付账款全流程自动化平台', ARRAY['AP自动化程度极高','异常检测准确','减少人工80%'], ARRAY['企业级定价较贵','实施周期较长'], '大中型企业AP部门效率提升首选', ARRAY['热门'], 4200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Docyt', 'Docyt', '会计', 'AI财务文件管理和记账平台，自动提取财务文件数据，实时同步到会计系统，减少手工录入。', 'AI financial document management and bookkeeping with automatic data extraction.', '$299/月', 4.3, 'https://docyt.com', ARRAY['财务文件AI数据提取','实时会计系统同步','收支自动分类','财务报告实时生成'], false, false, false, 'docyt', 'AI文件', 'AI财务文件自动提取记账平台', ARRAY['数据提取准确率高','实时同步方便','减少手工录入'], ARRAY['价格偏高','主要面向美国市场'], '餐饮和零售行业财务管理推荐', ARRAY['热门'], 4100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Dext', 'Dext', '会计', '票据和收据AI处理工具，拍照上传自动提取数据，与主流会计软件无缝集成，简化报销流程。', 'AI receipt and invoice processing tool with photo capture and accounting software integration.', '$20/月', 4.4, 'https://dext.com', ARRAY['收据拍照AI识别','数据自动提取','会计软件集成','报销流程简化'], true, false, false, 'dext', 'AI收据', '拍照上传自动提取票据数据工具', ARRAY['识别准确率高','集成生态丰富','移动端体验好'], ARRAY['主要面向英语市场','中文票据支持有限'], '会计师和财务人员票据处理推荐', ARRAY['热门'], 4000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Gridlex', 'Gridlex', '会计', '一体化企业管理平台，集成AI财务、CRM和项目管理，适合需要多系统整合的中小企业。', 'All-in-one business platform integrating AI finance, CRM and project management.', '$10/月', 4.2, 'https://gridlex.com', ARRAY['AI财务记账','CRM客户管理','项目管理集成','多模块一体化'], false, false, false, 'gridlex', '一体化', 'AI财务CRM项目管理一体平台', ARRAY['多模块集成方便','价格亲民','功能覆盖广'], ARRAY['各模块深度有限','界面较为复杂'], '需要多系统整合的中小企业推荐', ARRAY['免费'], 3900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Trullion', 'Trullion', '会计', 'AI会计合规平台，自动处理租赁会计、收入确认和审计准备，帮助企业满足IFRS/GAAP要求。', 'AI accounting compliance platform for lease accounting, revenue recognition and audit prep.', '企业定价', 4.4, 'https://trullion.com', ARRAY['租赁会计自动化','收入确认处理','审计准备辅助','IFRS/GAAP合规'], false, false, false, 'trullion', '会计合规', 'AI会计准则合规自动化平台', ARRAY['合规处理专业准确','审计准备效率高','准则更新及时'], ARRAY['价格较高','主要面向大型企业'], '上市公司和大型企业合规首选', ARRAY['热门'], 3800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Zeni', 'Zeni', '会计', 'AI驱动的初创公司财务管理平台，提供实时财务仪表盘、自动记账和CFO级财务洞察。', 'AI-driven startup finance platform with real-time dashboard and CFO-level insights.', '$299/月', 4.5, 'https://www.zeni.ai', ARRAY['实时财务仪表盘','AI自动记账','CFO级财务洞察','融资数据准备'], true, false, true, 'zeni', 'AI CFO', '初创公司AI财务管理与洞察平台', ARRAY['财务洞察深度好','实时数据准确','初创公司针对性强'], ARRAY['价格偏高','主要面向美国市场'], '融资阶段初创公司财务管理推荐', ARRAY['今日推荐'], 3700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Puzzle.io', 'Puzzle.io', '会计', '专为初创公司设计的AI财务软件，自动同步银行和支付数据，实时生成财务报表和指标。', 'AI finance software for startups with automatic bank sync and real-time financial metrics.', '免费+付费', 4.3, 'https://puzzle.io', ARRAY['银行数据自动同步','实时财务报表','关键指标追踪','投资人报告生成'], false, false, false, 'puzzle-io', 'AI财务', '初创公司实时财务数据AI平台', ARRAY['免费版功能够用','实时数据准确','投资人报告方便'], ARRAY['功能相对基础','主要面向美国市场'], '早期初创公司财务管理入门工具', ARRAY['免费'], 3600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Planful', 'Planful', '会计', '企业财务规划和分析AI平台，支持预算编制、滚动预测和财务报告，加速财务关账流程。', 'Enterprise financial planning and analysis AI platform for budgeting and forecasting.', '企业定价', 4.5, 'https://planful.com', ARRAY['预算编制自动化','滚动预测分析','财务关账加速','多维度财务报告'], true, false, false, 'planful', 'FP&A', '企业财务规划分析AI平台', ARRAY['FP&A功能专业全面','关账效率提升显著','报告灵活多样'], ARRAY['价格较高','实施周期较长'], '中大型企业财务规划分析首选', ARRAY['热门'], 3500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Anaplan', 'Anaplan', '会计', '企业级财务规划云平台，AI驱动的预测分析和情景模拟，广泛用于大型企业财务和运营规划。', 'Enterprise financial planning cloud with AI-driven forecasting and scenario modeling.', '企业定价', 4.6, 'https://www.anaplan.com', ARRAY['AI驱动预测分析','情景模拟建模','跨部门协同规划','实时数据整合'], true, true, false, 'anaplan', '企业规划', '大型企业AI财务运营规划平台', ARRAY['规划能力业界领先','情景模拟强大','跨部门协同好'], ARRAY['价格极高','实施复杂度高'], '大型企业财务规划的行业标杆', ARRAY['热门','TG精选'], 3400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Workiva', 'Workiva', '会计', '上市公司财务报告和合规AI平台，支持ESG报告、SEC申报和内控管理，数据可追溯。', 'Public company financial reporting and compliance AI platform for ESG and SEC filings.', '企业定价', 4.5, 'https://www.workiva.com', ARRAY['SEC申报文件准备','ESG报告自动化','内控管理','数据可追溯审计'], false, false, false, 'workiva', '财务报告', '上市公司财务合规报告AI平台', ARRAY['合规报告专业权威','数据追溯清晰','ESG报告能力强'], ARRAY['价格极高','主要面向上市公司'], '上市公司财务合规报告必备工具', ARRAY['热门'], 3300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Tipalti', 'Tipalti', '会计', 'AI全球应付账款自动化平台，支持全球供应商付款、税务合规和对账，适合跨境业务企业。', 'AI global accounts payable automation for supplier payments and tax compliance.', '企业定价', 4.5, 'https://tipalti.com', ARRAY['全球供应商付款','税务合规自动化','付款对账处理','欺诈风险检测'], true, false, false, 'tipalti', '全球付款', 'AI全球应付账款自动化平台', ARRAY['全球付款覆盖广','税务合规处理好','欺诈检测可靠'], ARRAY['价格较高','实施周期较长'], '跨境业务企业AP自动化首选', ARRAY['热门'], 3200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Expensify', 'Expensify', '会计', '智能费用报销管理工具，拍照自动识别收据，一键提交报销，支持企业信用卡对账。', 'Smart expense management with photo receipt scanning and one-click reimbursement.', '$5/月', 4.4, 'https://www.expensify.com', ARRAY['收据拍照自动识别','一键报销提交','企业信用卡对账','报销审批工作流'], true, true, false, 'expensify', 'AI报销', '拍照识别收据一键报销工具', ARRAY['报销流程极简便','识别准确率高','移动端体验好'], ARRAY['免费版功能有限','部分功能需企业版'], '员工差旅报销管理的高效工具', ARRAY['热门','今日推荐'], 3100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Ramp', 'Ramp', '会计', '企业支出管理AI平台，智能企业信用卡配合AI费用分析，自动识别节省机会和异常支出。', 'Corporate spend management AI platform with smart cards and automatic savings detection.', '免费', 4.6, 'https://ramp.com', ARRAY['智能企业信用卡','AI费用自动分类','节省机会识别','异常支出检测'], true, true, false, 'ramp', 'AI支出', '企业支出管理AI平台免费使用', ARRAY['完全免费使用','AI节省识别实用','费用分析深度好'], ARRAY['主要面向美国企业','需要美国银行账户'], '美国企业控制支出的最佳免费工具', ARRAY['免费','热门','TG精选'], 3000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Brex', 'Brex', '会计', '初创公司和科技企业专用AI财务平台，集成企业信用卡、费用管理和财务软件，自动化程度高。', 'AI finance platform for startups with corporate cards, expense management and automation.', '免费+付费', 4.5, 'https://www.brex.com', ARRAY['初创公司企业信用卡','费用自动分类','财务软件集成','实时支出分析'], false, true, false, 'brex', 'AI财务', '初创公司专用AI财务管理平台', ARRAY['初创公司针对性强','自动化程度高','集成生态好'], ARRAY['主要面向美国市场','需要满足资质要求'], '硅谷初创公司财务管理标配工具', ARRAY['热门'], 2900, 'active');
