-- 律师分类（26-50）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('合规云', 'ComplianceCloud', '律师', '企业合规管理AI平台，覆盖法规变更追踪、合规风险评估、内控体系建设和合规培训。', 'Enterprise compliance AI with regulation tracking and risk assessment.', '¥399/月', 4.4, 'https://www.compliancecloud.cn', ARRAY['法规变更实时追踪','合规风险自动评估','内控体系建设','合规培训管理'], false, false, false, 'compliance-cloud', '合规管理', '企业合规风险管理AI平台', ARRAY['法规追踪及时准确','风险评估维度全面','报告生成自动化'], ARRAY['价格偏高','实施周期较长'], '企业合规部门日常管理首选', ARRAY['热门'], 2500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('iLaw爱法律', 'iLaw', '律师', '面向律师的AI智能法律助手，提供法律文书自动生成、案例检索和法规问答服务。', 'AI legal assistant for lawyers with document generation and case search.', '免费+付费', 4.5, 'https://www.ilaw.com.cn', ARRAY['法律文书自动生成','智能案例检索','法规问答机器人','律师工作流管理'], true, false, false, 'ilaw', '法律助手', '律师全流程AI智能助手', ARRAY['文书模板丰富全面','问答响应准确','界面简洁易用'], ARRAY['部分功能需订阅','移动端体验一般'], '文书生成效率提升利器', ARRAY['免费','热门'], 2400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Spellbook', 'Spellbook', '律师', '基于GPT-4的合同起草AI助手，直接集成在Word中，实时提供合同条款建议和风险提示。', 'GPT-4 contract drafting AI integrated in Word with real-time clause suggestions.', '$99/月', 4.6, 'https://www.spellbook.legal', ARRAY['Word插件无缝集成','合同条款AI建议','风险条款实时提示','合同语言优化'], true, true, true, 'spellbook', 'Word合同AI', 'Word内嵌的AI合同起草助手', ARRAY['Word集成体验流畅','建议质量高','学习成本低'], ARRAY['仅支持英文合同','需要订阅费用'], '英文合同起草效率翻倍', ARRAY['热门','今日推荐'], 2300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法律AI助手', 'LawAIAssistant', '律师', '基于DeepSeek大模型的中国法律AI，专注中国法律场景的智能问答和文书辅助。', 'Chinese legal AI based on DeepSeek LLM for Q&A and document assistance.', '免费', 4.4, 'https://chat.deepseek.com', ARRAY['中国法律智能问答','法律文书辅助起草','法规条文解读','案例类比分析'], false, false, true, 'law-ai-assistant', '法律问答', '基于DeepSeek的中国法律AI', ARRAY['完全免费使用','中文理解能力强','响应速度快'], ARRAY['专业深度有待提升','数据有时限'], '免费体验AI法律助手的好选择', ARRAY['免费','今日推荐'], 2200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Briefpoint', 'Briefpoint', '律师', '专为诉讼律师设计的AI工具，自动将对方诉状转化为反驳文书草稿，大幅节省起草时间。', 'AI for litigators that auto-converts opposing briefs into response drafts.', '$99/月', 4.5, 'https://briefpoint.ai', ARRAY['诉状自动转换反驳稿','法律论点提炼','引用案例自动插入','文书格式规范化'], true, false, true, 'briefpoint', '诉状起草', 'AI自动生成诉讼反驳文书', ARRAY['起草效率提升80%','论点提炼准确','格式规范专业'], ARRAY['仅支持英文','需要人工审核'], '诉讼律师起草文书的效率神器', ARRAY['今日推荐'], 2100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('EvenUp AI', 'EvenUp AI', '律师', '专注人身伤害案件的AI法律工具，自动生成索赔需求函，帮助原告律师提高和解金额。', 'AI legal tool for personal injury cases that auto-generates demand letters.', '按案件收费', 4.6, 'https://www.evenuplaw.com', ARRAY['索赔需求函自动生成','医疗记录智能分析','损害赔偿计算','和解策略建议'], true, false, false, 'evenup-ai', '伤害索赔', '人身伤害案件AI索赔工具', ARRAY['需求函质量专业','医疗记录分析准确','提高和解成功率'], ARRAY['仅适用人身伤害案','按案件收费较贵'], '人身伤害律师提高案件价值必备', ARRAY['TG精选'], 2000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Lexion', 'Lexion', '律师', 'AI合同管理平台，自动提取合同关键数据，建立合同数据库，支持到期提醒和义务追踪。', 'AI contract management with automatic data extraction and obligation tracking.', '企业定价', 4.4, 'https://lexion.ai', ARRAY['合同数据自动提取','合同数据库建立','到期日提醒','义务履行追踪'], false, false, false, 'lexion', '合同数据库', 'AI合同数据提取与管理平台', ARRAY['数据提取准确率高','数据库管理清晰','提醒功能实用'], ARRAY['价格较高','初始导入耗时'], '企业法务合同台账管理推荐', ARRAY['热门'], 1900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Juro', 'Juro', '律师', '一体化合同自动化平台，从模板创建到签署存档全流程在线完成，内置AI合同分析功能。', 'All-in-one contract automation from template to signature with AI analysis.', '$199/月起', 4.5, 'https://juro.com', ARRAY['合同模板在线创建','协作编辑与审批','电子签名集成','AI合同数据分析'], false, false, false, 'juro', '合同自动化', '合同全流程在线自动化平台', ARRAY['全流程在线操作','协作体验流畅','模板库丰富'], ARRAY['价格偏高','中文支持有限'], '法务团队合同流程数字化首选', ARRAY['热门'], 1800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法律机器人', 'LawRobot', '律师', '国内AI法律文书生成工具，支持起诉状、答辩状、合同等100+法律文书模板一键生成。', 'Chinese AI legal document generator with 100+ templates for lawsuits and contracts.', '免费+付费', 4.3, 'https://www.lawrobot.cn', ARRAY['100+法律文书模板','一键智能生成','文书格式规范','支持自定义修改'], false, false, false, 'law-robot', '文书生成', '100+法律文书一键生成工具', ARRAY['模板数量多','生成速度快','格式规范标准'], ARRAY['生成内容需人工校对','复杂案件适用性差'], '简单法律文书快速生成推荐', ARRAY['免费'], 1700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Paxton AI', 'Paxton AI', '律师', '专为律师设计的AI法律研究助手，支持自然语言提问，快速检索相关法规和判例并生成摘要。', 'AI legal research assistant with natural language search and auto-generated summaries.', '$65/月', 4.5, 'https://www.paxton.ai', ARRAY['自然语言法律检索','判例摘要自动生成','法规关联分析','研究报告导出'], true, false, true, 'paxton-ai', '法律研究', '自然语言驱动的AI法律研究', ARRAY['自然语言交互流畅','摘要质量高','检索速度快'], ARRAY['主要覆盖美国法律','中文支持有限'], '英文法律研究的高效替代工具', ARRAY['今日推荐'], 1600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Genie AI', 'Genie AI', '律师', '英国AI法律文件平台，提供律师事务所级别的合同模板库，支持AI辅助起草和审查。', 'UK AI legal document platform with law firm-grade templates and AI drafting.', '免费+付费', 4.4, 'https://www.genieai.co', ARRAY['律所级合同模板库','AI辅助合同起草','条款建议与优化','协作审查功能'], false, false, false, 'genie-ai', '合同模板', '律所级AI合同模板与起草平台', ARRAY['模板质量专业','AI建议实用','免费版可用'], ARRAY['主要面向英国法律','高级功能需付费'], '英国法律合同起草的高效工具', ARRAY['免费'], 1500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Evisort', 'Evisort', '律师', 'AI合同智能管理平台，自动提取合同数据、追踪关键日期，并提供合同组合风险分析。', 'AI contract intelligence with automatic data extraction and portfolio risk analysis.', '企业定价', 4.5, 'https://www.evisort.com', ARRAY['合同数据自动提取','关键日期追踪','合同组合分析','风险仪表盘'], false, false, false, 'evisort', '合同智能', 'AI合同数据提取与风险分析', ARRAY['数据提取精度高','风险仪表盘直观','大规模合同处理强'], ARRAY['实施成本较高','需要专业培训'], '大型企业合同组合管理推荐', ARRAY['热门'], 1400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Clio', 'Clio', '律师', '全球最受欢迎的律所管理软件，集成AI功能，覆盖案件管理、账单、客户沟通全流程。', 'World most popular law firm management software with AI case and billing tools.', '$49/月', 4.6, 'https://www.clio.com', ARRAY['案件全流程管理','智能账单生成','客户沟通管理','法律文件存储'], true, true, false, 'clio', '律所管理', '全球最受欢迎的律所管理软件', ARRAY['功能最全面成熟','集成生态丰富','用户口碑极佳'], ARRAY['价格随功能递增','中文支持有限'], '律所管理软件的行业标杆', ARRAY['热门','TG精选'], 1300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Smokeball', 'Smokeball', '律师', '专为中小律所设计的法律实践管理软件，内置AI功能，自动记录工时、管理案件和文件。', 'Legal practice management for small firms with AI time tracking and case management.', '$99/月', 4.4, 'https://www.smokeball.com', ARRAY['AI自动工时记录','案件文件管理','账单自动生成','客户门户'], false, false, false, 'smokeball', '律所管理', '中小律所AI实践管理软件', ARRAY['工时记录自动准确','账单生成便捷','客户门户专业'], ARRAY['主要面向澳美市场','中文支持有限'], '中小律所提升运营效率的利器', ARRAY['热门'], 1200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Lawyaw', 'Lawyaw', '律师', '律师事务所文件自动化平台，通过智能模板批量生成法律文件，减少重复性文书工作。', 'Law firm document automation for batch legal document generation via smart templates.', '$70/月', 4.3, 'https://www.lawyaw.com', ARRAY['智能文件模板','批量文件生成','客户信息自动填充','文件版本管理'], false, false, false, 'lawyaw', '文件自动化', '律所文件批量自动化生成平台', ARRAY['批量生成效率高','模板自定义灵活','减少重复工作'], ARRAY['模板初始设置耗时','主要面向美国律所'], '重复性法律文件生成的效率工具', ARRAY['热门'], 1100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Definely', 'Definely', '律师', '法律文件阅读辅助AI工具，在Word中高亮显示定义条款，帮助律师快速理解复杂合同结构。', 'Legal document reading AI that highlights defined terms in Word for faster comprehension.', '$49/月', 4.3, 'https://www.definely.com', ARRAY['定义条款自动高亮','合同结构可视化','交叉引用追踪','Word插件集成'], false, false, false, 'definely', '合同阅读', 'Word内嵌合同阅读辅助工具', ARRAY['阅读效率大幅提升','定义追踪准确','Word集成无缝'], ARRAY['功能相对单一','仅支持英文'], '阅读复杂合同的效率提升工具', ARRAY['热门'], 1000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Themis AI', 'Themis AI', '律师', '专注劳动法领域的AI合规工具，帮助企业HR和法务快速检查劳动合同合规性和用工风险。', 'AI compliance tool for labor law helping HR check employment contract risks.', '¥199/月', 4.3, 'https://www.themisai.cn', ARRAY['劳动合同合规检查','用工风险评估','劳动法规查询','违规条款提示'], false, false, false, 'themis-ai', '劳动合规', '劳动法合规AI检查工具', ARRAY['劳动法专业深度强','风险提示准确','操作简单易用'], ARRAY['仅覆盖劳动法领域','部分地方法规有限'], '企业HR和法务劳动合规必备', ARRAY['热门'], 900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Legalfly', 'Legalfly', '律师', '欧洲AI法律研究平台，支持多国法律体系检索，提供法规摘要、案例分析和合规建议。', 'European AI legal research platform supporting multi-jurisdiction search and compliance.', '€79/月', 4.4, 'https://www.legalfly.com', ARRAY['多国法律体系检索','法规摘要生成','案例分析报告','合规建议输出'], false, false, true, 'legalfly', '欧洲法律', '欧洲多国法律AI研究平台', ARRAY['多国法律覆盖广','摘要生成质量高','合规建议实用'], ARRAY['亚洲法律支持弱','价格偏高'], '欧洲业务法律合规研究推荐', ARRAY['今日推荐'], 800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Legalese Decoder', 'Legalese Decoder', '律师', 'AI法律语言简化工具，将复杂法律条文转化为普通人易懂的语言，辅助律师向客户解释合同。', 'AI tool that simplifies complex legal language into plain language for clients.', '免费+付费', 4.2, 'https://legalesedecoder.com', ARRAY['法律条文简化解释','合同要点提炼','客户沟通辅助','多语言翻译'], false, false, false, 'legalese-decoder', '法律简化', '复杂法律条文AI简化解释工具', ARRAY['简化效果直观易懂','客户沟通效率提升','免费版可用'], ARRAY['专业深度有限','不能替代法律建议'], '向客户解释合同条款的辅助工具', ARRAY['免费'], 700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Amto AI', 'Amto AI', '律师', '专为律师设计的AI会议记录和案件笔记工具，自动转录庭审录音，生成结构化案件摘要。', 'AI meeting notes tool for lawyers with court recording transcription and case summaries.', '$49/月', 4.4, 'https://www.amto.ai', ARRAY['庭审录音自动转录','案件笔记结构化','会议摘要生成','关键信息提取'], false, false, true, 'amto-ai', '庭审记录', 'AI自动转录庭审录音生成摘要', ARRAY['转录准确率高','摘要结构清晰','节省大量记录时间'], ARRAY['需要清晰录音质量','中文支持有限'], '庭审记录和案件整理的效率工具', ARRAY['今日推荐'], 600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Robin AI', 'Robin AI', '律师', '英国AI合同审查平台，结合AI技术和律师专业知识，提供快速准确的合同风险分析服务。', 'UK AI contract review combining AI with lawyer expertise for risk analysis.', '企业定价', 4.5, 'https://www.robinai.co.uk', ARRAY['AI+律师混合审查','合同风险分析','标准化审查流程','审查报告生成'], false, false, false, 'robin-ai', '混合审查', 'AI与律师协作的合同审查平台', ARRAY['AI与人工结合准确','审查流程标准化','报告专业详细'], ARRAY['价格较高','响应周期较长'], '重要合同审查的可靠选择', ARRAY['热门'], 500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Legartis', 'Legartis', '律师', '瑞士AI合同审查平台，专注企业合同风险识别，支持德语、英语、法语等多语言合同分析。', 'Swiss AI contract review specializing in risk identification for enterprises.', '企业定价', 4.4, 'https://www.legartis.ai', ARRAY['多语言合同审查','风险条款自动识别','合规性检查','审查报告生成'], false, false, false, 'legartis', '多语言合同', '多语言企业合同AI审查平台', ARRAY['多语言支持出色','风险识别准确','欧洲合规专业'], ARRAY['价格较高','亚洲法律支持弱'], '欧洲跨境业务合同审查推荐', ARRAY['热门'], 400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Loio', 'Loio', '律师', 'Word插件形式的AI合同分析工具，实时检测合同问题、不一致之处和潜在风险条款。', 'Word plugin AI contract analyzer detecting issues, inconsistencies and risk clauses.', '$39/月', 4.2, 'https://loio.com', ARRAY['合同问题实时检测','不一致条款识别','风险条款标注','合同质量评分'], false, false, false, 'loio', '合同检测', 'Word插件AI合同质量检测', ARRAY['实时检测响应快','问题识别全面','价格亲民'], ARRAY['深度分析能力有限','仅支持英文'], '合同起草质量把关的实用工具', ARRAY['免费'], 300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Latch', 'Latch', '律师', '专为法律团队设计的AI合同谈判工具，实时标注合同风险，提供谈判策略和替代条款建议。', 'AI contract negotiation tool with real-time risk annotation and strategy suggestions.', '$79/月', 4.4, 'https://www.latch.legal', ARRAY['合同风险实时标注','谈判策略建议','替代条款推荐','谈判历史追踪'], false, false, false, 'latch', '合同谈判', 'AI辅助合同谈判策略工具', ARRAY['风险标注直观清晰','替代条款建议实用','谈判效率提升'], ARRAY['仅支持英文合同','功能相对单一'], '合同谈判阶段的高效辅助工具', ARRAY['热门'], 200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Clause', 'Clause', '律师', '智能合同执行平台，将合同条款与业务系统连接，实现合同义务的自动化执行和监控。', 'Smart contract execution platform connecting contract terms with business systems.', '企业定价', 4.3, 'https://clause.io', ARRAY['合同条款自动执行','业务系统集成','义务履行监控','合同数据分析'], false, false, false, 'clause-io', '智能执行', '合同条款自动化执行平台', ARRAY['自动化程度高','系统集成能力强','减少人工跟进'], ARRAY['技术实施复杂','需要IT配合'], '合同执行自动化的前沿工具', ARRAY['热门'], 100, 'active');
