-- 2026年Q1行业报告新增工具（会计财税+营销运营部分）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('金蝶云苍穹AI', 'Kingdee AI', '会计', '金蝶推出的AI财务机器人，覆盖凭证录入、记账、报表、报税全流程自动化，符合中国财税合规要求。', 'Kingdee AI finance robot covering full-process automation from bookkeeping to tax filing.', '按模块定价', 4.8, 'https://www.kingdee.com', ARRAY['凭证自动录入','智能记账','财务报表生成','一键报税'], true, true, true, 'kingdee-ai', 'AI财务机器人', '金蝶云苍穹AI，中国财税全流程自动化', ARRAY['中国合规有保障','全流程自动化','月活用户多'], ARRAY['按模块定价较复杂','需要培训'], '中大型企业财务自动化首选', ARRAY['热门','TG精选','国产精品'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('用友YonSuite AI', 'YonSuite AI', '会计', '用友网络推出的AI财务管理平台，支持智能财务分析、预算管理和资金预测，适合中大型企业。', 'Yonyou AI finance platform with intelligent analysis, budget management and cash flow forecasting.', '按模块定价', 4.7, 'https://www.yonyou.com', ARRAY['智能财务分析','预算管理自动化','资金预测','多维报表'], true, true, false, 'yonyou-ai', 'AI财务管理', '用友YonSuite AI，企业财务智能化平台', ARRAY['国内市场份额大','功能覆盖全面','本地化服务好'], ARRAY['实施周期较长','价格偏高'], '国内大中型企业财务管理首选', ARRAY['热门','国产精品'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('百望云AI', '百望云AI', '会计', '百望云推出的AI税务管理平台，覆盖中国全税种申报，支持发票智能识别和税务风险预警。', 'Baiwang Cloud AI tax management covering all China tax types with invoice recognition and risk alerts.', '¥3,600/年起', 4.7, 'https://www.baiwang.com', ARRAY['全税种智能申报','发票AI识别','税务风险预警','电子发票管理'], true, true, true, 'baiwang-ai', 'AI税务申报', '百望云AI，中国全税种智能申报平台', ARRAY['全税种覆盖','发票识别准确','风险预警及时'], ARRAY['主要面向中国市场','价格偏高'], '中国企业税务合规管理首选', ARRAY['热门','国产精品','2026新品'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Intuit TurboTax AI', 'TurboTax AI', '会计', 'Intuit旗下TurboTax推出的AI报税助手，2026年实现全流程自动化，适合美国个人和小企业报税。', 'Intuit TurboTax AI assistant with full-process automation for US personal and small business tax filing.', '$89/年起', 4.7, 'https://turbotax.intuit.com', ARRAY['AI全流程报税','税务优化建议','自动导入财务数据','退税最大化'], true, true, false, 'turbotax-ai', 'AI报税助手', 'TurboTax AI，美国报税全流程自动化', ARRAY['操作简单易上手','退税优化能力强','数据导入方便'], ARRAY['仅适用美国税法','中文支持有限'], '在美华人和美国用户报税首选', ARRAY['热门'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('SAP Joule', 'SAP Joule', '会计', 'SAP推出的AI助手Joule，深度集成SAP财务系统，支持自然语言查询财务数据、自动生成报告和异常检测。', 'SAP AI assistant Joule integrated with SAP finance for natural language queries and automated reporting.', '企业定价', 4.6, 'https://www.sap.com/joule', ARRAY['自然语言财务查询','自动报告生成','异常交易检测','多系统数据整合'], true, false, false, 'sap-joule', 'SAP AI助手', 'SAP Joule，企业级财务AI智能助手', ARRAY['SAP生态深度整合','自然语言交互','全球合规支持'], ARRAY['需要SAP系统','价格昂贵'], '已使用SAP的大型企业财务团队', ARRAY['热门'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Jasper AI', 'Jasper AI', '营销', 'AI营销内容创作平台，支持博客、广告文案、社媒内容批量生成，内置品牌声音训练功能，营销团队必备。', 'AI marketing content platform for blogs, ad copy and social media with brand voice training.', '$39/月起', 4.8, 'https://www.jasper.ai', ARRAY['营销文案批量生成','品牌声音训练','多平台内容适配','SEO优化建议'], true, true, false, 'jasper-ai', 'AI营销文案', 'Jasper AI，营销团队内容生产效率提升20倍', ARRAY['营销场景模板丰富','品牌一致性强','多语言支持'], ARRAY['价格偏高','需要学习成本'], '品牌营销团队内容生产首选工具', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Copy.ai', 'Copy.ai', '营销', 'AI文案生成工具，支持广告文案、邮件营销、产品描述等多种营销内容，操作简单，适合中小团队。', 'AI copywriting tool for ads, email marketing and product descriptions, simple for small teams.', '$36/月起', 4.6, 'https://www.copy.ai', ARRAY['广告文案生成','邮件营销内容','产品描述批量生成','多语言文案'], true, true, false, 'copy-ai', 'AI文案生成', 'Copy.ai，最易上手的AI营销文案工具', ARRAY['操作简单易上手','模板种类丰富','价格实惠'], ARRAY['深度定制能力有限','品牌一致性不如Jasper'], '中小团队和独立营销人的文案利器', ARRAY['热门'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('字节火山写作', '火山写作', '营销', '字节跳动推出的AI写作助手，深度优化中文营销内容，支持小红书、抖音、微信等国内主流平台内容生成。', 'ByteDance AI writing assistant optimized for Chinese marketing content across major Chinese platforms.', '免费+付费', 4.7, 'https://www.writingo.net', ARRAY['中文营销内容生成','多平台格式适配','爆款标题生成','内容改写优化'], true, true, true, 'huoshan-writing', 'AI中文写作', '火山写作，国内营销内容生产效率神器', ARRAY['中文内容质量高','平台适配好','免费版可用'], ARRAY['英文能力有限','部分功能需付费'], '国内营销运营人员内容生产首选', ARRAY['热门','国产精品','2026新品'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('字节巨量引擎AI', '巨量引擎AI', '营销', '字节跳动广告投放平台巨量引擎的AI优化系统，自动优化抖音、今日头条广告投放，ROI提升40%。', 'ByteDance advertising platform AI optimization for Douyin and Toutiao ads with 40% ROI improvement.', '按消耗计费', 4.9, 'https://e.cn.miaozhen.com', ARRAY['广告智能投放优化','受众精准定向','创意自动生成','ROI实时优化'], true, true, false, 'juliang-ai', 'AI广告投放', '巨量引擎AI，抖音广告ROI提升40%', ARRAY['抖音生态深度整合','ROI优化效果显著','数据分析维度丰富'], ARRAY['仅限字节系平台','需要一定预算'], '抖音和头条广告投放必用工具', ARRAY['热门','TG精选'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('HubSpot AI', 'HubSpot AI', '营销', 'HubSpot推出的AI营销代理人，2026年Q1实现从策略制定到内容发布的全链路营销自动化，CRM深度整合。', 'HubSpot AI marketing agent with full-funnel automation from strategy to publishing with CRM integration.', 'HubSpot订阅', 4.7, 'https://www.hubspot.com', ARRAY['全链路营销自动化','AI内容生成','CRM深度整合','营销效果分析'], true, true, true, 'hubspot-ai', 'AI营销自动化', 'HubSpot AI，全链路营销自动化平台', ARRAY['CRM整合最完善','全链路自动化','数据分析强'], ARRAY['价格较高','需要HubSpot订阅'], '中大型企业营销团队自动化首选', ARRAY['热门','TG精选','2026新品'], 4600, 'active');
