-- 营销分类（1-25）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('HubSpot AI', 'HubSpot AI', '营销', 'HubSpot内置AI功能，覆盖内容生成、邮件优化、SEO建议和销售预测，营销全流程AI赋能。', 'HubSpot built-in AI for content generation, email optimization, SEO and sales forecasting.', '免费+付费', 4.7, 'https://www.hubspot.com', ARRAY['AI内容自动生成','邮件主题优化','SEO关键词建议','销售预测分析'], true, true, false, 'hubspot-ai', 'AI营销', 'HubSpot全流程AI营销赋能平台', ARRAY['功能最全面成熟','CRM集成无缝','免费版功能丰富'], ARRAY['高级功能价格较高','学习曲线较陡'], '营销团队一站式AI工具首选', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Jasper AI', 'Jasper AI', '营销', '专为营销团队设计的AI内容创作平台，支持博客、广告文案、社媒内容批量生成，品牌声音一致。', 'AI content creation platform for marketing teams with blog, ad copy and social media generation.', '$39/月', 4.6, 'https://www.jasper.ai', ARRAY['营销文案AI生成','品牌声音训练','多格式内容创作','团队协作功能'], true, true, false, 'jasper-ai', 'AI文案', '营销团队专用AI内容创作平台', ARRAY['营销场景针对性强','品牌声音一致性好','内容质量较高'], ARRAY['价格偏高','需要人工审核'], '内容营销团队提升产出效率首选', ARRAY['热门','今日推荐'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Copy.ai', 'Copy.ai', '营销', 'AI营销文案生成工具，覆盖广告、邮件、落地页、社媒等100+营销场景，支持中文内容创作。', 'AI marketing copy tool covering 100+ scenarios including ads, emails and landing pages.', '免费+付费', 4.5, 'https://www.copy.ai', ARRAY['100+营销文案模板','广告文案生成','邮件营销内容','落地页文案优化'], true, true, false, 'copy-ai', 'AI文案', '100+场景AI营销文案生成工具', ARRAY['场景覆盖最全面','中文支持较好','免费版可用'], ARRAY['生成内容需要润色','高级功能需付费'], '营销人员快速生成各类文案推荐', ARRAY['热门','TG精选'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Semrush AI', 'Semrush AI', '营销', '全球领先的SEO和数字营销平台，AI辅助关键词研究、竞品分析、内容优化和排名追踪。', 'Leading SEO and digital marketing platform with AI keyword research and competitor analysis.', '$120/月', 4.7, 'https://www.semrush.com', ARRAY['AI关键词研究','竞品流量分析','内容SEO优化','排名实时追踪'], true, true, false, 'semrush-ai', 'SEO分析', '全球领先SEO数字营销AI平台', ARRAY['数据最全面权威','竞品分析深度好','SEO功能最强'], ARRAY['价格较高','数据量大学习成本高'], 'SEO和数字营销从业者必备工具', ARRAY['热门','TG精选'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Ahrefs AI', 'Ahrefs AI', '营销', 'SEO工具领域标杆，AI辅助外链分析、关键词挖掘、内容差距分析，数据准确性业界最高。', 'SEO benchmark tool with AI backlink analysis, keyword research and content gap analysis.', '$99/月', 4.8, 'https://ahrefs.com', ARRAY['外链数据库分析','关键词难度评估','内容差距分析','网站健康检查'], true, true, false, 'ahrefs-ai', 'SEO外链', 'SEO外链分析数据最准确的工具', ARRAY['外链数据最准确','关键词数据丰富','内容分析深度好'], ARRAY['价格较高','功能复杂需学习'], 'SEO专业人员外链和关键词分析首选', ARRAY['热门','TG精选'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mailchimp AI', 'Mailchimp AI', '营销', '全球最受欢迎的邮件营销平台，AI优化发送时间、个性化内容和受众细分，提升邮件转化率。', 'Most popular email marketing platform with AI send time optimization and personalization.', '免费+付费', 4.5, 'https://mailchimp.com', ARRAY['AI发送时间优化','个性化内容推荐','受众智能细分','邮件效果分析'], true, true, false, 'mailchimp-ai', 'AI邮件', '全球最受欢迎AI邮件营销平台', ARRAY['用户基础最大','AI优化效果好','免费版功能够用'], ARRAY['高级功能价格较高','模板设计较老旧'], '邮件营销入门和进阶的首选工具', ARRAY['热门','今日推荐'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Surfer SEO', 'Surfer SEO', '营销', 'AI内容SEO优化工具，实时分析竞争对手内容，给出关键词密度、结构和字数的精准优化建议。', 'AI content SEO tool analyzing competitors and providing keyword density and structure guidance.', '$89/月', 4.6, 'https://surferseo.com', ARRAY['内容SEO实时评分','竞品内容分析','关键词密度优化','内容结构建议'], true, true, false, 'surfer-seo', 'AI SEO', 'AI实时内容SEO优化评分工具', ARRAY['SEO建议精准实用','竞品分析直观','内容优化效果好'], ARRAY['价格偏高','主要面向英文内容'], '内容营销SEO优化的高效工具', ARRAY['热门'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Buffer AI', 'Buffer AI', '营销', '社交媒体管理工具Buffer内置AI助手，自动生成社媒内容、优化发布时间和分析内容表现。', 'Buffer social media management with AI content generation and optimal posting time analysis.', '免费+付费', 4.4, 'https://buffer.com', ARRAY['AI社媒内容生成','最佳发布时间推荐','多平台统一管理','内容表现分析'], false, true, false, 'buffer-ai', 'AI社媒', 'Buffer内置AI社交媒体管理工具', ARRAY['多平台管理方便','AI内容生成实用','免费版可用'], ARRAY['高级分析需付费','AI生成质量一般'], '个人和小团队社媒管理推荐', ARRAY['免费','热门'], 4300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Hootsuite AI', 'Hootsuite AI', '营销', '企业级社交媒体管理平台，AI辅助内容创作、最佳发布时间预测和社媒效果分析报告。', 'Enterprise social media management with AI content creation and performance analytics.', '$99/月', 4.4, 'https://www.hootsuite.com', ARRAY['AI内容创作辅助','发布时间AI预测','多账号统一管理','社媒效果报告'], false, false, false, 'hootsuite-ai', 'AI社媒', '企业级AI社交媒体管理平台', ARRAY['企业功能最全面','多账号管理方便','报告分析专业'], ARRAY['价格较高','界面较为复杂'], '企业社媒团队统一管理推荐', ARRAY['热门'], 4200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Notion AI', 'Notion AI', '营销', 'Notion内置AI写作助手，辅助营销策划文档、内容日历、会议纪要和创意头脑风暴。', 'Notion built-in AI writing assistant for marketing plans, content calendars and brainstorming.', '$10/月', 4.6, 'https://www.notion.so/product/ai', ARRAY['AI文档写作辅助','内容日历规划','会议纪要生成','创意头脑风暴'], true, true, false, 'notion-ai', 'AI写作', 'Notion内置AI营销文档写作助手', ARRAY['与Notion无缝集成','写作辅助质量高','价格亲民'], ARRAY['需要Notion订阅','功能相对通用'], 'Notion用户营销策划和内容创作推荐', ARRAY['热门','今日推荐'], 4100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Klaviyo AI', 'Klaviyo AI', '营销', '电商邮件和短信营销平台，AI驱动的个性化推荐、受众细分和发送时间优化，提升电商转化。', 'E-commerce email and SMS marketing with AI personalization and send time optimization.', '$20/月', 4.6, 'https://www.klaviyo.com', ARRAY['AI个性化产品推荐','受众智能细分','发送时间优化','电商行为触发邮件'], true, true, false, 'klaviyo-ai', 'AI邮件', '电商专用AI邮件短信营销平台', ARRAY['电商场景针对性强','个性化效果出色','转化率提升明显'], ARRAY['主要面向电商场景','价格随联系人增加'], '电商品牌邮件营销提升转化首选', ARRAY['热门','TG精选'], 4000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Writesonic', 'Writesonic', '营销', 'AI内容创作平台，支持SEO文章、广告文案、产品描述批量生成，内置Chatsonic AI助手。', 'AI content platform for SEO articles, ad copy and product descriptions with Chatsonic.', '免费+付费', 4.4, 'https://writesonic.com', ARRAY['SEO文章批量生成','广告文案创作','产品描述生成','Chatsonic AI助手'], false, true, false, 'writesonic', 'AI内容', 'SEO文章广告文案AI批量生成', ARRAY['内容生成速度快','SEO优化集成','免费版可用'], ARRAY['内容质量参差不齐','需要人工润色'], '内容营销团队批量生产内容推荐', ARRAY['免费','热门'], 3900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Sprout Social AI', 'Sprout Social AI', '营销', '企业社媒管理平台，AI辅助内容创作、情感分析、竞品监控和社媒ROI报告，适合大型品牌。', 'Enterprise social media platform with AI content creation, sentiment analysis and ROI reporting.', '$249/月', 4.5, 'https://sproutsocial.com', ARRAY['AI内容创作辅助','情感分析监控','竞品社媒追踪','ROI报告分析'], false, false, false, 'sprout-social-ai', 'AI社媒', '大型品牌企业级AI社媒管理平台', ARRAY['企业功能最完善','情感分析准确','ROI报告专业'], ARRAY['价格较高','小团队功能过剩'], '大型品牌社媒团队管理推荐', ARRAY['热门'], 3800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Persado', 'Persado', '营销', 'AI营销语言优化平台，通过分析情感和语言模式，生成最能引发目标受众共鸣的营销文案。', 'AI marketing language platform generating emotionally resonant copy through language analysis.', '企业定价', 4.5, 'https://www.persado.com', ARRAY['情感语言AI分析','高转化文案生成','A/B测试自动化','受众共鸣优化'], true, false, false, 'persado', 'AI文案', 'AI情感语言分析高转化文案生成', ARRAY['文案转化率提升显著','情感分析独特','大品牌验证效果'], ARRAY['企业级定价较贵','主要面向大品牌'], '大型品牌提升营销文案转化率推荐', ARRAY['热门'], 3700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Phrasee', 'Phrasee', '营销', 'AI邮件主题行和推送通知优化工具，通过机器学习生成高打开率的营销文案，持续学习优化。', 'AI email subject line and push notification optimizer generating high open-rate copy.', '企业定价', 4.4, 'https://phrasee.co', ARRAY['邮件主题行AI优化','推送通知文案生成','持续学习优化','A/B测试自动化'], false, false, false, 'phrasee', '主题优化', 'AI优化邮件主题行提升打开率', ARRAY['打开率提升效果好','持续学习改进','大品牌广泛验证'], ARRAY['企业级定价较贵','主要面向大型企业'], '邮件营销打开率优化的专业工具', ARRAY['热门'], 3600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Optimizely AI', 'Optimizely AI', '营销', '数字体验优化平台，AI驱动的A/B测试、个性化内容推送和网站转化率优化，适合大型网站。', 'Digital experience optimization with AI A/B testing, personalization and CRO for large sites.', '企业定价', 4.5, 'https://www.optimizely.com', ARRAY['AI驱动A/B测试','个性化内容推送','转化率优化','多变量测试'], true, false, false, 'optimizely-ai', 'A/B测试', 'AI驱动网站A/B测试转化优化', ARRAY['A/B测试功能最强','个性化效果出色','数据分析深度好'], ARRAY['价格极高','主要面向大型网站'], '大型网站转化率优化的行业标杆', ARRAY['热门'], 3500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Albert AI', 'Albert AI', '营销', 'AI自主数字广告平台，自动优化跨渠道广告投放、预算分配和受众定向，24小时持续优化。', 'Autonomous AI digital advertising platform auto-optimizing cross-channel ads and budgets.', '企业定价', 4.4, 'https://albert.ai', ARRAY['跨渠道广告自动优化','预算智能分配','受众定向优化','24小时持续学习'], false, false, false, 'albert-ai', 'AI广告', 'AI自主优化跨渠道数字广告平台', ARRAY['自动化程度极高','跨渠道优化强','持续学习改进'], ARRAY['企业级定价较贵','需要一定数据量'], '大型品牌数字广告自动化优化推荐', ARRAY['热门'], 3400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mutiny', 'Mutiny', '营销', 'B2B网站个性化AI平台，根据访客公司和行为自动展示个性化内容，提升B2B网站转化率。', 'B2B website personalization AI showing customized content based on visitor company data.', '企业定价', 4.5, 'https://www.mutinyhq.com', ARRAY['B2B访客公司识别','个性化内容展示','转化率优化','ABM营销支持'], true, false, false, 'mutiny', 'B2B个性化', 'B2B网站访客个性化AI平台', ARRAY['B2B场景针对性强','个性化效果出色','ABM支持好'], ARRAY['企业级定价较贵','需要一定流量'], 'B2B企业网站转化率提升必备', ARRAY['热门'], 3300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Drift AI', 'Drift AI', '营销', 'AI对话营销平台，智能聊天机器人自动与网站访客对话、资质筛选和预约演示，提升销售效率。', 'AI conversational marketing platform with chatbots for visitor engagement and lead qualification.', '$2500/月', 4.4, 'https://www.drift.com', ARRAY['AI智能聊天机器人','访客资质自动筛选','演示预约自动化','销售对话分析'], false, false, false, 'drift-ai', 'AI对话', 'AI对话营销自动筛选销售线索', ARRAY['线索筛选自动化','预约转化率高','销售效率提升'], ARRAY['价格极高','主要面向B2B企业'], 'B2B企业网站销售线索自动化推荐', ARRAY['热门'], 3200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Intercom AI', 'Intercom AI', '营销', 'AI客户沟通平台，Fin AI机器人自动回答客户问题，支持营销自动化、用户引导和客户成功。', 'AI customer communication platform with Fin AI bot for support and marketing automation.', '$74/月', 4.5, 'https://www.intercom.com', ARRAY['Fin AI智能客服机器人','营销自动化流程','用户引导onboarding','客户成功管理'], true, true, false, 'intercom-ai', 'AI客服', 'Intercom Fin AI智能客服营销平台', ARRAY['AI客服质量出色','营销自动化强','用户体验好'], ARRAY['价格较高','功能复杂需学习'], 'SaaS产品客服和营销自动化首选', ARRAY['热门','今日推荐'], 3100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Marketo AI', 'Marketo AI', '营销', 'Adobe旗下企业级营销自动化平台，AI辅助潜客培育、评分和个性化内容推送，适合大型企业。', 'Adobe enterprise marketing automation with AI lead nurturing, scoring and personalization.', '企业定价', 4.4, 'https://business.adobe.com/products/marketo', ARRAY['潜客AI评分培育','个性化内容推送','营销自动化流程','ROI归因分析'], false, false, false, 'marketo-ai', '营销自动化', 'Adobe企业级AI营销自动化平台', ARRAY['企业功能最完善','Adobe生态集成','潜客管理专业'], ARRAY['价格极高','实施复杂度高'], '大型企业B2B营销自动化标杆工具', ARRAY['热门'], 3000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Salesforce Marketing Cloud AI', 'Salesforce Marketing Cloud AI', '营销', 'Salesforce旗下AI营销云，Einstein AI驱动的个性化推送、旅程自动化和预测分析。', 'Salesforce AI marketing cloud with Einstein-powered personalization and journey automation.', '企业定价', 4.5, 'https://www.salesforce.com/products/marketing-cloud', ARRAY['Einstein AI个性化','客户旅程自动化','预测分析洞察','跨渠道营销协调'], true, false, false, 'salesforce-marketing-cloud', 'AI营销云', 'Salesforce Einstein AI营销自动化', ARRAY['Salesforce生态集成','个性化能力强','预测分析深度好'], ARRAY['价格极高','需要Salesforce生态'], 'Salesforce用户营销自动化升级首选', ARRAY['热门'], 2900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Brandwatch AI', 'Brandwatch AI', '营销', '社交媒体监听和消费者洞察AI平台，实时追踪品牌声誉、竞品动态和行业趋势。', 'Social media listening and consumer insights AI platform for brand reputation tracking.', '企业定价', 4.5, 'https://www.brandwatch.com', ARRAY['品牌声誉实时监听','竞品动态追踪','消费者情感分析','行业趋势洞察'], true, false, false, 'brandwatch-ai', '品牌监听', 'AI社交媒体品牌声誉监听平台', ARRAY['监听覆盖范围广','情感分析准确','洞察报告专业'], ARRAY['价格较高','数据量大需筛选'], '品牌管理和市场洞察的专业工具', ARRAY['热门'], 2800, 'active');
