-- 会计分类（26-50）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Cube', 'Cube', '会计', 'Excel和Google Sheets原生FP&A平台，AI辅助财务规划，无需迁移现有电子表格工作流。', 'Native Excel and Google Sheets FP&A platform with AI financial planning assistance.', '$1500/月', 4.4, 'https://www.cubesoftware.com', ARRAY['Excel原生集成','财务规划自动化','预算版本管理','多维度分析'], false, false, false, 'cube-software', 'FP&A', 'Excel原生AI财务规划分析平台', ARRAY['Excel集成无缝','迁移成本低','财务团队易上手'], ARRAY['价格较高','功能不如专业FP&A工具'], '习惯Excel的财务团队FP&A升级推荐', ARRAY['热门'], 2800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mosaic Tech', 'Mosaic Tech', '会计', '战略财务平台，实时整合ERP和CRM数据，AI驱动的财务分析和可视化，帮助CFO做出更快决策。', 'Strategic finance platform integrating ERP and CRM data with AI-driven analytics for CFOs.', '企业定价', 4.5, 'https://www.mosaic.tech', ARRAY['ERP/CRM数据实时整合','AI财务分析','CFO决策仪表盘','情景规划建模'], true, false, false, 'mosaic-tech', 'CFO平台', 'CFO战略财务决策AI分析平台', ARRAY['数据整合能力强','可视化效果出色','决策支持深度好'], ARRAY['价格较高','实施需要技术支持'], '成长期企业CFO财务分析首选', ARRAY['热门'], 2700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Vena Solutions', 'Vena Solutions', '会计', 'Excel集成的企业绩效管理平台，AI辅助预算、预测和报告，保留Excel操作习惯同时增强协作。', 'Excel-integrated enterprise performance management with AI budgeting and forecasting.', '企业定价', 4.4, 'https://www.venasolutions.com', ARRAY['Excel集成操作','预算预测自动化','企业绩效管理','协作审批工作流'], false, false, false, 'vena-solutions', '绩效管理', 'Excel集成企业绩效管理AI平台', ARRAY['Excel习惯保留','协作功能强','企业级安全'], ARRAY['价格较高','实施周期长'], '大型企业预算管理数字化推荐', ARRAY['热门'], 2600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Chargebee', 'Chargebee', '会计', '订阅业务收入管理AI平台，自动处理订阅计费、收入确认和财务报告，适合SaaS企业。', 'Subscription revenue management AI platform for billing, recognition and reporting for SaaS.', '$249/月', 4.5, 'https://www.chargebee.com', ARRAY['订阅计费自动化','收入确认处理','财务报告生成','客户生命周期管理'], true, false, false, 'chargebee', '订阅计费', 'SaaS订阅收入管理AI自动化平台', ARRAY['订阅场景针对性强','收入确认合规','集成生态丰富'], ARRAY['主要面向订阅业务','价格随规模增加'], 'SaaS和订阅制企业收入管理首选', ARRAY['热门'], 2500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Stripe Revenue Recognition', 'Stripe Revenue Recognition', '会计', 'Stripe推出的收入确认自动化工具，自动按ASC 606/IFRS 15准则处理收入，生成合规报告。', 'Stripe revenue recognition automation following ASC 606/IFRS 15 standards.', '$0.25%交易额', 4.5, 'https://stripe.com/revenue-recognition', ARRAY['ASC 606自动合规','收入确认自动化','合规报告生成','与Stripe支付集成'], true, false, false, 'stripe-revenue-recognition', '收入确认', 'Stripe收入确认自动合规工具', ARRAY['与Stripe无缝集成','合规处理准确','报告生成自动'], ARRAY['仅适用Stripe用户','按交易额收费'], 'Stripe用户收入确认合规必备', ARRAY['热门'], 2400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Avalara', 'Avalara', '会计', '全球税务合规自动化平台，AI自动计算销售税、增值税，支持200+国家税务规则，适合跨境电商。', 'Global tax compliance automation calculating sales tax and VAT for 200+ countries.', '$50/月起', 4.4, 'https://www.avalara.com', ARRAY['全球销售税自动计算','200+国家税务规则','税务申报自动化','跨境电商税务'], true, true, false, 'avalara', '全球税务', '全球200+国家税务合规自动化', ARRAY['全球税务覆盖最广','计算准确率高','跨境电商专业'], ARRAY['价格随交易量增加','配置较为复杂'], '跨境电商和全球业务税务合规必备', ARRAY['热门','TG精选'], 2300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('TaxJar', 'TaxJar', '会计', '电商销售税自动化工具，实时计算美国各州销售税，自动申报，与主流电商平台无缝集成。', 'E-commerce sales tax automation with real-time calculation and auto-filing for US states.', '$19/月', 4.4, 'https://www.taxjar.com', ARRAY['美国销售税实时计算','自动申报各州','电商平台集成','税务豁免管理'], false, false, false, 'taxjar', '销售税', '美国电商销售税自动计算申报', ARRAY['美国销售税覆盖全','自动申报省心','电商集成方便'], ARRAY['仅覆盖美国销售税','价格随交易量增加'], '美国电商卖家销售税合规必备', ARRAY['热门'], 2200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Pilot', 'Pilot', '会计', '专为初创公司提供的AI记账和税务服务，结合自动化软件和专业会计师，提供CFO咨询服务。', 'AI bookkeeping and tax service for startups combining automation with professional accountants.', '$499/月', 4.5, 'https://pilot.com', ARRAY['AI自动化记账','专业会计师审核','税务申报服务','CFO咨询服务'], true, false, false, 'pilot', 'AI记账服务', '初创公司AI记账+会计师服务', ARRAY['AI+人工结合可靠','初创公司针对性强','CFO服务有价值'], ARRAY['价格较高','主要面向美国市场'], '融资后初创公司财务外包首选', ARRAY['热门'], 2100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Bench', 'Bench', '会计', '小企业AI记账服务，专属会计师团队配合自动化软件，每月提供财务报表和税务准备。', 'Small business AI bookkeeping service with dedicated accountants and monthly financial reports.', '$299/月', 4.3, 'https://bench.co', ARRAY['专属会计师服务','月度财务报表','税务准备服务','历史账目整理'], false, false, false, 'bench', '记账服务', '小企业AI记账+专属会计师服务', ARRAY['专属会计师服务好','报表质量专业','历史整理能力强'], ARRAY['价格偏高','主要面向美国市场'], '没有财务人员的小企业记账外包', ARRAY['热门'], 2000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Digits', 'Digits', '会计', 'AI财务分析工具，自动连接银行和会计软件，用自然语言回答财务问题，生成财务洞察报告。', 'AI financial analytics connecting bank and accounting data with natural language Q&A.', '$75/月', 4.4, 'https://digits.com', ARRAY['自然语言财务问答','银行数据自动连接','财务洞察报告','异常支出提醒'], false, false, true, 'digits', 'AI财务问答', '自然语言回答财务问题AI工具', ARRAY['自然语言交互直觉','洞察报告有价值','异常提醒实用'], ARRAY['功能相对新颖','主要面向美国市场'], '想用自然语言了解财务状况的工具', ARRAY['今日推荐'], 1900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Klarity', 'Klarity', '会计', 'AI合同数据提取工具，专注财务和会计场景，自动从合同中提取收入确认和付款条款数据。', 'AI contract data extraction for finance, automatically extracting revenue and payment terms.', '企业定价', 4.3, 'https://www.klaritylaw.com', ARRAY['合同财务数据提取','收入条款自动识别','付款条款提取','会计系统集成'], false, false, false, 'klarity', '合同提取', 'AI从合同提取财务关键数据工具', ARRAY['财务数据提取准确','会计场景针对性强','减少手工录入'], ARRAY['价格较高','需要专业培训'], '财务团队合同数据录入自动化推荐', ARRAY['热门'], 1800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Leapfin', 'Leapfin', '会计', '收入数据自动化平台，统一来自多个系统的收入数据，自动生成符合会计准则的收入报告。', 'Revenue data automation platform unifying multi-system data for compliant revenue reporting.', '企业定价', 4.4, 'https://www.leapfin.com', ARRAY['多系统收入数据统一','收入报告自动生成','会计准则合规','数据可追溯审计'], false, false, false, 'leapfin', '收入数据', '多系统收入数据统一自动化平台', ARRAY['数据统一能力强','合规报告准确','审计追溯清晰'], ARRAY['价格较高','实施周期较长'], '多收入来源企业财务数据整合推荐', ARRAY['热门'], 1700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Numeric', 'Numeric', '会计', 'AI财务关账加速平台，自动化月末关账流程，追踪关账任务进度，减少关账时间50%以上。', 'AI financial close acceleration platform automating month-end close and task tracking.', '企业定价', 4.4, 'https://www.numeric.io', ARRAY['月末关账自动化','关账任务追踪','异常自动检测','关账时间缩短'], false, false, true, 'numeric', '关账加速', 'AI月末财务关账自动化加速平台', ARRAY['关账效率提升显著','任务追踪清晰','异常检测准确'], ARRAY['价格较高','需要与现有系统集成'], '财务团队月末关账效率提升推荐', ARRAY['今日推荐'], 1600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Spendesk', 'Spendesk', '会计', '欧洲企业支出管理平台，智能企业卡配合AI费用管理，实时可见所有企业支出，自动对账。', 'European corporate spend management with smart cards and real-time expense visibility.', '$99/月', 4.4, 'https://www.spendesk.com', ARRAY['智能企业卡管理','实时支出可见性','费用自动对账','预算控制管理'], false, false, false, 'spendesk', '支出管理', '欧洲企业智能支出管理平台', ARRAY['实时可见性强','对账自动化高','欧洲合规好'], ARRAY['主要面向欧洲市场','价格偏高'], '欧洲企业支出管理和控制推荐', ARRAY['热门'], 1500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Pleo', 'Pleo', '会计', '北欧企业支出管理工具，员工智能卡配合自动收据匹配，实时费用追踪，简化报销流程。', 'Nordic corporate spend tool with smart employee cards and automatic receipt matching.', '$45/月', 4.5, 'https://www.pleo.io', ARRAY['员工智能卡发放','收据自动匹配','实时费用追踪','报销流程简化'], false, true, false, 'pleo', '员工支出', '员工智能卡自动收据匹配工具', ARRAY['员工使用体验好','收据匹配准确','报销流程极简'], ARRAY['主要面向欧洲市场','高级功能需付费'], '欧洲中小企业员工支出管理推荐', ARRAY['热门'], 1400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Airbase', 'Airbase', '会计', '一体化企业支出管理平台，整合企业卡、报销、应付账款和采购审批，全面控制企业支出。', 'All-in-one corporate spend management integrating cards, reimbursements and AP.', '$500/月', 4.5, 'https://www.airbase.com', ARRAY['企业卡统一管理','报销流程自动化','应付账款处理','采购审批工作流'], false, false, false, 'airbase', '支出控制', '企业支出全面管控一体化平台', ARRAY['功能覆盖最全面','审批流程灵活','财务可见性强'], ARRAY['价格较高','实施周期较长'], '中大型企业全面支出管控推荐', ARRAY['热门'], 1300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Coupa', 'Coupa', '会计', '企业级采购和支出管理AI平台，覆盖采购、发票、费用和供应链，广泛用于大型企业。', 'Enterprise procurement and spend management AI covering purchasing, invoices and supply chain.', '企业定价', 4.5, 'https://www.coupa.com', ARRAY['采购全流程管理','发票自动处理','费用管理','供应链可见性'], true, false, false, 'coupa', '采购管理', '大型企业采购支出管理AI平台', ARRAY['功能最全面成熟','大企业广泛验证','供应链整合强'], ARRAY['价格极高','实施复杂度高'], '大型企业采购和支出管理标杆', ARRAY['热门'], 1200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Navan', 'Navan', '会计', '企业差旅和费用管理一体化平台，AI优化差旅预订，自动费用报告，实时政策合规检查。', 'Corporate travel and expense management platform with AI travel optimization and auto reporting.', '免费+付费', 4.5, 'https://navan.com', ARRAY['AI差旅预订优化','费用自动报告','政策合规实时检查','差旅数据分析'], true, true, false, 'navan', '差旅费用', '企业差旅费用管理一体化平台', ARRAY['差旅和费用一体化','政策合规自动','用户体验出色'], ARRAY['主要面向美国市场','高级功能需付费'], '企业差旅和费用管理的现代化工具', ARRAY['热门','今日推荐'], 1100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Concur', 'Concur', '会计', 'SAP旗下企业差旅和费用管理平台，全球最广泛使用的差旅报销系统，AI辅助合规检查。', 'SAP corporate travel and expense management platform used globally with AI compliance.', '$8/用户/月', 4.3, 'https://www.concur.com', ARRAY['差旅预订管理','费用报告提交','AI合规检查','ERP系统集成'], false, false, false, 'concur', '差旅报销', 'SAP旗下全球最广泛差旅报销系统', ARRAY['全球使用最广泛','SAP集成好','合规检查可靠'], ARRAY['界面较为老旧','移动端体验一般'], '大型企业差旅报销管理的行业标准', ARRAY['热门'], 1000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Zoho Books AI', 'Zoho Books AI', '会计', 'Zoho旗下AI财务软件，自动化记账、发票和报税，与Zoho生态深度集成，性价比极高。', 'Zoho AI accounting software with automated bookkeeping, invoicing and tax filing.', '$15/月', 4.4, 'https://www.zoho.com/books', ARRAY['AI自动化记账','发票管理','税务申报辅助','Zoho生态集成'], false, true, false, 'zoho-books-ai', 'AI财务', 'Zoho生态AI财务记账软件', ARRAY['性价比极高','Zoho集成好','功能覆盖全面'], ARRAY['界面不够现代','高级功能需升级'], 'Zoho用户和预算有限企业的首选', ARRAY['热门'], 900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('FreshBooks AI', 'FreshBooks AI', '会计', '专为自由职业者和小企业设计的AI财务软件，发票、时间追踪和费用管理一体化，操作简单。', 'AI accounting software for freelancers with invoicing, time tracking and expense management.', '$17/月', 4.4, 'https://www.freshbooks.com', ARRAY['专业发票生成','时间追踪计费','费用管理','财务报告生成'], false, false, false, 'freshbooks-ai', 'AI发票', '自由职业者专用AI财务管理工具', ARRAY['自由职业场景针对','发票设计专业','操作极简单'], ARRAY['功能相对基础','规模扩展有限'], '自由职业者和小工作室财务管理推荐', ARRAY['热门'], 800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Wave Accounting', 'Wave Accounting', '会计', '完全免费的小企业财务软件，提供记账、发票和收据扫描功能，AI辅助财务报告生成。', 'Completely free small business accounting with bookkeeping, invoicing and receipt scanning.', '免费', 4.3, 'https://www.waveapps.com', ARRAY['完全免费记账','专业发票生成','收据扫描识别','财务报告生成'], false, true, false, 'wave-accounting', '免费记账', '完全免费的小企业AI财务软件', ARRAY['完全免费无限制','功能够用实用','操作简单易上手'], ARRAY['高级功能需付费','客服支持有限'], '预算有限小企业财务管理免费首选', ARRAY['免费','热门'], 700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Kashoo', 'Kashoo', '会计', '简单易用的AI云财务软件，自动分类交易，一键生成财务报表，专为非财务背景小企业主设计。', 'Simple AI cloud accounting with automatic transaction categorization for non-accountants.', '$20/月', 4.2, 'https://kashoo.com', ARRAY['交易AI自动分类','一键财务报表','银行自动同步','税务准备辅助'], false, false, false, 'kashoo', 'AI记账', '非财务背景小企业主AI记账工具', ARRAY['操作极简单易懂','AI分类准确','价格亲民'], ARRAY['功能相对基础','高级报告有限'], '没有财务背景的小企业主记账推荐', ARRAY['免费'], 600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Fathom', 'Fathom', '会计', 'AI财务报告和分析工具，连接QuickBooks/Xero，自动生成美观的财务分析报告和KPI仪表盘。', 'AI financial reporting connecting QuickBooks/Xero to generate beautiful analysis reports.', '$39/月', 4.5, 'https://www.fathomhq.com', ARRAY['财务报告自动生成','KPI仪表盘','QuickBooks/Xero集成','客户报告定制'], true, false, false, 'fathom', 'AI报告', 'AI生成美观财务分析报告工具', ARRAY['报告设计专业美观','KPI追踪直观','集成方便快捷'], ARRAY['依赖第三方数据源','高级功能需付费'], '会计师向客户展示财务分析的利器', ARRAY['热门','今日推荐'], 500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('LiveFlow', 'LiveFlow', '会计', 'Google Sheets财务自动化工具，将QuickBooks/Xero数据实时同步到Google Sheets，自动更新报告。', 'Google Sheets finance automation syncing QuickBooks/Xero data for real-time reports.', '$99/月', 4.4, 'https://www.liveflow.io', ARRAY['Google Sheets实时同步','财务报告自动更新','QuickBooks/Xero集成','自定义报告模板'], false, false, false, 'liveflow', 'Sheets财务', 'Google Sheets财务数据实时同步', ARRAY['Google Sheets集成无缝','报告更新自动','模板自定义灵活'], ARRAY['依赖Google Sheets','价格偏高'], '习惯Google Sheets的财务团队推荐', ARRAY['热门'], 400, 'active');
