-- TG AI工具库 批量导入数据
-- 使用方法：在 Supabase SQL Editor 中执行此文件
-- 共300条，6个职业分类各50条

-- ══════════════════════════════════════════
-- 律师分类（1-25）
-- ══════════════════════════════════════════

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法狗狗', 'FaGouGou', '律师', '专为律师设计的AI法律检索工具，覆盖全国法规、案例、裁判文书，支持智能语义搜索。', 'AI legal search tool for lawyers covering national regulations and cases.', '免费+付费', 4.7, 'https://www.fagougou.com', ARRAY['智能语义法律检索','裁判文书全库搜索','法规实时更新','一键生成检索报告'], true, true, false, 'fagougou', 'AI法律检索', '律师必备的AI法律检索神器', ARRAY['检索速度快秒出结果','覆盖案例超2亿条','支持多维度筛选'], ARRAY['免费版每日限10次','部分裁判文书需付费'], '适合日常案例检索和法规查询', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法大大', 'FaDaDa', '律师', 'AI驱动的电子合同与法律文件管理平台，支持合同在线签署、存证及智能风险审查。', 'AI-powered electronic contract and legal document management platform.', '免费+付费', 4.6, 'https://www.fadada.com', ARRAY['电子合同在线签署','合同智能风险审查','区块链存证','批量合同管理'], true, true, false, 'fadada', '电子合同', 'AI合同签署与风险审查平台', ARRAY['签署流程简便快捷','区块链存证可靠','企业批量签署高效'], ARRAY['高级功能需付费','客服响应稍慢'], '合同签署和存证首选工具', ARRAY['热门','今日推荐'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('无讼', 'Wusong', '律师', '专业法律信息服务平台，提供海量裁判文书检索、法律知识图谱和律师社区交流。', 'Professional legal information platform with judgment search and knowledge graph.', '免费+付费', 4.5, 'https://www.wusong.com', ARRAY['裁判文书智能检索','法律知识图谱','律师社区交流','法规数据库'], true, true, false, 'wusong', '法律检索', '法律人必备的专业信息平台', ARRAY['文书数据库庞大','知识图谱直观','社区氛围活跃'], ARRAY['高级检索需付费','部分数据更新慢'], '法律检索和同行交流首选', ARRAY['热门','今日推荐'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('北大法宝', 'PKULaw', '律师', '北京大学法制信息中心旗下权威法律数据库，覆盖法规、案例、学术文献，AI检索助手加持。', 'Authoritative legal database from PKU covering regulations, cases and academic literature.', '¥99/月', 4.6, 'https://www.pkulaw.com', ARRAY['法规全文智能检索','学术文献检索','案例数据库','法律法规对比'], true, true, false, 'pkulaw', 'AI法律库', '北大法宝AI智能检索助手', ARRAY['数据权威学术背景','法规覆盖最全面','学术资源丰富'], ARRAY['价格偏高','界面不够现代'], '法学研究和实务检索双优选', ARRAY['热门','今日推荐'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Harvey AI', 'Harvey AI', '律师', '专为律师事务所设计的生成式AI平台，支持合同分析、尽职调查、法律研究和文书起草。', 'Generative AI platform for law firms supporting contract analysis and due diligence.', '企业定价', 4.8, 'https://www.harvey.ai', ARRAY['合同智能分析','尽职调查自动化','法律研究加速','文书起草辅助'], true, true, true, 'harvey-ai', '律所AI平台', '顶级律所专用生成式AI平台', ARRAY['大所验证效果卓越','安全合规有保障','多语言支持'], ARRAY['仅面向企业客户','价格不透明'], '大型律所数字化转型首选', ARRAY['热门','TG精选'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Casetext', 'Casetext', '律师', '美国领先的AI法律研究平台，集成GPT-4的CARA功能可自动分析案件并推荐相关判例。', 'Leading US AI legal research platform with GPT-4 powered case analysis.', '$65/月', 4.8, 'https://casetext.com', ARRAY['AI案件分析CARA','判例智能推荐','法律文书起草','多司法管辖区检索'], true, true, false, 'casetext', 'AI判例研究', '美国顶级AI法律研究平台', ARRAY['AI分析准确度极高','判例推荐精准','节省大量研究时间'], ARRAY['仅支持英文','价格较高'], '英文法律研究的最强AI工具', ARRAY['热门','TG精选'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Kira Systems', 'Kira Systems', '律师', '专业合同分析AI平台，利用机器学习自动提取合同关键条款，加速尽职调查流程。', 'Professional contract analysis AI using ML to extract key contract clauses.', '企业定价', 4.6, 'https://kirasystems.com', ARRAY['合同条款自动提取','尽职调查加速','自定义条款训练','多语言合同支持'], true, false, false, 'kira-systems', '合同分析', '机器学习驱动的合同分析平台', ARRAY['条款提取准确率高','支持自定义训练','多语言能力强'], ARRAY['企业级定价较贵','需要一定培训'], '大型并购项目尽调必备', ARRAY['热门'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Luminance', 'Luminance', '律师', '英国AI法律科技公司，提供合同审查、尽职调查和法律文件分析的企业级AI平台。', 'UK AI legal tech company providing enterprise contract review and due diligence.', '企业定价', 4.6, 'https://www.luminance.com', ARRAY['AI合同审查','尽职调查自动化','异常条款检测','多语言文件分析'], true, false, false, 'luminance', '合同尽调', '企业级AI法律文件分析平台', ARRAY['异常检测能力强','多语言支持好','大所广泛采用'], ARRAY['价格较高','需要专业培训'], '跨境并购尽调的高效工具', ARRAY['热门'], 4300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Westlaw Edge', 'Westlaw Edge', '律师', '汤森路透旗下AI增强法律研究平台，提供判例预测、引用分析和智能法律研究功能。', 'Thomson Reuters AI-enhanced legal research with case prediction and citation analysis.', '$200/月', 4.7, 'https://legal.thomsonreuters.com/westlaw', ARRAY['判例结果预测','引用有效性分析','AI智能检索','法规变更追踪'], true, true, false, 'westlaw-edge', '判例预测', '汤森路透AI法律研究旗舰产品', ARRAY['判例预测准确率高','引用分析权威','数据更新及时'], ARRAY['价格极高','主要面向美国法律'], '美国诉讼律师的核心工具', ARRAY['热门','TG精选'], 4200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('LexisNexis AI', 'LexisNexis AI', '律师', '全球顶级法律数据库LexisNexis推出的AI助手，整合海量判例和法规，支持智能法律研究。', 'AI assistant from global legal database LexisNexis for intelligent legal research.', '$150/月', 4.7, 'https://www.lexisnexis.com', ARRAY['全球法律数据库检索','AI智能摘要','判例关联分析','法规追踪更新'], true, true, false, 'lexisnexis-ai', '全球法律库', '全球最大法律数据库AI助手', ARRAY['数据库覆盖最全面','AI摘要质量高','多国法律支持'], ARRAY['订阅费用昂贵','界面较为复杂'], '跨国法律研究必备工具', ARRAY['热门'], 4100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法信', 'FaXin', '律师', '最高人民法院旗下法律信息平台，提供权威法规、司法解释、指导案例的免费检索服务。', 'Legal information platform under Supreme Court with authoritative free regulation search.', '免费', 4.5, 'https://www.faxin.cn', ARRAY['最高法权威数据','司法解释全文','指导案例检索','法规实时更新'], true, true, false, 'faxin', '权威法规', '最高法旗下权威法律信息平台', ARRAY['数据来源最权威','完全免费使用','更新及时准确'], ARRAY['AI功能较弱','检索体验一般'], '查权威法规和司法解释必备', ARRAY['免费','热门'], 4000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('知产宝', 'ZhiChanBao', '律师', '专注知识产权领域的AI检索分析平台，覆盖专利、商标、版权数据，支持侵权分析。', 'AI search platform for IP covering patents, trademarks, copyright and infringement analysis.', '免费+付费', 4.5, 'https://www.zhichanbaogao.com', ARRAY['专利智能检索分析','商标近似度比对','版权登记查询','侵权风险评估'], true, true, false, 'zhichan-bao', '知识产权', '知识产权AI检索分析平台', ARRAY['知产数据覆盖全面','侵权分析准确','报告生成专业'], ARRAY['部分高级功能收费','国际专利支持有限'], '知产律师和企业IP团队必备', ARRAY['热门','今日推荐'], 3900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Ironclad', 'Ironclad', '律师', '硅谷明星合同管理平台，AI驱动的合同工作流自动化，深受科技公司法务团队青睐。', 'Silicon Valley contract management platform with AI-driven workflow automation.', '$500/月起', 4.7, 'https://ironcladapp.com', ARRAY['合同工作流自动化','AI合同数据提取','电子签名集成','合同分析仪表盘'], true, true, false, 'ironclad', '合同工作流', '科技公司法务首选合同平台', ARRAY['工作流设计灵活','集成生态丰富','用户体验极佳'], ARRAY['价格较高','主要面向英文合同'], '科技公司法务团队强烈推荐', ARRAY['热门','TG精选'], 3800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Lex Machina', 'Lex Machina', '律师', '领英旗下法律分析平台，通过大数据分析法官、律师、当事人的诉讼行为，辅助诉讼策略。', 'LinkedIn legal analytics platform analyzing judges and litigation behavior for strategy.', '$100/月', 4.6, 'https://lexmachina.com', ARRAY['法官裁判偏好分析','律师胜诉率统计','诉讼结果预测','对手律师分析'], true, false, false, 'lex-machina', '诉讼分析', '大数据驱动的诉讼策略分析', ARRAY['法官分析维度丰富','预测准确率高','数据可视化好'], ARRAY['仅覆盖美国法院','价格较高'], '美国诉讼策略制定的利器', ARRAY['热门'], 3700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('ContractPodAi', 'ContractPodAi', '律师', '企业合同生命周期管理AI平台，覆盖合同起草、谈判、审批、执行和续签全流程。', 'Enterprise contract lifecycle management AI covering drafting to renewal.', '企业定价', 4.5, 'https://contractpodai.com', ARRAY['合同全生命周期管理','AI辅助合同谈判','自动审批工作流','合同到期提醒'], false, false, false, 'contractpod-ai', '合同管理', '企业合同全生命周期AI平台', ARRAY['流程覆盖最完整','审批自动化高效','集成能力强'], ARRAY['实施周期较长','价格较高'], '企业法务部门合同管理首选', ARRAY['热门'], 3600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Relativity AI', 'Relativity AI', '律师', '电子取证领域领先平台，AI辅助文件审查、证据分析和诉讼数据管理，广泛用于大型诉讼。', 'Leading e-discovery platform with AI-assisted document review and evidence analysis.', '企业定价', 4.6, 'https://www.relativity.com', ARRAY['AI辅助电子取证','文件智能分类','证据关联分析','诉讼数据管理'], true, false, false, 'relativity-ai', '电子取证', '大型诉讼电子取证AI平台', ARRAY['取证能力业界领先','处理海量文件高效','安全合规有保障'], ARRAY['价格极高','需要专业团队'], '大型诉讼和调查必备工具', ARRAY['热门'], 3500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('智法AI', 'ZhiFaAI', '律师', '基于大语言模型的中国法律AI助手，专注中国法律体系的文书生成、法规解读和案例分析。', 'Chinese law AI assistant based on LLM for document generation and regulation analysis.', '免费+付费', 4.5, 'https://www.zhifaai.com', ARRAY['中国法律文书生成','法规智能解读','案例分析报告','庭审要点提炼'], true, false, true, 'zhifa-ai', '中国法律AI', '专注中国法律体系的AI助手', ARRAY['中文法律理解准确','文书生成质量高','更新速度快'], ARRAY['英文支持较弱','部分功能测试中'], '中国法律实务工作者首选', ARRAY['免费','今日推荐'], 3400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法律云', 'LawCloud', '律师', '国内专业法律SaaS平台，为律师事务所提供案件管理、财务核算、文档协作一体化解决方案。', 'Professional legal SaaS for law firms with case management and financial tools.', '¥199/月', 4.4, 'https://www.lawcloud.cn', ARRAY['律所案件管理','财务核算系统','文档协作共享','客户关系管理'], false, false, false, 'law-cloud', '律所管理', '律师事务所一体化管理平台', ARRAY['功能模块完整','数据安全可靠','支持多人协作'], ARRAY['初始配置复杂','移动端功能有限'], '中小律所管理系统首选', ARRAY['免费'], 3300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('OpenLaw', 'OpenLaw', '律师', '区块链智能合约与法律文件自动化平台，支持合同模板创建、数字签名和链上存证。', 'Blockchain smart contract and legal document automation with digital signatures.', '免费+付费', 4.3, 'https://openlaw.io', ARRAY['智能合约自动化','区块链合同存证','法律模板库','数字签名集成'], false, false, false, 'openlaw', '智能合约', '区块链法律合同自动化平台', ARRAY['区块链存证安全','模板库丰富','开源可定制'], ARRAY['技术门槛较高','中文支持有限'], '适合熟悉区块链的法律科技团队', ARRAY['免费'], 3200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('得到法律', 'DedaoLaw', '律师', '面向普通用户和律师的AI法律咨询平台，提供智能问答、文书模板和在线律师对接服务。', 'AI legal consultation platform with smart Q&A and online lawyer matching.', '免费+付费', 4.3, 'https://www.dedaolaw.com', ARRAY['AI法律智能问答','法律文书模板','在线律师对接','法规查询'], false, false, false, 'dedao-law', '法律咨询', 'AI法律咨询与律师对接平台', ARRAY['问答响应及时','模板种类多','律师资源丰富'], ARRAY['AI回答有时不准确','付费功能较多'], '法律咨询入门推荐', ARRAY['免费'], 3100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('法律快车AI', 'LawTimeAI', '律师', '国内知名法律服务平台法律快车推出的AI工具，提供法律咨询、文书模板和律师匹配服务。', 'AI tool from LawTime legal platform with consultation and lawyer matching.', '免费+付费', 4.2, 'https://www.lawtime.cn', ARRAY['AI法律咨询问答','法律文书模板库','律师在线匹配','法规查询工具'], false, false, false, 'lawtime-ai', '法律咨询', '法律快车AI咨询与律师匹配', ARRAY['律师资源丰富','模板库免费使用','响应速度快'], ARRAY['AI回答质量参差','广告较多'], '法律咨询和找律师的入门选择', ARRAY['免费'], 3000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('合同管家', 'ContractButler', '律师', 'AI合同智能审查与管理工具，自动识别合同风险条款，提供修改建议和合规报告。', 'AI contract review tool with automatic risk clause identification and compliance reports.', '¥299/月', 4.6, 'https://www.hetongguanjia.com', ARRAY['合同风险条款识别','智能修改建议','合规性自动检查','合同版本对比'], true, true, false, 'contract-butler', '合同审查', 'AI智能合同风险审查工具', ARRAY['风险识别准确率高','报告生成专业','支持多种合同类型'], ARRAY['价格偏高','学习成本稍大'], '合同审查效率提升10倍', ARRAY['热门','TG精选'], 2900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('律师助手Pro', 'LawyerAssistantPro', '律师', '国内领先的律师办公AI助手，集成案件管理、文书起草、法规检索于一体的综合平台。', 'Leading AI office assistant for lawyers with case management and document drafting.', '免费+付费', 4.4, 'https://www.lvshizhushou.com', ARRAY['案件全流程管理','法律文书智能起草','法规数据库检索','客户信息管理'], false, true, false, 'lawyer-assistant-pro', '律师办公', '律师一站式AI办公平台', ARRAY['功能覆盖全面','案件管理清晰','免费版可用'], ARRAY['界面设计较老旧','高级功能需付费'], '适合个人律师日常办公', ARRAY['免费','热门'], 2800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('中国裁判文书网', 'ChinaJudgmentNet', '律师', '最高人民法院官方裁判文书公开平台，收录全国各级法院裁判文书，免费查阅。', 'Official Supreme Court platform for public access to court judgments nationwide.', '免费', 4.3, 'https://wenshu.court.gov.cn', ARRAY['裁判文书全文检索','全国法院覆盖','多维度筛选','文书下载保存'], false, true, false, 'china-judgment-net', '裁判文书', '全国裁判文书官方查阅平台', ARRAY['数据来源权威官方','免费使用无限制','覆盖全国法院'], ARRAY['AI分析功能有限','界面较为基础'], '诉讼前必查的免费工具', ARRAY['免费','热门'], 2700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Spellbook', 'Spellbook', '律师', '基于GPT-4的合同起草AI助手，直接集成在Word中，实时提供合同条款建议和风险提示。', 'GPT-4 powered contract drafting AI integrated in Word with real-time clause suggestions.', '$99/月', 4.6, 'https://www.spellbook.legal', ARRAY['Word插件无缝集成','合同条款AI建议','风险条款实时提示','合同语言优化'], true, true, true, 'spellbook', 'Word合同AI', 'Word内嵌的AI合同起草助手', ARRAY['Word集成体验流畅','建议质量高','学习成本低'], ARRAY['仅支持英文合同','需要订阅费用'], '英文合同起草效率翻倍', ARRAY['热门','今日推荐'], 2600, 'active');
