-- 2026年Q1行业报告新增工具（程序员+学生科研部分）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Cursor', 'Cursor', '程序员', 'AI原生代码编辑器，基于VS Code构建，内置GPT-4级AI代码助手，支持Agent模式自主完成完整功能开发，2026年月活突破500万。', 'AI-native code editor built on VS Code with Agent mode for autonomous feature development, 5M MAU.', '$20/月', 4.9, 'https://cursor.sh', ARRAY['AI Agent自主编程','代码库全局理解','多文件同步编辑','自然语言生成代码'], true, true, true, 'cursor', 'AI代码编辑器', 'Cursor，2026年最受欢迎AI编程工具', ARRAY['Agent模式自主完成功能','代码库理解最深','VS Code生态兼容'], ARRAY['月费较高','需要适应新工作流'], '程序员必装，AI编程效率提升首选', ARRAY['热门','TG精选','2026新品'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Windsurf', 'Windsurf', '程序员', 'Codeium推出的AI代码编辑器，支持128K上下文窗口，Cascade功能可自主完成多步骤编程任务，与Cursor并列最强AI IDE。', 'Codeium AI code editor with 128K context, Cascade for multi-step autonomous coding tasks.', '$15/月', 4.8, 'https://codeium.com/windsurf', ARRAY['128K超长上下文','Cascade自主编程','多文件协同编辑','实时代码建议'], true, true, true, 'windsurf', 'AI IDE', 'Windsurf，与Cursor并列最强AI代码编辑器', ARRAY['上下文窗口超长','Cascade自主能力强','价格比Cursor低'], ARRAY['生态不如VS Code成熟','插件支持有限'], 'Cursor的最强竞品，性价比更高', ARRAY['热门','TG精选','2026新品'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('通义灵码2.0', '通义灵码2.0', '程序员', '阿里巴巴推出的AI编程助手2.0版，接入DeepSeek R2，中文代码注释和文档质量大幅提升，支持VS Code和JetBrains。', 'Alibaba AI coding assistant 2.0 with DeepSeek R2, improved Chinese code comments and documentation.', '免费+付费', 4.7, 'https://tongyi.aliyun.com/lingma', ARRAY['DeepSeek R2加持','中文注释质量高','VS Code/JetBrains支持','代码安全扫描'], true, true, true, 'tongyi-lingma', 'AI编程助手', '通义灵码2.0，国内程序员首选AI编程工具', ARRAY['中文支持最好','免费版功能丰富','阿里云生态整合'], ARRAY['英文场景不如Copilot','Agent能力较弱'], '国内程序员免费入门AI编程首选', ARRAY['热门','国产精品','2026新品'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Bolt.new', 'Bolt.new', '程序员', 'StackBlitz推出的AI全栈应用生成工具，在浏览器中直接生成、运行和部署完整Web应用，无需本地环境配置。', 'StackBlitz AI full-stack app generator that builds, runs and deploys complete web apps in browser.', '$20/月', 4.8, 'https://bolt.new', ARRAY['浏览器内全栈开发','一键生成完整应用','自动部署功能','无需本地环境'], true, true, true, 'bolt-new', 'AI全栈生成', 'Bolt.new，浏览器内一键生成完整Web应用', ARRAY['零配置即可使用','全栈生成能力强','部署极其简单'], ARRAY['复杂项目支持有限','月费较高'], '独立开发者快速验证产品想法必备', ARRAY['热门','TG精选','2026新品'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Devin 2.0', 'Devin 2.0', '程序员', 'Cognition推出的AI软件工程师2.0版，自主完成率提升至45%，能独立完成GitHub Issue修复、代码重构等复杂任务。', 'Cognition AI software engineer 2.0 with 45% autonomous completion rate for complex engineering tasks.', '$500/月', 4.6, 'https://cognition.ai', ARRAY['自主完成率45%','GitHub Issue自动修复','代码重构自动化','多步骤任务规划'], true, false, true, 'devin-2', 'AI软件工程师', 'Devin 2.0，最接近真实工程师的AI代理人', ARRAY['自主完成率业界最高','复杂任务处理能力强','持续学习进化'], ARRAY['价格极高','仍需人工监督'], '探索AI自主编程前沿的团队', ARRAY['TG精选','2026新品'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Perplexity Pro', 'Perplexity Pro', '学生', 'AI搜索引擎专业版，实时联网搜索并生成带引用来源的答案，学术研究效率提升15倍，2026年月活突破2000万。', 'AI search engine Pro with real-time web search and cited answers, 15x research efficiency, 20M MAU.', '$20/月', 4.9, 'https://www.perplexity.ai', ARRAY['实时联网搜索','答案带引用来源','学术论文检索','多轮深度追问'], true, true, false, 'perplexity-pro', 'AI学术搜索', 'Perplexity Pro，学术研究效率提升15倍', ARRAY['引用来源可验证','实时信息最新','深度追问能力强'], ARRAY['价格较高','中文内容相对较少'], '研究生和科研人员文献检索首选', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Elicit', 'Elicit', '学生', 'AI学术研究助手，专为科研人员设计，自动检索和分析学术论文，支持文献综述自动生成，引用准确率极高。', 'AI research assistant for academics, auto-searches and analyzes papers with high-accuracy citations.', '免费+$10/月', 4.8, 'https://elicit.com', ARRAY['学术论文自动检索','文献综述生成','研究问题提炼','引用准确性验证'], true, true, false, 'elicit', 'AI文献综述', 'Elicit，科研人员文献综述自动化神器', ARRAY['引用准确率极高','文献分析深度好','免费版可用'], ARRAY['主要支持英文文献','中文论文支持有限'], '博士生和科研人员文献综述必备', ARRAY['热门','TG精选'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Consensus', 'Consensus', '学生', 'AI学术搜索引擎，专门检索同行评审论文，自动提取研究结论和共识，2026年新增AI论文综述自动生成功能。', 'AI academic search engine for peer-reviewed papers with auto-extracted conclusions and consensus.', '免费+$9/月', 4.8, 'https://consensus.app', ARRAY['同行评审论文检索','研究共识提取','AI综述自动生成','研究结论对比'], true, true, true, 'consensus', 'AI学术共识', 'Consensus，快速找到学术研究共识的AI工具', ARRAY['专注同行评审质量高','共识提取准确','综述生成功能新'], ARRAY['主要英文文献','数据库不如Google Scholar全'], '需要快速了解某领域研究共识的学者', ARRAY['热门','TG精选','2026新品'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('秘塔AI搜索', '秘塔AI搜索', '学生', '国内领先的AI搜索引擎，无广告干扰，中文学术内容理解能力强，支持深度搜索模式，完全免费使用。', 'Leading Chinese AI search engine, ad-free with strong Chinese academic content understanding, free.', '免费', 4.7, 'https://metaso.cn', ARRAY['无广告AI搜索','中文学术内容优化','深度搜索模式','来源引用展示'], true, true, false, 'metaso', 'AI中文搜索', '秘塔AI搜索，国内最好用的免费AI搜索', ARRAY['完全免费无广告','中文理解最强','深度搜索质量高'], ARRAY['英文内容不如Perplexity','实时性稍弱'], '国内学生和研究者免费AI搜索首选', ARRAY['热门','国产精品','免费'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Scite AI', 'Scite AI', '学生', 'AI学术引用分析工具，独创Smart Citations技术，显示论文被引用时是支持还是反驳，帮助评估研究可靠性。', 'AI citation analysis with Smart Citations showing whether papers are supported or contradicted.', '$20/月', 4.6, 'https://scite.ai', ARRAY['Smart Citations引用分析','论文可靠性评估','研究影响力追踪','AI科研代理人'], true, false, false, 'scite-ai', 'AI引用分析', 'Scite AI，评估学术论文可靠性的利器', ARRAY['Smart Citations独创技术','可靠性评估准确','科研代理人功能新'], ARRAY['价格偏高','主要英文文献'], '需要评估文献质量的博士生和研究者', ARRAY['热门'], 4600, 'active');
