-- 学生分类（26-50）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Obsidian', 'Obsidian', '学生', '双向链接笔记工具，帮助学生构建个人知识图谱，AI插件辅助笔记整理和知识连接。', 'Bidirectional linking note tool for building personal knowledge graphs with AI plugins.', '免费+付费', 4.6, 'https://obsidian.md', ARRAY['双向链接笔记','知识图谱可视化','AI插件支持','本地数据存储'], true, false, false, 'obsidian-student', '知识图谱', '双向链接构建个人知识图谱工具', ARRAY['知识连接最强','本地存储安全','插件生态丰富'], ARRAY['学习成本较高','同步需付费'], '想构建系统知识体系的学生推荐', ARRAY['热门'], 2600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('RemNote', 'RemNote', '学生', '结合笔记和间隔重复的学习工具，在记笔记的同时自动生成闪卡，学习和复习一体化。', 'Combined note-taking and spaced repetition tool auto-generating flashcards while taking notes.', '免费+付费', 4.4, 'https://www.remnote.com', ARRAY['笔记自动生成闪卡','间隔重复复习','知识结构化整理','AI学习辅助'], true, false, false, 'remnote', '笔记闪卡', '记笔记同时自动生成闪卡工具', ARRAY['笔记和复习一体','间隔重复科学','知识结构清晰'], ARRAY['界面较为复杂','高级功能需付费'], '想把笔记和记忆结合的学生推荐', ARRAY['热门'], 2500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Readwise Reader', 'Readwise Reader', '学生', 'AI阅读管理工具，统一管理文章、论文、电子书和播客，AI生成摘要和高亮复习。', 'AI reading management tool unifying articles, papers, ebooks and podcasts with AI summaries.', '$7.99/月', 4.5, 'https://readwise.io/read', ARRAY['多格式内容统一管理','AI摘要生成','高亮内容复习','间隔重复回顾'], false, false, false, 'readwise-reader', 'AI阅读', 'AI统一管理阅读内容摘要复习', ARRAY['内容管理最统一','AI摘要实用','复习系统好'], ARRAY['价格偏高','主要面向英文'], '阅读量大的学生统一管理学习资料', ARRAY['热门'], 2400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Symbolab', 'Symbolab', '学生', 'AI数学解题工具，专注代数、微积分、三角函数，提供详细解题步骤和图形可视化。', 'AI math solver focused on algebra, calculus and trigonometry with detailed steps and graphs.', '免费+付费', 4.5, 'https://www.symbolab.com', ARRAY['代数微积分解题','图形可视化','逐步解题过程','练习题生成'], false, true, false, 'symbolab', 'AI数学', '代数微积分图形可视化解题工具', ARRAY['高等数学覆盖好','图形可视化强','步骤详细清晰'], ARRAY['查看步骤需付费','主要面向英文'], '大学数学课程解题的专业工具', ARRAY['热门'], 2300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('GeoGebra', 'GeoGebra', '学生', '免费数学可视化工具，支持几何、代数、统计和微积分的交互式图形，全球数学教育标准工具。', 'Free math visualization tool for interactive geometry, algebra, statistics and calculus graphs.', '免费', 4.6, 'https://www.geogebra.org', ARRAY['几何图形交互绘制','函数图像可视化','统计数据分析','3D图形支持'], true, false, false, 'geogebra', '数学可视化', '免费数学几何代数交互可视化工具', ARRAY['完全免费','可视化效果好','教育场景专业'], ARRAY['界面设计较老旧','高级功能需学习'], '数学和物理学习可视化的免费神器', ARRAY['免费','热门'], 2200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Desmos', 'Desmos', '学生', '在线图形计算器，实时绘制函数图像，支持动态参数调节，是数学学习和考试备考利器。', 'Online graphing calculator with real-time function plotting and dynamic parameter adjustment.', '免费', 4.7, 'https://www.desmos.com', ARRAY['实时函数图像绘制','动态参数调节','多函数叠加显示','考试允许使用'], true, true, false, 'desmos', '图形计算器', '实时绘制函数图像在线计算器', ARRAY['操作最简单直观','实时响应流畅','完全免费'], ARRAY['功能相对基础','高级统计有限'], '数学函数图像学习和考试的必备工具', ARRAY['免费','热门','TG精选'], 2100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('StudySmarter', 'StudySmarter', '学生', 'AI学习平台，自动将笔记转化为闪卡和测验，提供个性化学习计划和进度追踪。', 'AI study platform converting notes to flashcards and quizzes with personalized study plans.', '免费+付费', 4.4, 'https://www.studysmarter.de', ARRAY['笔记自动转闪卡','AI个性化学习计划','进度追踪分析','学习社区共享'], false, false, false, 'studysmarter', 'AI学习', 'AI笔记转闪卡个性化学习平台', ARRAY['笔记转换方便','学习计划个性化','社区资源丰富'], ARRAY['高级功能需付费','中文支持有限'], '想系统化备考的学生学习平台', ARRAY['热门'], 2000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Brainly', 'Brainly', '学生', 'AI学习社区，学生互相解答作业问题，AI辅助验证答案准确性，覆盖全球3.5亿学生。', 'AI learning community where students answer homework questions with AI answer verification.', '免费+付费', 4.3, 'https://brainly.com', ARRAY['学生互助问答社区','AI答案验证','多学科覆盖','多语言支持'], false, false, false, 'brainly', '学习社区', '全球学生互助AI验证答案社区', ARRAY['社区资源丰富','多语言支持好','免费版可用'], ARRAY['答案质量参差','高级功能需付费'], '作业遇到困难时找同学帮助的平台', ARRAY['热门'], 1900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('MindMeister', 'MindMeister', '学生', 'AI思维导图工具，帮助学生可视化知识结构、头脑风暴和整理学习内容，支持团队协作。', 'AI mind mapping tool for visualizing knowledge structures and brainstorming with team collaboration.', '免费+付费', 4.4, 'https://www.mindmeister.com', ARRAY['AI辅助思维导图','知识结构可视化','团队协作编辑','多格式导出'], false, false, false, 'mindmeister', 'AI思维导图', 'AI辅助知识结构可视化思维导图', ARRAY['思维导图功能强','协作编辑好','模板丰富'], ARRAY['免费版节点有限','高级功能需付费'], '整理学习内容和头脑风暴的工具', ARRAY['热门'], 1800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Research Rabbit', 'Research Rabbit', '学生', '免费学术论文发现工具，通过已知论文推荐相关研究，可视化论文关系网络，加速文献调研。', 'Free academic paper discovery tool recommending related research and visualizing paper networks.', '免费', 4.5, 'https://www.researchrabbit.ai', ARRAY['相关论文智能推荐','论文关系网络图','作者研究追踪','Zotero集成'], true, false, false, 'research-rabbit', '论文发现', '免费AI推荐相关学术论文工具', ARRAY['完全免费','推荐准确度高','可视化直观'], ARRAY['主要面向英文','功能相对单一'], '文献调研发现相关论文的免费工具', ARRAY['免费','热门'], 1700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Coursera AI', 'Coursera AI', '学生', '全球最大在线学习平台，AI个性化课程推荐，提供顶尖大学课程和职业证书，支持中文。', 'Largest online learning platform with AI course recommendations from top universities.', '免费+付费', 4.6, 'https://www.coursera.org', ARRAY['顶尖大学课程','AI个性化推荐','职业证书项目','中文字幕支持'], true, true, false, 'coursera-ai', '在线课程', '全球最大顶尖大学在线学习平台', ARRAY['课程质量最高','证书认可度高','中文支持好'], ARRAY['付费课程较贵','部分内容过时'], '想获得顶尖大学课程和证书的学生', ARRAY['热门','TG精选'], 1600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Chegg AI', 'Chegg AI', '学生', 'AI学习辅助平台，提供作业解答、教材解析和AI导师服务，覆盖大学各学科。', 'AI learning platform providing homework solutions, textbook explanations and AI tutoring.', '$15.95/月', 4.3, 'https://www.chegg.com', ARRAY['作业题目解答','教材习题解析','AI导师问答','学科专家辅导'], false, false, false, 'chegg-ai', 'AI辅导', 'AI作业解答教材解析学习平台', ARRAY['作业解答覆盖广','教材解析详细','响应速度快'], ARRAY['价格偏高','主要面向美国课程'], '大学作业遇到困难时的辅导工具', ARRAY['热门'], 1500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Turnitin AI', 'Turnitin AI', '学生', '学术诚信检测平台，检测论文抄袭和AI生成内容，帮助学生了解学术规范，被全球高校广泛使用。', 'Academic integrity platform detecting plagiarism and AI-generated content used by universities globally.', '机构订阅', 4.4, 'https://www.turnitin.com', ARRAY['抄袭相似度检测','AI生成内容识别','写作反馈建议','学术规范教育'], false, false, false, 'turnitin-ai', '查重检测', '全球高校学术诚信抄袭检测平台', ARRAY['检测最权威准确','高校广泛认可','AI检测领先'], ARRAY['需要机构订阅','学生无法直接购买'], '了解论文是否符合学术规范的工具', ARRAY['热门'], 1400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Miro AI', 'Miro AI', '学生', '在线协作白板工具，AI辅助头脑风暴、思维导图和项目规划，适合小组作业和项目协作。', 'Online collaborative whiteboard with AI for brainstorming, mind maps and project planning.', '免费+付费', 4.5, 'https://miro.com', ARRAY['在线协作白板','AI头脑风暴辅助','思维导图创建','小组项目规划'], false, true, false, 'miro-ai-student', 'AI白板', 'AI辅助在线协作白板头脑风暴', ARRAY['协作功能最强','AI辅助实用','模板丰富'], ARRAY['免费版有限制','功能复杂度高'], '小组作业和项目协作的在线白板', ARRAY['热门'], 1300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Semantic Scholar', 'Semantic Scholar', '学生', 'AI学术搜索引擎，免费搜索2亿+学术论文，AI提取关键信息和研究影响力分析。', 'AI academic search engine with 200M+ papers and AI key information extraction.', '免费', 4.5, 'https://www.semanticscholar.org', ARRAY['2亿+论文免费搜索','AI关键信息提取','研究影响力分析','引用关系追踪'], true, false, false, 'semantic-scholar', '学术搜索', 'AI免费搜索2亿学术论文引擎', ARRAY['完全免费','论文覆盖最广','AI提取实用'], ARRAY['主要面向英文','深度分析有限'], '免费搜索学术论文的权威工具', ARRAY['免费','热门'], 1200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Natural Reader', 'Natural Reader', '学生', 'AI文字转语音工具，将PDF、Word和网页内容朗读出来，帮助有阅读障碍或想边听边学的学生。', 'AI text-to-speech tool reading PDFs, Word docs and web pages for students with reading needs.', '免费+付费', 4.3, 'https://www.naturalreaders.com', ARRAY['PDF文档朗读','多种AI声音','浏览器插件','多语言支持'], false, false, false, 'natural-reader', 'AI朗读', 'PDF文档网页AI朗读工具', ARRAY['格式支持丰富','声音自然','浏览器集成好'], ARRAY['高级声音需付费','中文声音一般'], '需要听读学习材料的学生推荐', ARRAY['热门'], 1100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mendeley', 'Mendeley', '学生', 'Elsevier旗下免费文献管理工具，管理参考文献、PDF注释和学术社交网络，与Word深度集成。', 'Elsevier free reference manager with PDF annotation and Word integration for academics.', '免费', 4.4, 'https://www.mendeley.com', ARRAY['文献免费管理','PDF注释标注','Word引用插件','学术社交网络'], false, false, false, 'mendeley', '文献管理', 'Elsevier免费文献管理Word集成', ARRAY['完全免费','Word集成好','PDF注释方便'], ARRAY['云存储有限','界面较老旧'], '写论文管理参考文献的免费工具', ARRAY['免费','热门'], 1000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mem.ai', 'Mem.ai', '学生', 'AI笔记工具，自动组织和连接笔记内容，通过AI搜索快速找到相关知识，无需手动分类。', 'AI note tool automatically organizing and connecting notes with AI search without manual filing.', '免费+付费', 4.3, 'https://mem.ai', ARRAY['笔记自动组织','AI智能搜索','知识自动连接','无需手动分类'], false, false, false, 'mem-ai', 'AI笔记', 'AI自动组织连接笔记无需分类', ARRAY['自动组织省心','AI搜索准确','知识连接好'], ARRAY['高级功能需付费','功能仍在完善'], '不想手动整理笔记的学生推荐', ARRAY['热门'], 900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Beautiful.ai', 'Beautiful.ai', '学生', 'AI演示文稿设计工具，智能布局自动调整，让学生无需设计技能也能制作专业PPT。', 'AI presentation design tool with smart layout auto-adjustment for professional slides without design skills.', '免费+付费', 4.4, 'https://www.beautiful.ai', ARRAY['智能布局自动调整','专业模板库','AI内容建议','团队协作'], false, false, false, 'beautiful-ai', 'AI PPT', 'AI智能布局自动调整演示文稿', ARRAY['布局自动调整好','设计质量专业','操作简单'], ARRAY['高级功能需付费','自定义有限'], '想做专业PPT但没设计基础的学生', ARRAY['热门'], 800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Logseq', 'Logseq', '学生', '开源双向链接笔记工具，本地存储保护隐私，支持PDF注释和任务管理，完全免费。', 'Open-source bidirectional linking note tool with local storage, PDF annotation and task management.', '免费', 4.5, 'https://logseq.com', ARRAY['双向链接笔记','本地数据存储','PDF注释功能','任务管理集成'], false, false, false, 'logseq', '开源笔记', '开源本地存储双向链接笔记工具', ARRAY['完全开源免费','隐私保护强','功能全面'], ARRAY['界面学习成本高','同步需配置'], '注重隐私的学生构建知识库推荐', ARRAY['免费','热门'], 700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('edX AI', 'edX AI', '学生', 'MIT和哈佛联合创办的在线学习平台，提供顶尖大学课程和微学位，AI个性化学习路径。', 'MIT and Harvard online learning platform with top university courses and AI personalized paths.', '免费+付费', 4.5, 'https://www.edx.org', ARRAY['顶尖大学课程','微学位项目','AI学习路径','证书认证'], false, false, false, 'edx-ai', '在线课程', 'MIT哈佛顶尖大学在线学习平台', ARRAY['课程质量顶尖','证书认可度高','免费旁听可选'], ARRAY['证书需付费','部分课程较难'], '想学习顶尖大学课程的学生推荐', ARRAY['热门'], 600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Focusmate', 'Focusmate', '学生', '虚拟自习室工具，与全球学生视频配对共同专注学习，AI匹配学习伙伴，提升学习效率。', 'Virtual study room pairing students globally for focused co-working sessions with AI matching.', '免费+付费', 4.5, 'https://www.focusmate.com', ARRAY['虚拟自习室配对','全球学习伙伴','专注时间追踪','学习习惯养成'], false, false, false, 'focusmate', '虚拟自习', '全球学生虚拟自习室配对工具', ARRAY['自律效果显著','全球伙伴激励','免费版可用'], ARRAY['需要网络摄像头','时区差异影响'], '容易分心需要自律的学生推荐', ARRAY['热门'], 500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Notion Calendar', 'Notion Calendar', '学生', 'Notion推出的AI日历工具，整合课程表、作业截止日期和学习计划，帮助学生管理时间。', 'Notion AI calendar integrating class schedules, assignment deadlines and study plans.', '免费', 4.4, 'https://www.notion.so/product/calendar', ARRAY['课程表日历整合','作业截止提醒','学习计划管理','Notion笔记联动'], false, false, false, 'notion-calendar', 'AI日历', 'Notion课程表作业截止AI日历', ARRAY['与Notion无缝集成','时间管理直观','完全免费'], ARRAY['功能相对基础','需要Notion账号'], 'Notion用户管理学习时间的免费工具', ARRAY['免费'], 400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Claude AI', 'Claude AI', '学生', 'Anthropic推出的AI助手，擅长长文本分析、论文写作辅助和复杂问题推理，学术诚信意识强。', 'Anthropic AI assistant excelling at long text analysis, essay writing and complex reasoning.', '免费+付费', 4.7, 'https://claude.ai', ARRAY['长文本深度分析','论文写作辅助','复杂推理能力','学术诚信引导'], true, true, false, 'claude-ai-student', 'AI助手', 'Anthropic长文本分析论文写作AI', ARRAY['长文本理解最强','推理能力出色','学术诚信好'], ARRAY['免费版有限制','实时信息有限'], '写长篇论文和深度分析的学生首选', ARRAY['热门','TG精选'], 300, 'active');
