-- 营销分类（26-50）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mention AI', 'Mention AI', '营销', '品牌和竞品监听工具，实时追踪社交媒体、新闻和博客中的品牌提及，AI生成洞察报告。', 'Brand and competitor monitoring tool tracking mentions across social media and news.', '$41/月', 4.3, 'https://mention.com', ARRAY['品牌提及实时监听','竞品动态追踪','情感分析报告','危机预警提醒'], false, false, false, 'mention-ai', '品牌监听', '实时追踪品牌提及AI监听工具', ARRAY['监听覆盖面广','实时提醒及时','报告生成方便'], ARRAY['深度分析不如专业工具','免费版功能有限'], '中小品牌声誉监控的性价比工具', ARRAY['热门'], 2700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Loomly AI', 'Loomly AI', '营销', '社交媒体内容日历和发布工具，AI辅助内容创意生成，支持多平台统一管理和团队协作。', 'Social media content calendar with AI content ideas and multi-platform team collaboration.', '$32/月', 4.3, 'https://www.loomly.com', ARRAY['内容日历可视化','AI内容创意建议','多平台统一发布','团队协作审批'], false, false, false, 'loomly-ai', '内容日历', 'AI辅助社媒内容日历管理工具', ARRAY['内容日历直观清晰','团队协作流畅','AI创意建议实用'], ARRAY['AI功能相对基础','价格偏高'], '社媒内容团队日历管理推荐', ARRAY['热门'], 2600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Lately AI', 'Lately AI', '营销', 'AI内容再利用工具，将长篇内容（博客、播客、视频）自动拆解为多条社媒帖子，提升内容效率。', 'AI content repurposing tool converting long-form content into multiple social media posts.', '$49/月', 4.4, 'https://www.lately.ai', ARRAY['长内容自动拆解','社媒帖子批量生成','品牌声音学习','内容效果分析'], true, false, false, 'lately-ai', '内容复用', 'AI将长内容拆解为社媒帖子工具', ARRAY['内容复用效率极高','品牌声音学习好','批量生成省时'], ARRAY['生成内容需要审核','价格偏高'], '内容营销团队提升内容产出效率', ARRAY['热门'], 2500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Predis AI', 'Predis AI', '营销', 'AI社交媒体内容生成工具，输入关键词自动生成配图和文案，支持多平台格式一键发布。', 'AI social media content generator creating images and captions from keywords for all platforms.', '免费+付费', 4.3, 'https://predis.ai', ARRAY['关键词生成配图文案','多平台格式适配','内容日历管理','竞品内容分析'], false, true, false, 'predis-ai', 'AI社媒', '关键词一键生成社媒配图文案', ARRAY['图文一体生成方便','多平台格式自动','免费版可用'], ARRAY['图像质量一般','文案需要润色'], '个人和小团队社媒内容快速生产', ARRAY['免费','热门'], 2400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Taplio', 'Taplio', '营销', 'LinkedIn内容增长AI工具，帮助个人品牌和B2B营销人员生成LinkedIn帖子、分析数据和拓展人脉。', 'LinkedIn growth AI tool for personal branding and B2B marketers to create posts and grow network.', '$39/月', 4.4, 'https://taplio.com', ARRAY['LinkedIn帖子AI生成','个人品牌内容规划','数据分析洞察','人脉拓展辅助'], true, false, true, 'taplio', 'LinkedIn', 'LinkedIn个人品牌增长AI工具', ARRAY['LinkedIn场景针对','内容生成质量好','数据分析实用'], ARRAY['仅限LinkedIn平台','价格偏高'], 'B2B营销和个人品牌LinkedIn运营推荐', ARRAY['今日推荐'], 2300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Tweet Hunter', 'Tweet Hunter', '营销', 'Twitter/X内容增长AI工具，AI生成推文、安排发布时间、分析账号数据，帮助快速增长粉丝。', 'Twitter/X growth AI tool for tweet generation, scheduling and account analytics.', '$49/月', 4.3, 'https://tweethunter.io', ARRAY['推文AI生成','最佳时间自动发布','账号数据分析','病毒内容灵感'], false, false, false, 'tweet-hunter', 'Twitter增长', 'Twitter/X账号增长AI内容工具', ARRAY['推文生成质量好','数据分析实用','病毒内容灵感多'], ARRAY['仅限Twitter/X平台','价格偏高'], 'Twitter/X个人品牌和营销增长推荐', ARRAY['热门'], 2200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Flick AI', 'Flick AI', '营销', 'Instagram和TikTok内容AI工具，生成标签策略、内容创意和帖子文案，提升社媒自然增长。', 'Instagram and TikTok AI tool for hashtag strategy, content ideas and caption generation.', '$14/月', 4.3, 'https://www.flick.social', ARRAY['标签策略AI分析','内容创意生成','帖子文案撰写','账号增长分析'], false, false, false, 'flick-ai', '标签策略', 'Instagram/TikTok标签内容AI工具', ARRAY['标签策略分析准确','内容创意实用','价格亲民'], ARRAY['功能相对基础','主要面向英文市场'], 'Instagram和TikTok自然增长推荐', ARRAY['热门'], 2100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Vidyard AI', 'Vidyard AI', '营销', 'B2B视频营销AI平台，AI生成个性化销售视频脚本，支持视频录制、分发和观看数据分析。', 'B2B video marketing AI platform for personalized sales video scripts and analytics.', '免费+付费', 4.4, 'https://www.vidyard.com', ARRAY['个性化视频脚本生成','视频录制分发','观看行为分析','销售视频个性化'], false, false, false, 'vidyard-ai', 'AI视频', 'B2B销售个性化视频营销平台', ARRAY['B2B场景针对性强','个性化效果好','数据分析实用'], ARRAY['主要面向B2B销售','高级功能需付费'], 'B2B销售团队视频营销提效推荐', ARRAY['热门'], 2000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Synthesia', 'Synthesia', '营销', 'AI视频生成平台，输入文字脚本自动生成AI数字人讲解视频，支持120+语言，无需拍摄。', 'AI video platform generating digital human presenter videos from text scripts in 120+ languages.', '$22/月', 4.6, 'https://www.synthesia.io', ARRAY['AI数字人视频生成','120+语言支持','无需拍摄设备','品牌定制数字人'], true, true, false, 'synthesia', 'AI数字人', '文字脚本生成AI数字人讲解视频', ARRAY['视频生成效率极高','多语言支持出色','无需拍摄成本低'], ARRAY['数字人表情较僵硬','高级功能需付费'], '企业培训和营销视频低成本制作', ARRAY['热门','今日推荐'], 1900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Heygen', 'Heygen', '营销', 'AI视频生成工具，支持数字人视频、视频翻译配音和个性化营销视频批量生成，中文友好。', 'AI video tool for digital human videos, video translation and personalized marketing videos.', '免费+付费', 4.6, 'https://www.heygen.com', ARRAY['AI数字人视频','视频翻译配音','个性化视频批量','中文支持友好'], true, true, false, 'heygen', 'AI视频', 'AI数字人视频翻译营销视频工具', ARRAY['中文支持最好','视频翻译效果出色','批量生成高效'], ARRAY['免费版有水印','高质量生成较慢'], '中文营销视频和视频本地化首选', ARRAY['热门','TG精选'], 1800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Descript AI', 'Descript AI', '营销', 'AI音视频编辑工具，像编辑文档一样编辑视频，支持AI配音克隆、自动字幕和内容再利用。', 'AI audio/video editor that edits like a document with voice cloning and auto captions.', '免费+付费', 4.5, 'https://www.descript.com', ARRAY['文档式视频编辑','AI声音克隆','自动字幕生成','内容再利用工具'], true, true, false, 'descript-ai', 'AI视频编辑', '像编辑文档一样编辑视频AI工具', ARRAY['编辑方式革命性','声音克隆效果好','字幕生成准确'], ARRAY['高级功能需付费','大文件处理较慢'], '播客和视频内容创作者必备工具', ARRAY['热门','今日推荐'], 1700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Opus Clip', 'Opus Clip', '营销', 'AI长视频自动剪辑工具，将长视频自动识别精彩片段并剪辑为短视频，适合多平台内容分发。', 'AI long video auto-clipper identifying highlights and creating short clips for multi-platform.', '免费+付费', 4.5, 'https://www.opus.pro', ARRAY['长视频自动剪辑','精彩片段AI识别','多平台格式适配','字幕自动添加'], true, true, true, 'opus-clip', 'AI剪辑', 'AI自动将长视频剪辑为短视频', ARRAY['剪辑效率极高','精彩识别准确','多平台格式好'], ARRAY['免费版有水印','复杂内容识别有限'], '视频内容多平台分发的效率神器', ARRAY['热门','TG精选'], 1600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Captions AI', 'Captions AI', '营销', 'AI视频字幕和内容创作工具，自动生成字幕、翻译、AI眼神修正和视频内容优化。', 'AI video captions and content tool with auto subtitles, translation and eye contact correction.', '免费+付费', 4.4, 'https://www.captions.ai', ARRAY['自动字幕生成','多语言翻译','AI眼神修正','视频内容优化'], false, true, false, 'captions-ai', 'AI字幕', 'AI自动字幕翻译眼神修正工具', ARRAY['字幕生成准确','眼神修正独特','多语言支持好'], ARRAY['免费版功能有限','高级功能需付费'], '短视频创作者提升视频质量推荐', ARRAY['热门'], 1500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Podcastle AI', 'Podcastle AI', '营销', 'AI播客录制和编辑平台，支持远程录制、AI降噪、自动剪辑和文字转音频功能。', 'AI podcast recording and editing platform with remote recording, noise removal and auto editing.', '免费+付费', 4.4, 'https://podcastle.ai', ARRAY['远程多人录制','AI背景噪音消除','自动剪辑处理','文字转音频'], false, false, false, 'podcastle-ai', 'AI播客', 'AI播客录制编辑一体化平台', ARRAY['远程录制质量好','降噪效果出色','操作简单易用'], ARRAY['高级功能需付费','存储空间有限'], '播客创作者录制和编辑推荐', ARRAY['免费'], 1400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('ElevenLabs', 'ElevenLabs', '营销', 'AI语音合成平台，生成极度逼真的AI配音，支持声音克隆和多语言配音，广泛用于营销视频。', 'AI voice synthesis platform generating ultra-realistic voices with cloning and multilingual support.', '免费+付费', 4.7, 'https://elevenlabs.io', ARRAY['超逼真AI语音合成','声音克隆技术','多语言配音','API商业集成'], true, true, false, 'elevenlabs', 'AI配音', '业界最逼真的AI语音合成平台', ARRAY['语音质量业界最高','声音克隆效果出色','多语言支持好'], ARRAY['商用需付费授权','免费版有限制'], '营销视频和内容配音的首选工具', ARRAY['热门','TG精选'], 1300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Murf AI', 'Murf AI', '营销', 'AI文字转语音工具，提供120+逼真AI声音，支持多语言配音，适合营销视频和演示文稿配音。', 'AI text-to-speech with 120+ realistic voices for marketing videos and presentations.', '免费+付费', 4.4, 'https://murf.ai', ARRAY['120+逼真AI声音','多语言配音支持','视频配音同步','商用授权支持'], false, true, false, 'murf-ai', 'AI配音', '120+声音AI文字转语音配音工具', ARRAY['声音选择丰富','多语言支持好','商用授权清晰'], ARRAY['顶级声音需付费','免费版有水印'], '营销视频和课程内容配音推荐', ARRAY['热门'], 1200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Typeface AI', 'Typeface AI', '营销', '企业AI内容创作平台，学习品牌风格和受众偏好，生成符合品牌调性的营销内容，保障品牌一致性。', 'Enterprise AI content platform learning brand style to generate on-brand marketing content.', '企业定价', 4.4, 'https://www.typeface.ai', ARRAY['品牌风格AI学习','营销内容批量生成','品牌一致性保障','多渠道内容适配'], false, false, false, 'typeface-ai', '品牌内容', '企业品牌风格AI内容创作平台', ARRAY['品牌一致性最强','内容质量有保障','企业安全合规'], ARRAY['企业级定价较贵','实施需要时间'], '大型品牌内容营销规模化推荐', ARRAY['热门'], 1100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Anyword', 'Anyword', '营销', 'AI文案优化平台，预测文案转化率评分，帮助营销人员在发布前选择最高转化的文案版本。', 'AI copywriting platform predicting conversion scores to help choose highest-converting copy.', '$39/月', 4.4, 'https://anyword.com', ARRAY['文案转化率预测评分','多版本文案对比','广告文案优化','邮件主题行优化'], true, false, false, 'anyword', '转化预测', 'AI预测文案转化率评分优化工具', ARRAY['转化预测独特实用','多版本对比方便','营销场景覆盖广'], ARRAY['预测准确性有限','价格偏高'], '广告和邮件文案转化率优化推荐', ARRAY['热门'], 1000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Smartly.io', 'Smartly.io', '营销', '社交广告自动化平台，AI优化Facebook、Instagram、TikTok广告创意和投放，提升广告ROI。', 'Social advertising automation platform with AI creative optimization for Facebook and TikTok.', '企业定价', 4.5, 'https://www.smartly.io', ARRAY['广告创意AI优化','多平台广告自动化','预算智能分配','广告效果分析'], false, false, false, 'smartly-io', 'AI广告', '社交广告创意投放AI自动化平台', ARRAY['多平台广告自动化','创意优化效果好','ROI提升明显'], ARRAY['企业级定价较贵','主要面向大广告主'], '大型品牌社交广告自动化优化推荐', ARRAY['热门'], 900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Madgicx AI', 'Madgicx AI', '营销', 'Facebook和Instagram广告AI优化工具，自动分析广告数据、优化受众定向和预算分配。', 'Facebook and Instagram ad AI optimizer for audience targeting and budget allocation.', '$44/月', 4.3, 'https://madgicx.com', ARRAY['广告数据AI分析','受众定向优化','预算自动分配','广告创意测试'], false, false, false, 'madgicx-ai', 'FB广告', 'Facebook广告AI自动优化工具', ARRAY['FB广告优化效果好','受众分析准确','预算分配智能'], ARRAY['主要面向FB/IG广告','价格偏高'], 'Facebook广告投放效率提升推荐', ARRAY['热门'], 800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Clearscope', 'Clearscope', '营销', 'AI内容SEO优化工具，分析排名靠前内容的关键词使用，提供内容优化建议，提升搜索排名。', 'AI content SEO tool analyzing top-ranking content to provide optimization recommendations.', '$170/月', 4.5, 'https://www.clearscope.io', ARRAY['竞品内容关键词分析','内容优化评分','相关词推荐','内容大纲生成'], false, false, false, 'clearscope', 'SEO内容', 'AI分析竞品内容SEO优化工具', ARRAY['关键词分析深度好','优化建议精准','内容评分直观'], ARRAY['价格较高','主要面向英文内容'], '英文内容SEO优化的专业工具', ARRAY['热门'], 700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('MarketMuse', 'MarketMuse', '营销', 'AI内容策略和优化平台，分析内容差距、规划内容主题集群，帮助建立主题权威性提升SEO。', 'AI content strategy platform analyzing content gaps and planning topic clusters for SEO authority.', '$149/月', 4.4, 'https://www.marketmuse.com', ARRAY['内容差距AI分析','主题集群规划','内容优化建议','竞争难度评估'], false, false, false, 'marketmuse', '内容策略', 'AI内容差距分析主题集群规划', ARRAY['内容策略分析深度好','主题集群规划实用','SEO提升效果明显'], ARRAY['价格较高','学习成本较高'], '内容营销SEO策略规划的专业工具', ARRAY['热门'], 600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Frase.io', 'Frase.io', '营销', 'AI内容研究和写作工具，自动分析搜索意图、生成内容大纲，帮助快速创作SEO优化文章。', 'AI content research and writing tool analyzing search intent and generating SEO outlines.', '$14.99/月', 4.4, 'https://www.frase.io', ARRAY['搜索意图AI分析','内容大纲自动生成','SEO文章写作辅助','竞品内容对比'], true, false, false, 'frase-io', 'AI写作', 'AI搜索意图分析SEO文章写作', ARRAY['搜索意图分析准确','大纲生成实用','价格亲民'], ARRAY['深度写作需人工','主要面向英文内容'], 'SEO内容创作性价比最高的工具', ARRAY['热门','今日推荐'], 500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('GrowthBar', 'GrowthBar', '营销', 'AI SEO工具，专为内容营销人员设计，提供关键词研究、竞品分析和AI文章生成一体化功能。', 'AI SEO tool for content marketers with keyword research, competitor analysis and article generation.', '$29/月', 4.3, 'https://www.growthbarseo.com', ARRAY['关键词研究分析','竞品流量分析','AI文章一键生成','Chrome插件集成'], false, false, false, 'growthbar', 'AI SEO', '内容营销人员SEO研究写作工具', ARRAY['功能一体化方便','价格亲民','Chrome插件实用'], ARRAY['数据深度不如Ahrefs','AI文章质量一般'], '内容营销入门SEO工具的性价比选择', ARRAY['热门'], 400, 'active');
