-- 学生分类（1-25）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('ChatGPT', 'ChatGPT', '学生', 'OpenAI推出的AI对话助手，帮助学生解答学科问题、辅助写作、解释复杂概念，是最受学生欢迎的AI工具。', 'OpenAI AI assistant helping students with subject questions, writing and concept explanation.', '免费+付费', 4.8, 'https://chat.openai.com', ARRAY['学科问题解答','写作辅助润色','复杂概念解释','代码学习辅助'], true, true, false, 'chatgpt-student', 'AI助手', '学生最常用的AI学习对话助手', ARRAY['功能最全面','理解能力强','免费版可用'], ARRAY['信息可能过时','需要辨别准确性'], '学生学习和作业辅助的万能工具', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Khanmigo', 'Khanmigo', '学生', 'Khan Academy推出的AI学习导师，以苏格拉底式提问引导学生思考，不直接给答案而是帮助理解。', 'Khan Academy AI tutor using Socratic method to guide student thinking without giving direct answers.', '$4/月', 4.6, 'https://www.khanacademy.org/khan-labs', ARRAY['苏格拉底式引导学习','数学逐步解题','写作辅导反馈','学习进度追踪'], true, true, false, 'khanmigo', 'AI导师', 'Khan Academy苏格拉底式AI学习导师', ARRAY['教学方式最科学','引导思考不给答案','覆盖学科广'], ARRAY['价格偏高','主要面向英文'], '真正想学懂知识而非抄答案的学生', ARRAY['热门','今日推荐'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Grammarly', 'Grammarly', '学生', 'AI写作辅助工具，实时检查语法错误、提升写作表达，帮助学生提交更高质量的英文作业。', 'AI writing assistant checking grammar and improving expression for better English assignments.', '免费+付费', 4.7, 'https://www.grammarly.com', ARRAY['语法错误实时检查','写作风格改进','抄袭检测功能','浏览器插件集成'], true, true, false, 'grammarly-student', 'AI写作', '学生英文写作语法检查AI助手', ARRAY['语法检查最准确','写作建议实用','浏览器集成好'], ARRAY['高级功能需付费','主要面向英文'], '英文写作必备的AI语法检查工具', ARRAY['热门','TG精选'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Notion AI', 'Notion AI', '学生', 'Notion内置AI助手，帮助学生整理笔记、生成学习计划、总结课堂内容和辅助论文写作。', 'Notion built-in AI for organizing notes, study plans, class summaries and essay writing.', '$10/月', 4.6, 'https://www.notion.so/product/ai', ARRAY['笔记AI整理总结','学习计划生成','课堂内容总结','论文写作辅助'], true, true, false, 'notion-ai-student', 'AI笔记', 'Notion内置AI学习笔记管理助手', ARRAY['笔记管理最强','AI总结实用','学习计划好'], ARRAY['需要Notion订阅','学习成本较高'], '用Notion管理学习的学生必备AI', ARRAY['热门'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Quizlet AI', 'Quizlet AI', '学生', '全球最受欢迎的学习卡片工具，AI自动生成闪卡和测验，帮助学生高效记忆和备考。', 'Most popular flashcard tool with AI generating flashcards and quizzes for efficient memorization.', '免费+付费', 4.6, 'https://quizlet.com', ARRAY['AI自动生成闪卡','智能测验练习','学习进度追踪','多种学习模式'], true, true, false, 'quizlet-ai', 'AI闪卡', '全球最受欢迎AI闪卡学习工具', ARRAY['闪卡生成最方便','学习模式多样','社区资源丰富'], ARRAY['高级功能需付费','部分内容需验证'], '备考和记忆知识点的高效学习工具', ARRAY['热门','TG精选'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Photomath', 'Photomath', '学生', '拍照解数学题AI工具，用手机拍摄数学题后自动识别并给出逐步解题过程，支持各类数学题型。', 'Math solving AI app photographing problems and providing step-by-step solutions.', '免费+付费', 4.7, 'https://photomath.com', ARRAY['拍照识别数学题','逐步解题过程','多种题型支持','解题方法解释'], true, true, false, 'photomath', 'AI数学', '拍照解数学题逐步解析AI工具', ARRAY['识别准确率高','解题步骤清晰','操作极简单'], ARRAY['高级功能需付费','复杂题型有限'], '数学作业遇到困难时的救星工具', ARRAY['热门','今日推荐'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Wolfram Alpha', 'Wolfram Alpha', '学生', '计算知识引擎，能解答数学、物理、化学等理科问题，给出精确计算结果和详细解题步骤。', 'Computational knowledge engine solving math, physics and chemistry with precise calculations.', '免费+付费', 4.6, 'https://www.wolframalpha.com', ARRAY['数学精确计算','物理化学解题','数据可视化','逐步解题过程'], true, false, false, 'wolfram-alpha', '计算引擎', '理科问题精确计算知识引擎', ARRAY['计算精度最高','理科覆盖全面','解题步骤详细'], ARRAY['高级功能需付费','人文学科较弱'], '理工科学生解题计算的权威工具', ARRAY['热门'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Duolingo AI', 'Duolingo AI', '学生', '全球最受欢迎的语言学习应用，AI个性化学习路径，游戏化设计让语言学习更有趣持久。', 'Most popular language learning app with AI personalized paths and gamified design.', '免费+付费', 4.7, 'https://www.duolingo.com', ARRAY['AI个性化学习路径','游戏化学习设计','40+语言支持','口语发音练习'], true, true, false, 'duolingo-ai', 'AI语言', '全球最受欢迎AI游戏化语言学习', ARRAY['游戏化体验最好','坚持学习效果好','免费版够用'], ARRAY['深度学习需付费','口语练习有限'], '想坚持学外语的学生首选工具', ARRAY['热门','TG精选'], 4300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Otter.ai', 'Otter.ai', '学生', 'AI课堂录音转文字工具，实时转录课堂讲座，自动生成摘要和关键词，方便课后复习。', 'AI lecture transcription tool with real-time transcription, summaries and keyword extraction.', '免费+付费', 4.5, 'https://otter.ai', ARRAY['课堂实时转录','自动摘要生成','关键词提取','多人发言识别'], true, true, false, 'otter-ai-student', 'AI转录', '课堂讲座AI实时转录摘要工具', ARRAY['转录准确率高','摘要生成实用','多人识别好'], ARRAY['免费版有时长限制','中文支持一般'], '不想漏记课堂内容的学生必备', ARRAY['热门'], 4200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Perplexity AI', 'Perplexity AI', '学生', 'AI搜索引擎，回答学术问题时提供带引用来源的答案，比Google更适合学术研究和论文写作。', 'AI search engine providing cited answers for academic questions, better than Google for research.', '免费+付费', 4.6, 'https://www.perplexity.ai', ARRAY['学术问题AI搜索','引用来源标注','实时信息检索','深度研究模式'], true, true, false, 'perplexity-student', 'AI搜索', '学术研究带引用来源AI搜索引擎', ARRAY['来源引用可信','信息最新实时','学术场景好'], ARRAY['深度分析需付费','来源需自行验证'], '写论文找资料的学生必备搜索工具', ARRAY['热门','今日推荐'], 4100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Consensus', 'Consensus', '学生', 'AI学术论文搜索引擎，专门搜索同行评审论文，用AI总结研究结论，帮助学生快速了解学术共识。', 'AI academic paper search engine summarizing peer-reviewed research conclusions.', '免费+付费', 4.5, 'https://consensus.app', ARRAY['同行评审论文搜索','研究结论AI总结','学术共识提取','引用格式生成'], true, false, false, 'consensus', '学术搜索', 'AI搜索同行评审论文总结结论', ARRAY['学术可信度高','结论总结准确','引用格式方便'], ARRAY['高级功能需付费','主要面向英文'], '写学术论文找权威来源的必备工具', ARRAY['热门'], 4000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Elicit', 'Elicit', '学生', 'AI研究助手，自动搜索和总结学术论文，提取关键数据和方法论，加速文献综述写作。', 'AI research assistant automatically searching and summarizing academic papers for literature reviews.', '免费+付费', 4.4, 'https://elicit.com', ARRAY['学术论文自动搜索','关键数据提取','文献综述辅助','研究方法总结'], true, false, false, 'elicit', '文献综述', 'AI自动搜索总结学术论文工具', ARRAY['文献综述效率高','数据提取准确','研究方法清晰'], ARRAY['高级功能需付费','主要面向英文'], '写文献综述的研究生必备工具', ARRAY['热门'], 3900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Anki AI', 'Anki AI', '学生', '间隔重复记忆软件，AI优化复习时间间隔，帮助学生高效记忆大量知识点，医学生和语言学习者最爱。', 'Spaced repetition memory software with AI-optimized review intervals for efficient memorization.', '免费', 4.7, 'https://apps.ankiweb.net', ARRAY['间隔重复算法','AI复习时间优化','自定义卡片制作','多平台同步'], true, true, false, 'anki-ai', '间隔记忆', '间隔重复AI优化记忆效率工具', ARRAY['记忆效率科学最高','完全免费','社区卡片丰富'], ARRAY['界面设计较老旧','学习成本较高'], '医学生和语言学习者的记忆神器', ARRAY['免费','热门','TG精选'], 3800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Gamma.app', 'Gamma.app', '学生', 'AI演示文稿生成工具，输入主题自动生成精美PPT，适合学生快速制作课堂展示和项目汇报。', 'AI presentation generator creating beautiful slides from topic input for class presentations.', '免费+付费', 4.5, 'https://gamma.app', ARRAY['主题自动生成PPT','精美模板设计','AI内容填充','一键导出分享'], true, true, false, 'gamma-app', 'AI PPT', '输入主题自动生成精美演示文稿', ARRAY['PPT生成速度极快','设计质量高','操作极简单'], ARRAY['高级功能需付费','自定义有限'], '快速制作课堂展示PPT的学生首选', ARRAY['热门','今日推荐'], 3700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Speechify', 'Speechify', '学生', 'AI文字转语音工具，将教材、论文和网页内容转为音频，支持4.5倍速收听，提升阅读效率。', 'AI text-to-speech tool converting textbooks and papers to audio at up to 4.5x speed.', '免费+付费', 4.5, 'https://speechify.com', ARRAY['文字转语音朗读','4.5倍速收听','多格式文件支持','AI声音自然逼真'], false, true, false, 'speechify', 'AI朗读', '教材论文转音频4.5倍速收听', ARRAY['朗读速度可调','声音自然逼真','多格式支持好'], ARRAY['高级功能需付费','中文支持一般'], '阅读量大的学生提升效率的工具', ARRAY['热门'], 3600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Explainpaper', 'Explainpaper', '学生', 'AI学术论文解读工具，上传论文后可以对任意段落提问，AI用简单语言解释复杂学术内容。', 'AI academic paper explainer allowing questions on any paragraph with simple language explanations.', '免费+付费', 4.4, 'https://www.explainpaper.com', ARRAY['论文段落AI解释','复杂概念简化','专业术语解读','多轮对话追问'], true, false, false, 'explainpaper', '论文解读', 'AI用简单语言解释复杂学术论文', ARRAY['复杂内容解释清晰','交互式追问好','学习效果好'], ARRAY['高级功能需付费','主要面向英文'], '读不懂英文论文的学生必备工具', ARRAY['热门'], 3500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Zotero', 'Zotero', '学生', '免费开源的文献管理工具，AI辅助整理参考文献，自动生成引用格式，是学术写作必备工具。', 'Free open-source reference manager with AI assistance for citations and bibliography generation.', '免费', 4.6, 'https://www.zotero.org', ARRAY['文献自动收集整理','引用格式自动生成','PDF注释管理','团队文献共享'], true, false, false, 'zotero', '文献管理', '免费开源学术文献管理引用工具', ARRAY['完全免费开源','引用格式最全','PDF管理好'], ARRAY['界面设计较老旧','云存储有限'], '写学术论文管理参考文献必备', ARRAY['免费','热门'], 3400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Scite.ai', 'Scite.ai', '学生', 'AI学术引用分析工具，显示论文被引用时是被支持还是被反驳，帮助评估研究可信度。', 'AI citation analysis tool showing whether papers are supported or contradicted when cited.', '免费+付费', 4.4, 'https://scite.ai', ARRAY['引用支持反驳分析','论文可信度评估','学术影响力追踪','文献综述辅助'], false, false, false, 'scite-ai', '引用分析', 'AI分析论文引用支持反驳关系', ARRAY['引用分析独特','可信度评估好','学术价值高'], ARRAY['高级功能需付费','主要面向英文'], '评估学术论文可信度的专业工具', ARRAY['热门'], 3300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Connected Papers', 'Connected Papers', '学生', 'AI学术论文关系可视化工具，以图谱形式展示论文之间的引用关系，帮助发现相关研究。', 'AI academic paper relationship visualization showing citation networks to discover related research.', '免费+付费', 4.4, 'https://www.connectedpapers.com', ARRAY['论文关系图谱可视化','相关研究发现','引用网络分析','研究领域探索'], false, false, false, 'connected-papers', '论文图谱', 'AI可视化论文引用关系图谱工具', ARRAY['可视化效果直观','相关研究发现好','操作简单'], ARRAY['免费版有限制','主要面向英文'], '文献调研发现相关论文的高效工具', ARRAY['热门'], 3200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Socratic by Google', 'Socratic by Google', '学生', 'Google推出的学习辅助App，拍照上传作业题目，AI解释解题思路，覆盖数学、科学、历史等学科。', 'Google learning app photographing homework for AI explanations across math, science and history.', '免费', 4.5, 'https://socratic.org', ARRAY['拍照识别作业题目','多学科解题解释','视频资源推荐','完全免费使用'], true, false, false, 'socratic-google', 'AI作业', 'Google拍照识别作业AI解题工具', ARRAY['完全免费','Google品质','多学科覆盖'], ARRAY['主要面向英文','深度解析有限'], '中学生作业遇到困难时的免费工具', ARRAY['免费','热门'], 3100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mathway', 'Mathway', '学生', 'AI数学解题工具，覆盖基础数学到微积分、线性代数，输入题目即给出答案和解题步骤。', 'AI math solver covering basic math to calculus and linear algebra with step-by-step solutions.', '免费+付费', 4.5, 'https://www.mathway.com', ARRAY['多层次数学解题','逐步解题过程','多种输入方式','图形计算器'], false, true, false, 'mathway', 'AI数学', '基础到高等数学AI逐步解题工具', ARRAY['数学覆盖范围广','解题步骤清晰','输入方式多样'], ARRAY['查看步骤需付费','不解释原理'], '数学作业从初中到大学的解题工具', ARRAY['热门'], 3000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Tome AI', 'Tome AI', '学生', 'AI演示文稿和故事叙述工具，通过对话生成精美幻灯片，适合学生制作创意项目展示。', 'AI presentation and storytelling tool generating beautiful slides through conversation.', '免费+付费', 4.4, 'https://tome.app', ARRAY['对话生成幻灯片','AI内容自动填充','精美视觉设计','一键分享发布'], false, false, false, 'tome-ai', 'AI演示', '对话生成精美幻灯片演示工具', ARRAY['设计风格现代','对话交互好','分享方便'], ARRAY['高级功能需付费','自定义有限'], '制作创意项目展示的学生推荐', ARRAY['热门'], 2900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Canva AI', 'Canva AI', '学生', 'Canva内置AI设计功能，帮助学生快速制作海报、信息图表和演示文稿，无需设计基础。', 'Canva built-in AI design for students to create posters, infographics and presentations easily.', '免费+付费', 4.6, 'https://www.canva.com', ARRAY['AI图像生成','海报模板设计','信息图表制作','演示文稿创建'], true, true, false, 'canva-ai-student', 'AI设计', 'Canva内置AI学生设计创作工具', ARRAY['模板资源最丰富','操作极简单','免费版够用'], ARRAY['高级功能需付费','原创性有限'], '没有设计基础的学生制作视觉内容', ARRAY['免费','热门'], 2800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('QuillBot', 'QuillBot', '学生', 'AI改写和润色工具，帮助学生改写句子、提升写作表达，内置语法检查和摘要生成功能。', 'AI paraphrasing and polishing tool helping students rewrite sentences and improve writing.', '免费+付费', 4.5, 'https://quillbot.com', ARRAY['句子AI改写润色','多种改写风格','语法检查','文章摘要生成'], false, true, false, 'quillbot', 'AI改写', 'AI改写润色提升写作表达工具', ARRAY['改写质量好','风格选择多','免费版可用'], ARRAY['高级功能需付费','过度依赖影响写作'], '英文写作需要润色改写的学生工具', ARRAY['热门'], 2700, 'active');
