-- 程序员分类（26-50）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Aider', 'Aider', '程序员', 'AI结对编程命令行工具，在终端中与GPT-4/Claude对话修改代码，自动提交Git变更。', 'AI pair programming CLI tool for editing code with GPT-4/Claude and auto Git commits.', '免费', 4.5, 'https://aider.chat', ARRAY['终端AI结对编程','自动Git提交','多文件同时编辑','多模型支持'], true, false, false, 'aider', 'AI结对', '终端AI结对编程自动Git提交工具', ARRAY['开源完全免费','Git集成自动','多文件编辑强'], ARRAY['需要命令行熟悉','配置有一定门槛'], '喜欢命令行的开发者AI编程利器', ARRAY['免费','热门'], 2500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Modal', 'Modal', '程序员', '云端Python函数运行平台，一行代码将本地函数部署到云端GPU，适合AI模型训练和推理。', 'Cloud Python function platform deploying local functions to GPU with one line of code.', '按用量付费', 4.5, 'https://modal.com', ARRAY['一行代码云端部署','GPU按需使用','Python原生体验','AI训练推理优化'], false, true, false, 'modal', '云端GPU', '一行代码部署Python函数到云端GPU', ARRAY['部署极简单','GPU按量付费','Python体验好'], ARRAY['主要面向Python','成本随规模增加'], 'AI模型训练和推理的最简云端方案', ARRAY['热门'], 2400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Supabase AI', 'Supabase AI', '程序员', 'Supabase内置AI功能，SQL编辑器AI辅助、向量数据库支持和Edge Functions AI集成。', 'Supabase built-in AI with SQL editor assistance, vector database and Edge Functions.', '免费+付费', 4.6, 'https://supabase.com', ARRAY['SQL AI辅助编写','向量数据库pgvector','Edge Functions','AI应用快速构建'], true, true, false, 'supabase-ai', 'AI数据库', 'Supabase内置AI向量数据库平台', ARRAY['全栈开发最快','向量搜索内置','免费版够用'], ARRAY['高级功能需付费','大规模需优化'], '全栈AI应用开发的最快后端方案', ARRAY['热门','TG精选'], 2300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('LlamaIndex', 'LlamaIndex', '程序员', 'RAG应用开发框架，专注于将私有数据与LLM连接，构建知识库问答和文档检索应用。', 'RAG application framework connecting private data with LLMs for knowledge base Q&A.', '免费', 4.5, 'https://www.llamaindex.ai', ARRAY['RAG应用构建','私有数据连接','文档索引检索','多数据源支持'], true, false, false, 'llamaindex', 'RAG框架', '构建RAG知识库问答的专业框架', ARRAY['RAG能力最专业','数据连接丰富','文档完善'], ARRAY['学习曲线较陡','版本更新频繁'], '构建企业知识库AI问答的首选框架', ARRAY['热门'], 2200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('v0 by Vercel', 'v0 by Vercel', '程序员', 'Vercel推出的AI UI生成工具，通过文字描述生成React组件代码，支持shadcn/ui和Tailwind。', 'Vercel AI UI generator creating React components from text with shadcn/ui and Tailwind.', '免费+付费', 4.6, 'https://v0.dev', ARRAY['文字生成React组件','shadcn/ui集成','Tailwind CSS支持','代码直接可用'], true, true, true, 'v0-vercel', 'AI UI生成', '文字描述生成React组件代码', ARRAY['UI生成质量高','代码直接可用','现代技术栈'], ARRAY['免费额度有限','复杂UI需调整'], '前端开发者快速生成UI组件的利器', ARRAY['热门','今日推荐'], 2100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Bolt.new', 'Bolt.new', '程序员', 'StackBlitz推出的AI全栈应用生成工具，在浏览器中通过对话生成并运行完整Web应用。', 'StackBlitz AI full-stack app generator building and running complete web apps in browser.', '免费+付费', 4.5, 'https://bolt.new', ARRAY['全栈应用AI生成','浏览器内运行','对话式开发','一键部署'], true, true, true, 'bolt-new', 'AI全栈', '浏览器内对话生成完整全栈应用', ARRAY['全栈生成能力强','无需本地环境','部署极简单'], ARRAY['免费额度有限','复杂应用需调整'], '快速原型验证想法的AI全栈工具', ARRAY['热门','TG精选'], 2000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Lovable', 'Lovable', '程序员', 'AI全栈应用构建平台，通过自然语言对话生成完整Web应用，集成Supabase后端和Stripe支付。', 'AI full-stack app builder generating complete web apps with Supabase and Stripe integration.', '免费+付费', 4.5, 'https://lovable.dev', ARRAY['自然语言生成应用','Supabase后端集成','Stripe支付集成','GitHub代码同步'], true, true, true, 'lovable', 'AI建站', '自然语言生成完整全栈Web应用', ARRAY['全栈集成最完整','后端自动配置','支付集成方便'], ARRAY['免费额度有限','复杂逻辑需手动'], '非技术创始人快速构建MVP的工具', ARRAY['热门','今日推荐'], 1900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Devin AI', 'Devin AI', '程序员', '首个AI软件工程师，能自主完成完整编程任务，包括规划、编码、测试和部署全流程。', 'First AI software engineer autonomously completing full programming tasks from planning to deployment.', '企业定价', 4.3, 'https://devin.ai', ARRAY['自主完成编程任务','全流程规划执行','代码测试调试','自动部署发布'], false, true, false, 'devin-ai', 'AI工程师', '首个自主完成编程任务的AI工程师', ARRAY['自主能力最强','任务完成度高','减少人工干预'], ARRAY['价格极高','复杂任务仍需监督'], '探索AI自主编程能力的前沿工具', ARRAY['热门'], 1800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Sweep AI', 'Sweep AI', '程序员', 'AI GitHub助手，将Issue自动转化为Pull Request，自动修复Bug和实现小功能。', 'AI GitHub assistant converting issues to pull requests and automatically fixing bugs.', '免费+付费', 4.3, 'https://sweep.dev', ARRAY['Issue转PR自动化','Bug自动修复','小功能自动实现','代码审查辅助'], false, false, false, 'sweep-ai', 'AI PR', 'Issue自动转Pull Request的AI工具', ARRAY['Issue转PR自动','减少重复工作','GitHub集成好'], ARRAY['复杂任务成功率低','需要人工审核'], '减少简单编程任务重复工作的工具', ARRAY['热门'], 1700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Cline', 'Cline', '程序员', '开源AI编程代理VSCode插件，能自主执行复杂编程任务，支持文件操作、终端命令和浏览器控制。', 'Open-source AI coding agent VSCode extension for autonomous complex tasks with file and terminal access.', '免费', 4.6, 'https://github.com/cline/cline', ARRAY['自主执行编程任务','文件系统操作','终端命令执行','浏览器控制'], true, true, true, 'cline', 'AI代理', '开源AI编程代理VSCode插件', ARRAY['开源完全免费','自主能力强','VSCode集成好'], ARRAY['需要自备API Key','复杂任务需监督'], '开源最强AI编程代理VSCode插件', ARRAY['免费','热门','TG精选'], 1600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Perplexity AI', 'Perplexity AI', '程序员', 'AI搜索引擎，实时搜索最新技术文档和Stack Overflow答案，给出带引用来源的技术解答。', 'AI search engine with real-time technical docs and Stack Overflow search with cited sources.', '免费+付费', 4.6, 'https://www.perplexity.ai', ARRAY['实时网络搜索','引用来源标注','技术问题解答','多模型切换'], false, true, false, 'perplexity-ai', 'AI搜索', '实时搜索带引用来源的AI搜索引擎', ARRAY['信息最新实时','来源引用可信','技术问题准确'], ARRAY['深度分析不如专业工具','高级功能需付费'], '获取最新技术信息的AI搜索工具', ARRAY['热门'], 1500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Railway', 'Railway', '程序员', '现代应用部署平台，AI辅助配置检测，一键部署各类应用，自动处理基础设施配置。', 'Modern app deployment platform with AI config detection and one-click deployment.', '免费+付费', 4.5, 'https://railway.app', ARRAY['一键应用部署','AI配置自动检测','多语言框架支持','数据库一键创建'], false, true, false, 'railway', 'AI部署', '一键部署AI配置检测现代平台', ARRAY['部署极简单','配置自动检测','价格亲民'], ARRAY['高级功能需付费','大流量成本增加'], '快速部署应用的现代化平台', ARRAY['热门'], 1400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Render', 'Render', '程序员', '云应用托管平台，自动部署GitHub代码，支持Web服务、数据库和定时任务，操作简单。', 'Cloud hosting platform auto-deploying GitHub code for web services, databases and cron jobs.', '免费+付费', 4.4, 'https://render.com', ARRAY['GitHub自动部署','Web服务托管','PostgreSQL数据库','定时任务支持'], false, false, false, 'render', '云托管', 'GitHub自动部署云应用托管平台', ARRAY['部署流程简单','免费版可用','数据库集成好'], ARRAY['免费版有限制','冷启动较慢'], '个人项目和小团队应用托管推荐', ARRAY['免费','热门'], 1300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Grafana AI', 'Grafana AI', '程序员', '可观测性平台Grafana内置AI功能，自然语言查询指标、自动生成告警规则和异常检测。', 'Grafana observability platform with AI for natural language metric queries and anomaly detection.', '免费+付费', 4.5, 'https://grafana.com', ARRAY['自然语言查询指标','告警规则自动生成','异常自动检测','仪表盘AI生成'], false, false, false, 'grafana-ai', 'AI监控', 'Grafana自然语言查询指标AI功能', ARRAY['可视化最强大','自然语言查询好','开源版可用'], ARRAY['配置复杂度高','高级功能需付费'], '系统监控可视化的行业标准工具', ARRAY['热门'], 1200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Swimm', 'Swimm', '程序员', 'AI代码文档工具，将文档与代码绑定，代码变更时自动更新文档，解决文档过时问题。', 'AI code documentation tool binding docs to code and auto-updating when code changes.', '免费+付费', 4.3, 'https://swimm.io', ARRAY['文档与代码绑定','代码变更自动更新','团队知识共享','新人快速上手'], false, false, false, 'swimm', '代码文档', 'AI代码文档与代码绑定自动更新', ARRAY['文档不过时问题解决','团队知识传承好','新人上手快'], ARRAY['需要团队配合','价格偏高'], '解决代码文档过时问题的专业工具', ARRAY['热门'], 1100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Blackbox AI', 'Blackbox AI', '程序员', 'AI代码搜索和补全工具，支持从视频、图片中提取代码，以及实时代码补全和问答。', 'AI code search and completion tool extracting code from videos and images with real-time completion.', '免费+付费', 4.3, 'https://www.useblackbox.io', ARRAY['视频图片代码提取','实时代码补全','代码问答搜索','多语言支持'], false, false, false, 'blackbox-ai', 'AI代码', '从视频图片提取代码的AI工具', ARRAY['代码提取独特实用','补全速度快','免费版可用'], ARRAY['补全质量一般','功能深度有限'], '从教程视频提取代码的独特工具', ARRAY['免费'], 1000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Codacy AI', 'Codacy AI', '程序员', 'AI代码质量平台，自动化代码审查、安全分析和技术债务管理，集成GitHub/GitLab工作流。', 'AI code quality platform automating code review, security analysis and tech debt management.', '免费+付费', 4.3, 'https://www.codacy.com', ARRAY['自动化代码审查','安全漏洞分析','技术债务追踪','PR自动评论'], false, false, false, 'codacy-ai', '代码审查', 'AI自动化代码审查质量分析平台', ARRAY['代码审查自动化','安全分析全面','PR集成方便'], ARRAY['误报率偶有偏高','高级功能需付费'], '团队代码质量自动化审查推荐', ARRAY['热门'], 900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('CodeRabbit', 'CodeRabbit', '程序员', 'AI代码审查工具，自动分析Pull Request，提供详细的代码改进建议和安全问题提示。', 'AI code review tool automatically analyzing pull requests with improvement suggestions.', '免费+付费', 4.5, 'https://coderabbit.ai', ARRAY['PR自动AI审查','代码改进建议','安全问题检测','多语言支持'], true, false, true, 'coderabbit', 'AI审查', 'AI自动分析PR提供代码改进建议', ARRAY['PR审查质量高','建议具体实用','集成简单'], ARRAY['免费版有限制','复杂逻辑理解有限'], '提升代码审查效率的AI工具', ARRAY['热门','今日推荐'], 800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Stenography', 'Stenography', '程序员', 'AI代码自动注释工具，分析代码逻辑后自动生成清晰的代码注释和文档字符串。', 'AI code auto-commenting tool analyzing code logic to generate clear comments and docstrings.', '免费+付费', 4.2, 'https://stenography.dev', ARRAY['代码自动注释生成','文档字符串生成','多语言支持','IDE插件集成'], false, false, false, 'stenography', 'AI注释', 'AI自动分析代码生成注释工具', ARRAY['注释生成准确','多语言支持好','节省时间'], ARRAY['注释质量参差','高级功能需付费'], '懒得写注释的开发者效率工具', ARRAY['热门'], 700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Mutable AI', 'Mutable AI', '程序员', 'AI加速软件开发平台，提供代码补全、重构建议和代码库问答，支持私有代码库训练。', 'AI software development acceleration with code completion, refactoring and codebase Q&A.', '免费+付费', 4.2, 'https://mutable.ai', ARRAY['代码补全加速','重构建议生成','代码库问答','私有代码库训练'], false, false, false, 'mutable-ai', 'AI重构', 'AI代码补全重构私有代码库训练', ARRAY['私有训练安全','重构建议实用','代码库问答好'], ARRAY['功能深度有限','价格偏高'], '需要私有代码库训练的团队推荐', ARRAY['热门'], 600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Cursor Rules', 'Cursor Rules', '程序员', 'Cursor编辑器的规则配置系统，通过.cursorrules文件定制AI行为，社区共享最佳实践规则。', 'Cursor editor rules system customizing AI behavior via .cursorrules files with community sharing.', '免费', 4.4, 'https://cursor.directory', ARRAY['AI行为自定义规则','社区规则共享','项目级别配置','框架专属规则'], false, false, false, 'cursor-rules', 'Cursor配置', 'Cursor AI行为自定义规则配置', ARRAY['定制化程度高','社区规则丰富','免费使用'], ARRAY['需要Cursor编辑器','规则质量参差'], 'Cursor用户提升AI输出质量的配置', ARRAY['免费'], 500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Zed Editor', 'Zed Editor', '程序员', '高性能AI代码编辑器，用Rust构建速度极快，内置AI助手和实时协作功能，开源免费。', 'High-performance AI code editor built in Rust with built-in AI assistant and real-time collaboration.', '免费', 4.5, 'https://zed.dev', ARRAY['极速编辑器性能','内置AI助手','实时多人协作','开源免费'], false, true, false, 'zed-editor', 'AI编辑器', 'Rust构建极速AI代码编辑器', ARRAY['速度最快','实时协作好','开源免费'], ARRAY['插件生态不如VSCode','功能仍在完善'], '追求极速编辑体验的开发者推荐', ARRAY['免费','热门'], 400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Fitten Code', 'Fitten Code', '程序员', '国产AI代码补全工具，对中文注释和国内技术栈支持好，免费使用，响应速度快。', 'Chinese AI code completion tool with good Chinese comment support and fast response.', '免费', 4.3, 'https://code.fittentech.com', ARRAY['中文注释支持好','国内技术栈优化','免费无限使用','多IDE支持'], false, false, false, 'fitten-code', 'AI补全', '国产中文友好AI代码补全工具', ARRAY['中文支持最好','完全免费','响应速度快'], ARRAY['英文场景不如Copilot','功能相对基础'], '国内开发者的免费AI代码补全选择', ARRAY['免费'], 300, 'active');
