-- 设计师分类（1-25）

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Midjourney', 'Midjourney', '设计师', '全球最受欢迎的AI图像生成工具，通过文字描述生成高质量艺术图像，设计师必备创作利器。', 'World most popular AI image generator creating high-quality art from text prompts.', '$10/月', 4.9, 'https://www.midjourney.com', ARRAY['文字转高质量图像','多种艺术风格','图像变体生成','社区创作分享'], true, true, false, 'midjourney', 'AI绘图', '设计师必备AI图像生成神器', ARRAY['图像质量业界最高','风格多样可控','社区资源丰富'], ARRAY['需要Discord使用','学习提示词有门槛'], '设计灵感和概念图首选工具', ARRAY['热门','TG精选'], 5000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Adobe Firefly', 'Adobe Firefly', '设计师', 'Adobe推出的生成式AI设计工具，深度集成Photoshop和Illustrator，支持文字生成图像和创意填充。', 'Adobe generative AI integrated with Photoshop and Illustrator for creative design.', '免费+付费', 4.7, 'https://firefly.adobe.com', ARRAY['文字生成图像','创意填充扩展','文字效果生成','深度Adobe集成'], true, true, false, 'adobe-firefly', 'Adobe AI', 'Adobe生态AI创意设计工具', ARRAY['与Adobe软件无缝集成','商用版权有保障','操作直觉化'], ARRAY['高级功能需Creative Cloud','生成速度较慢'], 'Adobe用户升级创作效率首选', ARRAY['热门','今日推荐'], 4900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Figma AI', 'Figma AI', '设计师', 'Figma内置AI功能，支持AI生成UI组件、自动布局、设计稿翻译和原型智能优化。', 'Figma built-in AI for UI component generation, auto layout and prototype optimization.', '免费+付费', 4.7, 'https://www.figma.com', ARRAY['AI生成UI组件','智能自动布局','设计稿AI翻译','原型智能优化'], true, true, false, 'figma-ai', 'UI设计AI', 'Figma内置AI设计助手', ARRAY['与Figma无缝集成','UI生成质量高','团队协作流畅'], ARRAY['高级AI功能需付费','部分功能仍在测试'], 'UI/UX设计师提效必备工具', ARRAY['热门','TG精选'], 4800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Canva AI', 'Canva AI', '设计师', 'Canva内置Magic Studio AI套件，支持文字生成图像、AI背景移除、智能设计建议和一键品牌套用。', 'Canva Magic Studio AI with text-to-image, background removal and smart design suggestions.', '免费+付费', 4.6, 'https://www.canva.com', ARRAY['Magic文字生成图像','AI背景一键移除','智能设计建议','品牌套件一键应用'], true, true, false, 'canva-ai', 'AI设计', 'Canva Magic Studio AI设计套件', ARRAY['操作极其简单','模板资源海量','免费版功能丰富'], ARRAY['专业设计灵活性有限','高级功能需付费'], '非专业设计师快速出图首选', ARRAY['热门','今日推荐'], 4700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Stable Diffusion', 'Stable Diffusion', '设计师', '开源AI图像生成模型，可本地部署，支持高度自定义，拥有庞大的模型和插件生态。', 'Open-source AI image generation model with local deployment and extensive customization.', '免费', 4.7, 'https://stability.ai', ARRAY['完全开源免费','本地私有部署','海量社区模型','高度自定义控制'], true, true, false, 'stable-diffusion', '开源AI绘图', '开源免费的AI图像生成引擎', ARRAY['完全免费无限使用','自定义程度最高','社区模型资源丰富'], ARRAY['需要一定技术门槛','本地部署需要GPU'], '有技术能力的设计师强烈推荐', ARRAY['免费','热门','TG精选'], 4600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('DALL-E 3', 'DALL-E 3', '设计师', 'OpenAI最新图像生成模型，理解复杂提示词能力强，生成图像与描述高度一致，集成于ChatGPT。', 'OpenAI latest image model with strong prompt understanding integrated in ChatGPT.', '免费+付费', 4.6, 'https://openai.com/dall-e-3', ARRAY['复杂提示词理解','图文高度一致','ChatGPT直接调用','API商业集成'], true, true, false, 'dall-e-3', 'AI图像', 'OpenAI最新AI图像生成模型', ARRAY['提示词理解最准确','图文一致性极高','ChatGPT直接使用'], ARRAY['免费版有使用限制','风格不如Midjourney多样'], '需要精确图文一致时首选', ARRAY['热门'], 4500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Runway ML', 'Runway ML', '设计师', '专业AI视频生成和编辑平台，支持文字转视频、视频风格迁移、背景移除和AI特效制作。', 'Professional AI video generation and editing with text-to-video and style transfer.', '$12/月', 4.7, 'https://runwayml.com', ARRAY['文字转视频生成','视频风格迁移','AI背景移除','视频特效制作'], true, true, false, 'runway-ml', 'AI视频', '专业AI视频生成与编辑平台', ARRAY['视频生成质量领先','特效功能专业','创意自由度高'], ARRAY['高质量生成消耗积分多','学习曲线较陡'], '视频设计师和创意人必备工具', ARRAY['热门','TG精选'], 4400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Framer AI', 'Framer AI', '设计师', 'AI驱动的网站设计和发布平台，通过文字描述自动生成完整网站，支持实时编辑和一键发布。', 'AI-powered website design platform that generates full sites from text descriptions.', '免费+付费', 4.6, 'https://www.framer.com', ARRAY['文字生成完整网站','实时可视化编辑','响应式设计自动适配','一键发布上线'], true, true, true, 'framer-ai', 'AI建站', '文字描述自动生成网站平台', ARRAY['建站速度极快','设计质量专业','无需编程知识'], ARRAY['复杂交互需手动调整','免费版有水印'], '快速搭建作品集和落地页首选', ARRAY['热门','今日推荐'], 4300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Khroma', 'Khroma', '设计师', 'AI配色工具，通过学习用户偏好生成个性化配色方案，帮助设计师快速找到完美色彩组合。', 'AI color tool that learns user preferences to generate personalized color palettes.', '免费', 4.5, 'https://www.khroma.co', ARRAY['AI个性化配色学习','无限配色方案生成','色彩搭配预览','颜色代码导出'], true, false, false, 'khroma', 'AI配色', 'AI学习偏好的个性化配色工具', ARRAY['配色方案高度个性化','生成数量无限','操作简单直观'], ARRAY['需要初始训练时间','功能相对单一'], '寻找品牌配色方案的高效工具', ARRAY['免费','热门'], 4200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Looka', 'Looka', '设计师', 'AI品牌设计平台，通过简单问答自动生成专业Logo、品牌视觉系统和品牌资产包。', 'AI brand design platform generating professional logos and brand identity systems.', '$20起', 4.4, 'https://looka.com', ARRAY['AI自动生成Logo','完整品牌视觉系统','品牌资产包导出','多格式文件输出'], false, true, false, 'looka', 'AI品牌', 'AI自动生成专业品牌视觉系统', ARRAY['品牌设计速度极快','视觉系统完整','非设计师也能用'], ARRAY['原创性有限','复杂品牌需专业设计师'], '初创公司快速建立品牌形象首选', ARRAY['热门'], 4100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Remove.bg', 'Remove.bg', '设计师', '专业AI背景移除工具，一键精准抠图，支持批量处理，广泛用于电商产品图和人像处理。', 'Professional AI background removal tool with one-click precision and batch processing.', '免费+付费', 4.7, 'https://www.remove.bg', ARRAY['一键精准背景移除','批量图片处理','API商业集成','高分辨率输出'], true, true, false, 'remove-bg', 'AI抠图', '一键精准AI背景移除工具', ARRAY['抠图精度业界领先','批量处理高效','API集成方便'], ARRAY['免费版分辨率有限','复杂背景偶有误差'], '电商产品图处理的必备工具', ARRAY['热门','TG精选'], 4000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Upscayl', 'Upscayl', '设计师', '免费开源的AI图像超分辨率工具，将低分辨率图片放大4-16倍同时保持清晰度，本地运行。', 'Free open-source AI image upscaler that enlarges images 4-16x while maintaining clarity.', '免费', 4.6, 'https://upscayl.org', ARRAY['图像4-16倍超分辨率','本地私有运行','批量图片处理','多种AI模型选择'], true, false, false, 'upscayl', 'AI超分', '免费开源AI图像超分辨率工具', ARRAY['完全免费开源','本地运行隐私安全','放大效果出色'], ARRAY['需要本地安装','处理速度依赖硬件'], '图片放大清晰化的免费首选', ARRAY['免费','热门'], 3900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Kling AI', 'Kling AI', '设计师', '快手推出的AI视频生成工具，支持文字和图片转高质量视频，物理效果逼真，中文友好。', 'Kuaishou AI video generation tool supporting text and image to high-quality video.', '免费+付费', 4.6, 'https://klingai.com', ARRAY['文字转高质量视频','图片转视频动画','物理效果逼真','中文提示词支持'], true, true, true, 'kling-ai', 'AI视频', '快手出品的高质量AI视频生成', ARRAY['视频质量国内领先','中文支持友好','物理效果逼真'], ARRAY['免费版有水印','长视频生成较慢'], '中文AI视频生成的最佳选择', ARRAY['热门','今日推荐'], 3800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('即梦AI', 'Jimeng AI', '设计师', '字节跳动推出的AI图像和视频生成工具，支持中文提示词，生成效果优秀，免费额度充足。', 'ByteDance AI image and video generation with Chinese prompts and generous free quota.', '免费+付费', 4.5, 'https://jimeng.jianying.com', ARRAY['中文文字生成图像','图片转视频','多种艺术风格','免费额度充足'], true, true, false, 'jimeng-ai', 'AI创作', '字节出品中文AI图像视频生成', ARRAY['中文理解能力强','免费额度慷慨','与剪映深度集成'], ARRAY['部分风格不如Midjourney','商用需注意版权'], '中文AI创作的高性价比选择', ARRAY['免费','热门'], 3700, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Galileo AI', 'Galileo AI', '设计师', 'AI UI设计工具，通过文字描述自动生成完整的UI界面设计稿，可直接导出到Figma。', 'AI UI design tool that generates complete UI designs from text and exports to Figma.', '$19/月', 4.4, 'https://www.usegalileo.ai', ARRAY['文字生成UI界面','完整设计稿输出','一键导出Figma','多平台UI适配'], true, false, true, 'galileo-ai', 'AI界面', '文字描述自动生成UI设计稿', ARRAY['UI生成速度极快','Figma导出方便','设计质量较高'], ARRAY['复杂交互需手动完善','风格自定义有限'], 'UI设计快速出稿的效率工具', ARRAY['今日推荐'], 3600, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Uizard', 'Uizard', '设计师', 'AI驱动的UI/UX设计工具，支持手绘草图转数字原型，文字描述生成界面，快速制作产品原型。', 'AI UI/UX design tool converting sketches to prototypes and text to interfaces.', '免费+付费', 4.3, 'https://uizard.io', ARRAY['手绘草图转数字原型','文字生成UI界面','快速原型制作','团队协作设计'], false, false, false, 'uizard', 'AI原型', '手绘草图转数字原型AI工具', ARRAY['草图转换效果好','原型制作速度快','非设计师友好'], ARRAY['高保真设计能力有限','免费版功能受限'], '产品经理快速制作原型的利器', ARRAY['免费'], 3500, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Pika Labs', 'Pika Labs', '设计师', 'AI视频生成工具，支持文字和图片转视频，擅长动画和创意视频效果，操作简单易上手。', 'AI video generation tool for text and image to video with creative animation effects.', '免费+付费', 4.4, 'https://pika.art', ARRAY['文字转创意视频','图片转动画视频','视频风格迁移','视频时长延伸'], false, true, false, 'pika-labs', 'AI动画', '文字图片转创意动画视频工具', ARRAY['动画效果创意丰富','操作简单易上手','免费版可用'], ARRAY['视频时长有限制','写实效果不如Runway'], '创意动画和短视频制作推荐', ARRAY['热门'], 3400, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Spline AI', 'Spline AI', '设计师', '3D设计工具Spline内置AI功能，支持文字生成3D场景和物体，适合网页3D设计和交互动效。', '3D design tool Spline with AI for generating 3D scenes and objects from text.', '免费+付费', 4.5, 'https://spline.design', ARRAY['文字生成3D场景','3D交互动效设计','网页3D嵌入','实时协作编辑'], true, false, true, 'spline-ai', 'AI 3D设计', '文字生成3D场景的设计工具', ARRAY['3D生成效果出色','网页集成方便','学习曲线平缓'], ARRAY['复杂3D需专业技能','免费版有限制'], '网页3D设计和交互动效首选', ARRAY['今日推荐'], 3300, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Vectorizer.AI', 'Vectorizer.AI', '设计师', 'AI位图转矢量图工具，将JPG/PNG图片自动转换为高质量SVG矢量文件，适合Logo和图标处理。', 'AI bitmap to vector converter turning JPG/PNG into high-quality SVG files.', '免费+付费', 4.5, 'https://vectorizer.ai', ARRAY['位图自动转矢量','高质量SVG输出','细节保留精准','批量转换处理'], true, false, false, 'vectorizer-ai', 'AI矢量化', '位图一键转高质量矢量图工具', ARRAY['转换质量业界领先','细节保留出色','操作极简单'], ARRAY['免费版每月有限次','复杂图片偶有误差'], 'Logo和图标矢量化处理必备', ARRAY['热门'], 3200, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Luma AI', 'Luma AI', '设计师', 'AI 3D场景生成和视频工具，支持文字转视频和图片转3D模型，Dream Machine视频质量出众。', 'AI 3D scene generation and video tool with text-to-video and image-to-3D capabilities.', '免费+付费', 4.6, 'https://lumalabs.ai', ARRAY['文字转高质量视频','图片转3D模型','Dream Machine视频','3D场景捕捉'], true, true, false, 'luma-ai', 'AI 3D视频', 'AI 3D场景生成与视频创作工具', ARRAY['视频质量极高','3D生成效果出色','免费版可体验'], ARRAY['高质量生成消耗积分','等待时间较长'], '3D设计师和视频创作者必备', ARRAY['热门','TG精选'], 3100, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Colorize.cc', 'Colorize.cc', '设计师', 'AI黑白照片上色工具，自动为老照片和黑白图像添加逼真色彩，支持批量处理和高分辨率输出。', 'AI black and white photo colorization tool with realistic colors and batch processing.', '免费+付费', 4.3, 'https://colorize.cc', ARRAY['黑白照片自动上色','色彩逼真自然','批量照片处理','高分辨率输出'], false, false, false, 'colorize-cc', 'AI上色', 'AI黑白照片自动上色工具', ARRAY['上色效果自然逼真','操作极简单','免费版可用'], ARRAY['复杂场景色彩有偏差','免费版分辨率有限'], '老照片修复和黑白图上色推荐', ARRAY['免费'], 3000, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Cleanup.pictures', 'Cleanup.pictures', '设计师', 'AI图像修复工具，一键去除照片中的水印、人物、文字等不需要的元素，填充效果自然。', 'AI image cleanup tool that removes watermarks, people and text with natural fill.', '免费+付费', 4.5, 'https://cleanup.pictures', ARRAY['一键去除水印','人物和物体移除','智能背景填充','批量图片处理'], true, true, false, 'cleanup-pictures', 'AI修图', '一键去除图片多余元素AI工具', ARRAY['去除效果自然','操作极简单','免费版可用'], ARRAY['复杂背景填充有误差','免费版分辨率有限'], '电商图片和照片修复的高效工具', ARRAY['免费','热门'], 2900, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Fontjoy', 'Fontjoy', '设计师', 'AI字体搭配工具，通过深度学习推荐和谐的字体组合，帮助设计师快速找到完美字体配对。', 'AI font pairing tool using deep learning to recommend harmonious font combinations.', '免费', 4.4, 'https://fontjoy.com', ARRAY['AI字体搭配推荐','和谐度智能评分','实时预览效果','一键锁定字体'], false, false, false, 'fontjoy', 'AI字体', 'AI推荐和谐字体搭配组合工具', ARRAY['推荐结果和谐美观','操作极简单','完全免费'], ARRAY['字体库主要为英文','中文字体支持有限'], '英文设计字体搭配的快速工具', ARRAY['免费'], 2800, 'active');

INSERT INTO tools (name, name_en, category, description, description_en, price, rating, official_url, features, is_recommended, is_hot, is_new, slug, short_tag, full_desc, highlights, drawbacks, tg_advice, tags, sort_order, status) VALUES
('Magician for Figma', 'Magician for Figma', '设计师', 'Figma插件形式的AI设计助手，支持文字生成图标、AI文案撰写和设计元素智能生成。', 'Figma plugin AI assistant for icon generation, copywriting and design element creation.', '$6/月', 4.3, 'https://magician.design', ARRAY['Figma内文字生成图标','AI设计文案撰写','设计元素智能生成','一键应用到设计稿'], false, false, false, 'magician-figma', 'Figma AI插件', 'Figma内嵌AI设计辅助插件', ARRAY['Figma集成无缝','图标生成实用','价格亲民'], ARRAY['功能相对基础','生成质量参差'], 'Figma用户提升设计效率的插件', ARRAY['热门'], 2700, 'active');
